plugin_dir = ""

[gabriel]
# If left blank, vehicles will not connect to Gabriel
server_endpoint = ""
telemetry_target_engines = ["telemetry", "obstacle-avoidance"]
video_frames_target_engines = ["obstacle-avoidance"]

[[vehicles]]
# Name of the vehicle.
name = "steppeeagle"
# Whether or not to simulate the vehicle
simulate = false
[vehicles.driver]
# Path of the plugin to run for this device
plugin = "parrot_anafi"
# Additional arguments
args = [
    "--ip", "10.202.0.1",
]
[vehicles.mission]
# Path of the plugin to run for this device
plugin = "test_mission"
# Additional arguments
args = [
    "--kml", "satya.kml",
    "--name", "poly",
]
