[[vehicles]]
# Name of the vehicle.
name = "steppeeagle"
# Whether or not to simulate the vehicle
simulate = false
# Path of the plugin to run for this device
plugin = "steeleagle_aviary"
[vehicles.driver]
# Path of the plugin to run for this device
plugin = "parrot_anafi"
# Additional arguments
args = [
    "--ip", "10.202.0.1",
]
[vehicles.mission]
# Path of the plugin to run for this device
plugin = "test_mission"
# Additional arguments
args = [
    "--kml", "satya.kml",
    "--name", "poly",
]
