// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1;v1";

// Angular offsets or poses in 3 dimensions.
message Pose {
  optional double pitch = 1; // pitch [degrees]
  optional double roll = 2; // roll [degrees]
  optional double yaw = 3; // yaw [degrees]
}

// Representation of velocity in 3-dimensions.
// Axes are organized as:
// - `x_vel`: forward/northward velocity
// - `y_vel`: right/eastward velocity
// - `z_vel`: up velocity
message Velocity {
  optional double x_vel = 1; // forward/north velocity [meters/s]
  optional double y_vel = 2; // right/east velocity [meters/s]
  optional double z_vel = 3; // up velocity [meters/s]
  optional double angular_vel = 4; // angular velocity [degrees/s]
}

// Representation of global position.
message GlobalPosition {
  optional double latitude = 1;
  optional double longitude = 2;
  optional double altitude = 3;
  optional double heading = 4;
}

// Representation of relative position in 3-dimensions.
// Can represent either a body relative position, e.g. 1m forward, 1m right, 1m up
// or a home relative position, e.g. 1m north, 1m east, 1m up of home position.
// Axes are organized as:
// - `x`: forward offset/north offset
// - `y`: right offset/east offset
// - `z``: up offset
message RelativePosition {
  optional double x = 1; // forward offset/north offset [meters]
  optional double y = 2; // right offset/east offset [meters]
  optional double z = 3; // up offset [meters]
  optional double angle = 4; // angular offset [degrees]
}

// Identifies a vehicle registering as a Gabriel client, made available to
// engines alongside any data it subsequently sends.
message VehicleInfo {
  string vehicle_id = 1; // unique identifier of the vehicle
  string model = 2; // model of the vehicle
}
