[project]
name = "steeleagle-backend-detection"
version = "1.0.0"
description = "Object detection using YOLOv5 models"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
   "redis",
   "opencv-python-headless",
   "numpy",
   "pykml",
   "pygeodesy",
   "ultralytics==8.4.66",
   "rfdetr>=1.8.3",
   "supervision>=0.29.1",
   "scipy",
   "Pillow",
   "gabriel-server>=4.1.2",
   "steeleagle-sdk>=1.0.16",
   "torch"
]

[dependency-groups]
dev = [
   "pytest>=8.4.2",
]

[tool.uv]
override-dependencies = [
  "opencv-python ; sys_platform == 'never'",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
