package compiler

import (
	"errors"
	"fmt"
	"go/types"
	"strings"
)

// fieldIR represents a field in a typeIR constructor. In cases
// where fieldIR is an inline constructor, it can link to the
// underlying typeIR.
type fieldIR struct {
	Name string
	Type types.Type
	Link string
}

// typeIR represents a type in the DSL.
type typeIR struct {
	Name   string
	Type   types.Type
	Fields []*fieldIR
}

// transitionIR represents a single transition declaration. Begin is the
// event (or the synthetic "done" event) that triggers the transition, and
// End is the action it transitions to.
type transitionIR struct {
	Begin *typeIR
	End   *typeIR
}

// missionIR represents a full mission.
type missionIR struct {
	Role        string
	Import      []string
	Data        []*typeIR
	Actions     []*typeIR
	Events      []*typeIR
	Start       *typeIR
	Transitions map[string][]*transitionIR
	// Types holds every typeIR by name, including Data/Actions/Events
	// declarations and the synthesized entries built for inline
	// constructors, so a fieldIR's Link can always be resolved back to
	// the typeIR it names.
	Types map[string]*typeIR
}

// doneEvent is the synthetic typeIR standing in for the built-in "done"
// pseudo-event: every action implicitly raises it on completion, so it's
// valid as a transition's event without a matching Events: declaration.
var doneEvent = &typeIR{Name: "done"}

// nameInfo records how a single Data/Actions/Events Decl resolved, so
// later Decls and the Mission stanza can refer back to it by name.
type nameInfo struct {
	decl    *Decl
	section string // "data", "action", or "event"
	ir      *typeIR
}

// linker links an Ast's declarations against a typeRegistry produced by
// loadPackages, building the missionIR that Link returns.
type linker struct {
	registry   *typeRegistry
	errs       []error
	names      map[string]*nameInfo
	ir         *missionIR
	synthCount int // used to generate unique names for inline constructors
}

// Link links an Ast to concrete type declarations generated by the loader,
// enforcing that:
//   - Data declarations resolve to either a Go generic/builtin type or a
//     DSL Datatype (reg.Datatypes).
//   - Actions declarations resolve to a DSL Action (reg.Actions).
//   - Events declarations resolve to a DSL Event (reg.Events).
//   - the Mission stanza's Start action, every During block's action, and
//     every transition's action/event are all previously declared, with
//     "done" accepted in place of a declared event.
//
// Every Decl's Attrs are also linked into its typeIR.Fields: each field's
// value is either a Go generic (a literal Float/Int/String/Kml, or a
// homogeneous array of such), or a link to another typeIR - an Ident
// reference to a previously declared Data/Actions/Events Decl, or an
// inline constructor (itself linked to a synthesized typeIR built from its
// own Args, registered in the returned missionIR's Types map).
//
// It returns the resulting missionIR, populated as far as linking got,
// together with every problem found joined into a single error (nil if
// ast linked cleanly).
func Link(ast *Ast, reg *typeRegistry) (*missionIR, error) {
	l := &linker{
		registry: reg,
		names:    map[string]*nameInfo{},
		ir: &missionIR{
			Transitions: make(map[string][]*transitionIR),
			Types:       map[string]*typeIR{},
		},
	}

	if ast.Role != nil {
		l.ir.Role = ast.Role.Name
	}
	if ast.Import != nil {
		for _, imp := range ast.Import.Imports {
			l.ir.Import = append(l.ir.Import, imp.Path)
		}
	}

	if ast.Data != nil {
		for _, d := range ast.Data.Decls {
			if t := l.linkDecl(d, "data", l.resolveData); t != nil {
				l.ir.Data = append(l.ir.Data, t)
			}
		}
	}
	if ast.Actions != nil {
		for _, d := range ast.Actions.Decls {
			if t := l.linkDecl(d, "action", l.resolveAction); t != nil {
				l.ir.Actions = append(l.ir.Actions, t)
			}
		}
	}
	if ast.Events != nil {
		for _, d := range ast.Events.Decls {
			if t := l.linkDecl(d, "event", l.resolveEvent); t != nil {
				l.ir.Events = append(l.ir.Events, t)
			}
		}
	}

	l.linkMission(ast.Mission)

	return l.ir, errors.Join(l.errs...)
}

func (l *linker) errorf(pos fmt.Stringer, format string, args ...any) {
	l.errs = append(l.errs, fmt.Errorf("%s: %s", pos, fmt.Sprintf(format, args...)))
}

// linkDecl records d under its name (checking for duplicate declarations
// across Data/Actions/Events) and resolves its type via resolve. It
// returns the resulting typeIR, or nil if d was a duplicate or its type
// didn't resolve (either way, an error has already been recorded).
func (l *linker) linkDecl(d *Decl, section string, resolve func(*Decl) (types.Type, bool)) *typeIR {
	if prev, dup := l.names[d.Name]; dup {
		l.errorf(d.Pos, "%q is already declared (as %s at %s)", d.Name, prev.section, prev.decl.Pos)
		return nil
	}

	info := &nameInfo{decl: d, section: section}
	l.names[d.Name] = info

	t, ok := resolve(d)
	if !ok {
		return nil
	}

	ir := &typeIR{Name: d.Name, Type: t}
	info.ir = ir
	l.ir.Types[d.Name] = ir
	ir.Fields = l.linkAttrs(t, d.Attrs)
	return ir
}

// linkAttrs resolves each of attrs into a fieldIR: Name is the attr's key,
// and Type/Link come from resolving its value (see resolveValue). Each
// attr's Key must name an actual field of target (target must be a struct
// type at all if there are any attrs); a misreferenced field or a
// value that fails to resolve is skipped (an error has already been
// recorded).
func (l *linker) linkAttrs(target types.Type, attrs []*Attr) []*fieldIR {
	if len(attrs) == 0 {
		return nil
	}

	structType, _ := target.Underlying().(*types.Struct)
	if structType == nil {
		l.errorf(attrs[0].Value.Pos, "type %s has no parameters", target)
		return nil
	}
	pkg := declPackage(target)

	var fields []*fieldIR
	for _, a := range attrs {
		obj, _, _ := types.LookupFieldOrMethod(target, true, pkg, a.Key)
		fld, ok := obj.(*types.Var)
		if !ok || fld == nil || !fld.IsField() {
			l.errorf(a.Value.Pos, "unknown parameter %q for type %s", a.Key, target)
			continue
		}

		t, link, ok := l.resolveValue(a.Value)
		if !ok {
			continue
		}
		fields = append(fields, &fieldIR{
			Name: a.Key,
			Type: t,
			Link: link,
		})
	}
	return fields
}

// declPackage returns the *types.Package that owns t, used so
// LookupFieldOrMethod can correctly resolve unexported-identifier
// visibility.
func declPackage(t types.Type) *types.Package {
	if named, ok := t.(*types.Named); ok {
		return named.Obj().Pkg()
	}
	return nil
}

// resolveValue resolves val to its Go type and, if it links to another
// typeIR rather than being a plain Go generic, that typeIR's name:
//   - a literal Float/Int/String/Kml resolves to the matching Go generic
//     type (float64/int64/string/string), with no link.
//   - an Ident resolves to the type of the Data/Actions/Events Decl it
//     names, linked to that Decl's typeIR.
//   - an inline constructor resolves to its DSL Datatype, linked to a
//     synthesized typeIR (registered in l.ir.Types) built the same way a
//     Data declaration is, recursively linking its own Args.
//   - an array resolves to a slice of its (homogeneous) element type; all
//     elements must resolve to the same type, and per-element links aren't
//     tracked (fieldIR only carries a single Link).
func (l *linker) resolveValue(val *Value) (types.Type, string, bool) {
	switch {
	case val.Float != nil:
		t, _ := genericType("float64")
		return t, "", true
	case val.Int != nil:
		t, _ := genericType("int64")
		return t, "", true
	case val.String != nil:
		t, _ := genericType("string")
		return t, "", true
	case val.Kml != nil:
		t, _ := genericType("string")
		return t, "", true
	case val.Ident != nil:
		info, ok := l.names[*val.Ident]
		if !ok || info.ir == nil {
			l.errorf(val.Pos, "identifier %q does not refer to a previously declared Data, Actions, or Events declaration", *val.Ident)
			return nil, "", false
		}
		return info.ir.Type, info.ir.Name, true
	case val.Inline != nil:
		return l.resolveInline(val.Pos, val.Inline)
	case val.Array != nil:
		return l.resolveArray(val.Pos, val.Array)
	default:
		l.errorf(val.Pos, "value has no recognized literal form")
		return nil, "", false
	}
}

// resolveInline links an inline constructor value to a synthesized typeIR,
// registered in l.ir.Types under a generated name so it can be found via
// the returned Link. ctor.Type must be a DSL Datatype; its own Args are
// recursively linked into the synthesized typeIR's Fields.
func (l *linker) resolveInline(pos fmt.Stringer, ctor *InlineCtor) (types.Type, string, bool) {
	bt, ok := l.lookupBase(l.registry.Datatypes, typesPkgPath, string(ctor.Type))
	if !ok {
		l.errorf(pos, "constructor %q: not a datatype", ctor.Type)
		return nil, "", false
	}

	name := fmt.Sprintf("<inline:%s:%d>", ctor.Type, l.synthCount)
	l.synthCount++

	ir := &typeIR{Name: name, Type: bt.Type}
	l.ir.Types[name] = ir
	ir.Fields = l.linkAttrs(bt.Type, ctor.Args)
	return bt.Type, name, true
}

// resolveArray resolves an array value to a slice of its element type.
// Every element must resolve to the same type.
func (l *linker) resolveArray(pos fmt.Stringer, arr *ArrayValue) (types.Type, string, bool) {
	if len(arr.Elems) == 0 {
		l.errorf(pos, "empty array: cannot infer an element type")
		return nil, "", false
	}
	var elemType types.Type
	for _, e := range arr.Elems {
		t, _, ok := l.resolveValue(e)
		if !ok {
			return nil, "", false
		}
		if elemType == nil {
			elemType = t
			continue
		}
		if !types.Identical(elemType, t) {
			l.errorf(e.Pos, "array element type %s does not match earlier element type %s", t, elemType)
			return nil, "", false
		}
	}
	return types.NewSlice(elemType), "", true
}

// resolveData resolves a Data declaration's type: a DSL Datatype, or a Go
// generic/builtin type.
func (l *linker) resolveData(d *Decl) (types.Type, bool) {
	if bt, ok := l.lookupBase(l.registry.Datatypes, typesPkgPath, string(d.Type)); ok {
		return bt.Type, true
	}
	if t, ok := genericType(string(d.Type)); ok {
		return t, true
	}
	l.errorf(d.Pos, "%s %q: not a datatype or a generic type", d.Name, d.Type)
	return nil, false
}

// resolveAction resolves an Actions declaration's type: it must be a DSL
// Action.
func (l *linker) resolveAction(d *Decl) (types.Type, bool) {
	bt, ok := l.lookupBase(l.registry.Actions, actionsPkgPath, string(d.Type))
	if !ok {
		l.errorf(d.Pos, "%s %q: not a declared action", d.Name, d.Type)
		return nil, false
	}
	return bt.Type, true
}

// resolveEvent resolves an Events declaration's type: it must be a DSL
// Event.
func (l *linker) resolveEvent(d *Decl) (types.Type, bool) {
	bt, ok := l.lookupBase(l.registry.Events, eventsPkgPath, string(d.Type))
	if !ok {
		l.errorf(d.Pos, "%s %q: not a declared event", d.Name, d.Type)
		return nil, false
	}
	return bt.Type, true
}

// lookupBase resolves name (a Decl's TypeName - "Ident" or
// "qualifier.Ident") against reg. A qualified name is looked up as-is; an
// unqualified name is looked up under basePath's qualifier (respecting any
// Import alias that overrides it), matching how loadPackages keys its
// registry maps.
func (l *linker) lookupBase(reg map[string]baseType, basePath, name string) (baseType, bool) {
	if strings.Contains(name, ".") {
		bt, ok := reg[name]
		return bt, ok
	}
	qualifier := l.baseQualifier(basePath)
	if qualifier == "" {
		return baseType{}, false
	}
	bt, ok := reg[qualifier+"."+name]
	return bt, ok
}

// baseQualifier returns the qualifier used for one of the fixed base
// package paths (steeleaglePkgs), respecting any Import alias that
// overrides it - the same rule loadPackages itself applies when building
// its registry keys.
func (l *linker) baseQualifier(path string) string {
	if alias, ok := l.registry.Alias[path]; ok && alias != "" {
		return alias
	}
	if pkg, ok := l.registry.Packages[path]; ok && pkg.Types != nil {
		return pkg.Types.Name()
	}
	return ""
}

// genericType resolves name against Go's universe of builtin types (int,
// float64, string, bool, ...), the DSL's "generic" types. A capitalized
// spelling (e.g. "Bool") is also accepted, matching the DSL's Ident casing.
func genericType(name string) (types.Type, bool) {
	if obj := types.Universe.Lookup(name); obj != nil {
		if tn, ok := obj.(*types.TypeName); ok {
			return tn.Type(), true
		}
	}
	if lower := strings.ToLower(name); lower != name {
		if obj := types.Universe.Lookup(lower); obj != nil {
			if tn, ok := obj.(*types.TypeName); ok {
				return tn.Type(), true
			}
		}
	}
	return nil, false
}

// linkMission checks that the Mission stanza's Start action, every During
// block's action, and every transition's action/event were all previously
// declared - "done" is accepted as a transition's event in place of a
// declared event - and builds the corresponding missionIR fields.
func (l *linker) linkMission(m *MissionStanza) {
	if m == nil {
		return
	}

	action := func(pos fmt.Stringer, name string) *typeIR {
		info, ok := l.names[name]
		if !ok || info.section != "action" {
			l.errorf(pos, "mission references %q, which is not a declared action", name)
			return nil
		}
		return info.ir
	}
	event := func(pos fmt.Stringer, name string) *typeIR {
		if name == "done" {
			return doneEvent
		}
		info, ok := l.names[name]
		if !ok || info.section != "event" {
			l.errorf(pos, "mission references %q, which is not a declared event or %q", name, "done")
			return nil
		}
		return info.ir
	}

	l.ir.Start = action(m.Pos, m.Start)
	for _, blk := range m.Blocks {
		action(blk.Pos, blk.Action) // During <action>: action must be declared
		for _, r := range blk.Rules {
			l.ir.Transitions[blk.Action] = append(l.ir.Transitions[blk.Action], &transitionIR{
				Begin: event(r.Pos, r.Event),
				End:   action(r.Pos, r.Next),
			})
		}
	}
}
