package main

import (
	"errors"
	"fmt"
	"go/types"
	"strings"
)

// fieldIR represents a single resolved value: a struct field's value, an
// option's argument, or an array element. Type is always the Go type this
// value must be assignable to at its use site (a struct field's declared
// type, an option's argument type, or a slice's element type) -- not
// necessarily the type of whatever produced the value, so generator.go can
// tell (e.g. by pointer-ness) whether a Link needs to be taken by address.
//
// Exactly one of Float/Int/String/Elems/Link/Const is set, except for an
// empty array value, where none are.
type fieldIR struct {
	Name   string // the field/option name this value is assigned to; empty for an array element
	Type   types.Type
	Float  *float64
	Int    *int64
	String *string
	Elems  []*fieldIR   // one per array element, for an array value
	Link   *typeIR      // an Ident reference to a previously declared Data/Actions/Events typeIR, or a synthesized Inline constructor
	Inline bool         // true when Link is a synthesized inline constructor rather than a reference to an already-declared, named typeIR
	Const  *types.Const // an Ident reference to one of Type's exported package-level constants (an enum value)
}

// optionIR represents a single With<Name>(...) functional-option call to be
// collected into a typeIR's Options field.
type optionIR struct {
	Pkg   *types.Package // package declaring the With<Name> constructor
	Name  string         // e.g. "Altitude", rendered as <Pkg>.WithAltitude(Value)
	Value *fieldIR
}

// typeIR represents a type in the DSL.
type typeIR struct {
	Name    string
	Type    types.Type
	Fields  []*fieldIR  // direct struct field assignments
	Options []*optionIR // With<Name>(...) calls collected into the type's Options field
}

// transitionIR represents a single transition declaration. Begin is the
// event (or the reserved "done" event) that triggers the transition, and
// End is the action it transitions to.
type transitionIR struct {
	Begin *typeIR
	End   *typeIR
}

// missionIR represents a full mission.
type missionIR struct {
	Role        string
	Import      []string
	Data        []*typeIR
	Actions     []*typeIR
	Events      []*typeIR
	Start       *typeIR
	Transitions map[string][]*transitionIR
	Types       map[string]*typeIR
}

// doneEvent is the synthetic typeIR standing in for the built-in "done"
// pseudo-event: every action implicitly raises it on completion, so it's
// valid as a transition's event without a matching Events: declaration.
var doneEvent = &typeIR{Name: "done"}

// nameInfo records how a single Data/Actions/Events Decl resolved, so
// later Decls and the Mission stanza can refer back to it by name.
type nameInfo struct {
	decl    *Decl
	section string // "data", "action", or "event"
	ir      *typeIR
}

// linker links an AST's declarations against a typeRegistry produced by
// loadPackages, building the missionIR that Link returns.
type linker struct {
	registry *typeRegistry
	errs     []error
	names    map[string]*nameInfo
	ir       *missionIR
}

// Link links an AST to concrete type declarations generated by the loader.
// It returns the resulting missionIR, populated as far as linking got,
// together with every problem found joined into a single error.
func Link(ast *Ast, reg *typeRegistry) (*missionIR, error) {
	l := &linker{
		registry: reg,
		names:    map[string]*nameInfo{},
		ir: &missionIR{
			Transitions: make(map[string][]*transitionIR),
			Types:       map[string]*typeIR{},
		},
	}

	if ast.Role != nil {
		l.ir.Role = ast.Role.Name
	}
	if ast.Import != nil {
		for _, imp := range ast.Import.Imports {
			l.ir.Import = append(l.ir.Import, imp.Path)
		}
	}
	if ast.Data != nil {
		for _, d := range ast.Data.Decls {
			if t := l.linkDecl(d, "data", l.resolveData); t != nil {
				l.ir.Data = append(l.ir.Data, t)
			}
		}
	}
	if ast.Actions != nil {
		for _, d := range ast.Actions.Decls {
			if t := l.linkDecl(d, "action", l.resolveAction); t != nil {
				l.ir.Actions = append(l.ir.Actions, t)
			}
		}
	}
	if ast.Events != nil {
		for _, d := range ast.Events.Decls {
			if t := l.linkDecl(d, "event", l.resolveEvent); t != nil {
				l.ir.Events = append(l.ir.Events, t)
			}
		}
	}

	l.linkMission(ast.Mission)

	return l.ir, errors.Join(l.errs...)
}

// errorf wraps over an error list append. The slice will later be concatenated
// to form the unified linker error.
func (l *linker) errorf(pos fmt.Stringer, format string, args ...any) {
	l.errs = append(l.errs, fmt.Errorf("%s: %s", pos, fmt.Sprintf(format, args...)))
}

// linkDecl records d under its name (checking for duplicate declarations
// across Data/Actions/Events) and resolves its type via resolve.
func (l *linker) linkDecl(d *Decl, section string, resolve func(*Decl) (types.Type, []optionalType, bool)) *typeIR {
	if prev, dup := l.names[d.Name]; dup {
		l.errorf(d.Pos, "%q is already declared (as %s at %s)", d.Name, prev.section, prev.decl.Pos)
		return nil
	}

	info := &nameInfo{decl: d, section: section}
	l.names[d.Name] = info

	t, opts, ok := resolve(d)
	if !ok {
		return nil
	}

	ir := &typeIR{Name: d.Name, Type: t}
	info.ir = ir
	l.ir.Types[d.Name] = ir
	ir.Fields, ir.Options = l.linkAttrs(t, opts, d.Attrs)
	return ir
}

// linkAttrs resolves each of attrs into either a direct struct field
// assignment (returned in fields) or, when its key instead names one of
// options' functional-option constructors, a With<Name>(...) call to
// collect into the type's Options field (returned in opts).
func (l *linker) linkAttrs(target types.Type, options []optionalType, attrs []*Attr) (fields []*fieldIR, opts []*optionIR) {
	if len(attrs) == 0 {
		return nil, nil
	}

	// Get all known struct attributes
	structType, _ := target.Underlying().(*types.Struct)
	if structType == nil && len(options) == 0 {
		l.errorf(attrs[0].Value.Pos, "type %s has no parameters", target)
		return nil, nil
	}
	optsByName := make(map[string]optionalType, len(options))
	for _, o := range options {
		optsByName[o.Name] = o
	}

	var pkg *types.Package
	if structType != nil {
		pkg = declPackage(target)
	}
	for _, a := range attrs {
		if structType != nil {
			if obj, _, _ := types.LookupFieldOrMethod(target, true, pkg, a.Key); obj != nil {
				if fld, ok := obj.(*types.Var); ok && fld.IsField() {
					f, ok := l.resolveValue(fld.Type(), a.Value)
					if !ok {
						continue
					}
					f.Name = a.Key
					fields = append(fields, f)
					continue
				}
			}
		}
		if opt, ok := optsByName[a.Key]; ok {
			v, ok := l.resolveValue(opt.Type, a.Value)
			if !ok {
				continue
			}
			opts = append(opts, &optionIR{Pkg: opt.Pkg, Name: opt.Name, Value: v})
			continue
		}
		l.errorf(a.Value.Pos, "unknown parameter %q for type %s", a.Key, target)
	}
	return fields, opts
}

// declPackage returns the *types.Package that owns t, used so
// LookupFieldOrMethod can correctly resolve unexported-identifier
// visibility.
func declPackage(t types.Type) *types.Package {
	if named, ok := t.(*types.Named); ok {
		return named.Obj().Pkg()
	}
	return nil
}

// lookupBase resolves name against reg. A qualified name is looked up as-is;
// an unqualified name is looked up under basePath's qualifier (respecting any
// Import alias that overrides it), matching how loadPackages keys its
// registry maps.
func (l *linker) lookupBase(reg map[string]baseType, basePath, name string) (baseType, bool) {
	if strings.Contains(name, ".") {
		bt, ok := reg[name]
		return bt, ok
	}
	qualifier := l.baseQualifier(basePath)
	if qualifier == "" {
		return baseType{}, false
	}
	bt, ok := reg[qualifier+"."+name]
	return bt, ok
}

// baseQualifier returns the qualifier used for one of the fixed base
// package paths (steeleaglePkgs), respecting any Import alias that
// overrides it.
func (l *linker) baseQualifier(path string) string {
	if alias, ok := l.registry.Alias[path]; ok && alias != "" {
		return alias
	}
	if pkg, ok := l.registry.Packages[path]; ok && pkg.Types != nil {
		return pkg.Types.Name()
	}
	return ""
}

// genericType resolves name against Go's universe of builtin types (int,
// float64, string, bool, ...), the DSL's "generic" types.
func genericType(name string) (types.Type, bool) {
	if obj := types.Universe.Lookup(name); obj != nil {
		if tn, ok := obj.(*types.TypeName); ok {
			return tn.Type(), true
		}
	}
	if lower := strings.ToLower(name); lower != name {
		if obj := types.Universe.Lookup(lower); obj != nil {
			if tn, ok := obj.(*types.TypeName); ok {
				return tn.Type(), true
			}
		}
	}
	return nil, false
}

// linkMission checks that the Mission stanza's Start action, every During
// block's action, and every transition's action/event were all previously
// declared.
func (l *linker) linkMission(m *MissionStanza) {
	if m == nil {
		return
	}

	action := func(pos fmt.Stringer, name string) *typeIR {
		info, ok := l.names[name]
		if !ok || info.section != "action" {
			l.errorf(pos, "mission references %q, which is not a declared action", name)
			return nil
		}
		return info.ir
	}
	event := func(pos fmt.Stringer, name string) *typeIR {
		if name == "done" {
			return doneEvent
		}
		info, ok := l.names[name]
		if !ok || info.section != "event" {
			l.errorf(pos, "mission references %q, which is not a declared event or %q", name, "done")
			return nil
		}
		return info.ir
	}

	l.ir.Start = action(m.Pos, m.Start)
	for _, blk := range m.Blocks {
		action(blk.Pos, blk.Action) // During <action>: action must be declared
		for _, r := range blk.Rules {
			l.ir.Transitions[blk.Action] = append(l.ir.Transitions[blk.Action], &transitionIR{
				Begin: event(r.Pos, r.Event),
				End:   action(r.Pos, r.Next),
			})
		}
	}
}
