// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle.protocol.v1;

import "steeleagle/protocol/v1/common.proto";

/*
 * Used to manage downstream data consumption and transmission.
 *
 * This service is used to configure data consumer endpoints for frames and 
 * telemetry post-processing. It maintains an internal consumer list of 
 * datasinks that the kernel broadcasts frames and telemetry to. RPC 
 * methods within this service allow for manipulation of this list. It also
 * is used to send reports downstream which can contain freeform data.
 * While a single vehicle will return an OK message as soon as a command 
 * is acked and sent, multiple vehicles will return a message stream
 * when proxied.
 */
service DataService {
  /*
   * Set the datasink consumer list.
   *
   * Takes a list of datasinks and replaces the current consumer list with them.
   */
  rpc SetEnginesForTopic (SetEnginesForTopicRequest)
	returns (stream Response) {}
}

// Denotes where an engine is located.
enum EngineLocation {
  REMOTE = 0; // remote location (network hop required)
  LOCAL = 1; // local location (IPC)
}

// Information about an engine.
message EngineInfo {
  // engine ID
  string id = 1;
  // engine location
  EngineLocation location = 2;  
}

// Data topics created by the vehicle.
enum Topic {
  TELEMETRY = 0; // telemetry from the driver
  IMAGERY = 1; // imagery from the driver
  REPORT = 2; // reports from the mission
}

message SetEnginesForTopicRequest {
  Topic topic = 1; // topic to forward  
  repeated EngineInfo datasinks = 2; // name of target engines
}

message ReportRequest {
  bytes report = 1; // report data, freeform
}
