// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle.protocol.v1;

import "steeleagle/protocol/v1/common.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

// Information about the vehicle battery.
message BatteryInfo {
  uint32 percentage = 1; // battery level [0-100]%
}

// Information about the vehicle GPS fix.
message GPSInfo {
  uint32 satellites = 1; // number of satellites used in GPS fix
}

// Future: information about the vehicle's communication links.
message CommsInfo {}

// Future: transmit the current setpoint of the vehicle so it can be displayed in the GCS
message SetpointInfo {}

// Information about the vehicle position.
message PositionInfo {
  // global position that will be used when returning home
  GlobalPosition home = 1;
  // current global position of the vehicle
  GlobalPosition global_position = 2;
  /*
   * current relative position of the vehicle in the global NEU
   * (North, East, Up) coordinate frame, relative to start
   * position
   */
  RelativePosition relative_position = 3;
  /*
   * current velocity of the vehicle in the global NEU (North, East, Up)
   * coordinate frame
   */
  Velocity velocity_neu = 4;
  /*
   * current velocity of the vehicle in the body (forward, right, up)
   * coordinate frame
   */
  Velocity velocity_body = 5;
  // info on the current vehicle setpoint
  SetpointInfo setpoint_info = 6;
}

// Status of a gimbal.
message GimbalStatus {
  // ID of the gimbal
  uint32 id = 1;
  // current pose in the body (forward, right, up) reference frame
  Pose pose_body = 2;
  // current pose in the NEU (North, East, Up) reference frame
  Pose pose_neu = 3;
}

// Info of all attached gimbals.
message GimbalInfo {
  // list of connected gimbals
  repeated GimbalStatus gimbals = 1;
}

// Battery warnings and alerts.
enum BatteryWarning {
  // the vehicle is above 30% battery
  NONE = 0;
  // the vehicle is below 30% battery
  LOW = 1;
  // the vehicle is below 15% battery
  CRITICAL = 2;
}

// GPS fix warnings and alerts.
enum GPSWarning {
  // GPS readings are nominal and a fix has been achieved
  NO_GPS_WARNING = 0;
  // weak GPS fix, expect errant global position data
  WEAK_SIGNAL = 1;
  // no GPS fix
  NO_FIX = 2;
}

// Magnetometer warnings and alerts.
enum MagnetometerWarning {
  // magnetometer readings are nominal
  NO_MAGNETOMETER_WARNING = 0;
  // the vehicle is experiencing magnetic perturbations
  PERTURBATION = 1;
}

// Connection warnings and alerts.
enum ConnectionWarning {
  // connection to remote server is nominal
  NO_CONNECTION_WARNING = 0;
  // contact has been lost with the remote server
  DISCONNECTED = 1;
  // connection is experiencing interference or is weak
  WEAK_CONNECTION = 2;
}

// Compass warnings and alerts.
enum CompassWarning {
  // absolute heading is nominal
  NO_COMPASS_WARNING = 0;
  // absolute heading is available but may be incorrect
  WEAK_HEADING_LOCK = 1;
  // no absolute heading available from the vehicle
  NO_HEADING_LOCK = 2;
}

// Information about all vehicle warning and alerts.
message AlertInfo {
  // battery warnings
  BatteryWarning battery_warning = 1;
  // GPS warnings
  GPSWarning gps_warning = 2;
  // magnetometer warnings
  MagnetometerWarning magnetometer_warning = 3;
  // connection warnings
  ConnectionWarning connection_warning = 4;
  // compass warnings
  CompassWarning compass_warning = 5;
}

/*
 * Telemetry message for the vehicle, originating from the driver module.
 *
 * This message provides frame data from currently streaming imaging sensors. It
 * is one of two message (`Telemetry`, `Frame`) that is broadcast by the driver.
 */
message Telemetry {
  // timestamp of message
  google.protobuf.Timestamp timestamp = 1;
  // battery info
  BatteryInfo battery_info = 2;
  // GPS and satellite info
  GPSInfo gps_info = 3;
  // communication link info
  CommsInfo comms_info = 4;
  // positional info about the vehicle
  PositionInfo position_info = 5;
  // status on attached gimbals and their orientations
  GimbalInfo gimbal_info = 6;
  // enumeration of vehicle warnings
  AlertInfo alert_info = 7;
}

// Raw camera frames
message RawFrame {
  // capture timestamp of the frame
  google.protobuf.Timestamp timestamp = 1;
  // raw bytes representing the frame
  bytes data = 2;
  // horizontal frame resolution in pixels
  uint64 h_res = 3;
  // vertical frame resolution in pixels
  uint64 v_res = 4;
  // depth resolution in pixels
  uint64 d_res = 5;
  // number of channels
  uint64 channels = 6;
  // frame ID for future correlation
  uint64 id = 7;
  // positional info about the vehicle
  PositionInfo position_info = 8;
  // status on gimbal this frame is attached to, if applicable
  GimbalStatus gimbal_info = 9;
  // ID of origin camera
  uint64 camera_id = 10;
}

// Compressed camera frames (JPG encoded)
message EncodedFrame {
  // capture timestamp of the frame
  google.protobuf.Timestamp timestamp = 1;
  // encoded bytes representing the frame
  bytes encoded_data = 2;
  // frame ID for future correlation
  uint64 id = 3;
  // positional info about the vehicle
  PositionInfo position_info = 4;
  // status on gimbal this frame is attached to, if applicable
  GimbalStatus gimbal_info = 5;
  // ID of origin camera
  uint64 camera_id = 6;
}
