#####################################################################
# NOTE: THIS FILE IS AUTOGENERATED BY GENERATE_TYPES.PY. DO NOT EDIT!
#####################################################################
from pydantic import Field

from ....compiler.registry import register_data
from ...base import Datatype


@register_data
class Timestamp(Datatype):
    """Unix timestamp with nanosecond resolution (seconds since 1970-01-01T00:00:00Z)."""

    seconds: int = Field(description="Seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.")
    nanos: int = Field(description="Sub-second fractions at nanosecond resolution [0, 999999999].")
