#####################################################################
# NOTE: THIS FILE IS AUTOGENERATED BY GENERATE_TYPES.PY. DO NOT EDIT!
#####################################################################
from enum import Enum

from pydantic import Field

from ....compiler.registry import register_data
from ...base import Datatype
from . import common as common


class AltitudeMode(int, Enum):
    """Altitude mode: ABSOLUTE(0)=meters above MSL, RELATIVE(1)=meters above takeoff."""

    ABSOLUTE = 0
    RELATIVE = 1


class HeadingMode(int, Enum):
    """Heading mode: TO_TARGET(0)=orient towards target, HEADING_START(1)=orient to given heading."""

    TO_TARGET = 0
    HEADING_START = 1


class ReferenceFrame(int, Enum):
    """Reference frame: BODY(0)=vehicle frame, NEU(1)=North-East-Up frame."""

    BODY = 0
    NEU = 1


class PoseMode(int, Enum):
    """Pose mode: ANGLE(0)=absolute angle, OFFSET(1)=offset from current, VELOCITY(2)=rotational velocity."""

    ANGLE = 0
    OFFSET = 1
    VELOCITY = 2


@register_data
class ImagingSensorConfiguration(Datatype):
    """Configuration for an imaging sensor stream."""

    id: int = Field(description="Target imaging sensor ID.")
    set_primary: bool = Field(description="Set this sensor as the primary stream.")
    set_fps: int = Field(description="Target FPS for the stream.")
