[steeleagle_tak]
; redis connection settings
REDIS_HOST=localhost
REDIS_PORT=6379
;REDIS_USERNAME=
;REDIS_PASSWORD=

; TAK/CoT connection settings
COT_URL=log://stdout
COT_STALE=120

; reporting interval
POLL_INTERVAL=1

; detection settings
DETECTION_POLL_ENABLED=1
DETECTION_POLL_INTERVAL=5
DETECTION_TTL=600

; Detection class to CoT type mapping (default to a-u-G-I if not mapped)
DETECTION_CLASS_MAP=person:a-u-G-I,car:a-u-G-F,vehicle:a-u-G-F
