#
# Minimal taky configuration file that starts a tcp listener on port 8088
#
[taky]
# System hostname
#hostname=taky.local
# The TAK Server nodeId
#node_id=TAKY
# The IP to bind to. Defaults to 0.0.0.0. To use IPv6, set to "::"
#bind_ip=
# The server's public IP address
#public_ip=

[cot_server]
# If left blank, taky will listen on 8087 without SSL, or 8089 with SSL
port=8088
# Where to store a log of .cot messages from the client for debug purposes
#log_cot=/var/taky/logs
# The monitor IP address. Recommend 127.0.0.1
#mon_ip=127.0.0.1
# Pick any port to enable the monitor server (ssl must be enabled)
#mon_port=12345

[dp_server]
# Where user datapackage uploads are stored.
# For quick testing, set to /tmp/taky
#upload_path=/var/taky/dp-user

[ssl]
# SSL is disabled by default. Set enabled to "true" to enable
#enabled=false

# Should taky require clients to have a certificate?
#client_cert_required=false

# The server certificate or certificate+keyfile
#cert=/etc/taky/ssl/server.crt

# Specify the SSL key path
#key=/etc/taky/ssl/server.key

# Specify the SSL key password (if required)
#key_pw=
