// Command compiler's generator renders a linked missionIR as a standalone
// Go program (main.go): every Data/Actions/Events declaration is
// instantiated as a package-level var, wired into a dsl/runtime.DslRuntime,
// which is then run to completion.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	dslPkgImportPath     = "github.com/cmusatyalab/steeleagle/sdk/dsl"
	runtimePkgImportPath = "github.com/cmusatyalab/steeleagle/sdk/dsl/runtime"
)

// generator renders a missionIR as Go source, tracking which packages get
// referenced (and under what alias) along the way.
type generator struct {
	ir          *missionIR
	userAliases map[string]string // import path -> alias from the mission's Import stanza (registry.Alias)
	pkgAlias    map[string]string // import path -> alias chosen for generated source
	aliasTaken  map[string]bool
}

// Generate renders ir as a complete main.go and writes it to
// filepath.Join(dir, "main.go"). aliases is the typeRegistry's Alias map,
// reused so generated references match whatever qualifier the mission's own
// Import stanza used.
func Generate(ir *missionIR, aliases map[string]string, dir string) error {
	g := newGenerator(ir, aliases)

	var body bytes.Buffer
	g.writeVars(&body)
	g.writeMain(&body)

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by the SteelEagle DSL compiler. DO NOT EDIT.")
	fmt.Fprintln(&out, "package main")
	fmt.Fprintln(&out)
	g.writeImports(&out)
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("generated main.go is not valid Go: %w\n%s", err, out.String())
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), formatted, 0o644); err != nil {
		return err
	}

	// main.go's own imports (grpc, dsl/runtime, and every base/mission
	// package g.qualifier touched) aren't yet declared in dir's go.mod --
	// only the replaced modules themselves are. "go mod tidy" adds them,
	// resolving purely against dir's go.sum (copied from repoRoot) and the
	// module cache, so this needs no network access for anything repoRoot
	// itself already depends on.
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("go mod tidy: %w\n%s", err, out)
	}
	return nil
}

func newGenerator(ir *missionIR, aliases map[string]string) *generator {
	g := &generator{
		ir:          ir,
		userAliases: aliases,
		pkgAlias:    map[string]string{},
		aliasTaken:  map[string]bool{},
	}
	// Reserved first, so a mission-declared package never displaces the
	// fixed identifiers writeMain's hand-written source depends on.
	g.reserve("context", "context")
	g.reserve("fmt", "fmt")
	g.reserve("os", "os")
	g.reserve("signal", "os/signal")
	g.reserve("syscall", "syscall")
	g.reserve("grpc", "google.golang.org/grpc")
	g.reserve("insecure", "google.golang.org/grpc/credentials/insecure")
	g.reserve("dsl", dslPkgImportPath)
	g.reserve("runtime", runtimePkgImportPath)
	return g
}

// reserve registers alias for path unconditionally, without collision
// checking (used only for the fixed imports writeMain's source names).
func (g *generator) reserve(alias, path string) {
	g.pkgAlias[path] = alias
	g.aliasTaken[alias] = true
}

// qualifier returns pkg's chosen identifier for use in generated source,
// registering it (and pkg's import path) the first time it's seen. It
// satisfies go/types.Qualifier.
func (g *generator) qualifier(pkg *types.Package) string {
	if pkg == nil {
		return ""
	}
	path := pkg.Path()
	if alias, ok := g.pkgAlias[path]; ok {
		return alias
	}
	alias := g.userAliases[path]
	if alias == "" {
		alias = pkg.Name()
	}
	for g.aliasTaken[alias] {
		alias += "_"
	}
	g.aliasTaken[alias] = true
	g.pkgAlias[path] = alias
	return alias
}

// typeString renders t as a Go type expression, qualifying every named
// type's package per g.qualifier.
func (g *generator) typeString(t types.Type) string {
	return types.TypeString(t, g.qualifier)
}

// varName returns the package-level identifier generated for a top-level
// Data/Actions/Events declaration named name, escaping the rare case where
// a mission author's DSL identifier collides with a Go keyword.
func varName(name string) string {
	if token.Lookup(name).IsKeyword() {
		return name + "_"
	}
	return name
}

// renderValue renders f as a Go value expression.
func (g *generator) renderValue(f *fieldIR) string {
	switch {
	case f.Float != nil:
		return fmt.Sprintf("%s(%s)", g.typeString(f.Type), strconv.FormatFloat(*f.Float, 'g', -1, 64))
	case f.Int != nil:
		return fmt.Sprintf("%s(%d)", g.typeString(f.Type), *f.Int)
	case f.String != nil:
		return fmt.Sprintf("%s(%q)", g.typeString(f.Type), *f.String)
	case f.Link != nil:
		return g.renderLink(f.Type, f.Link, f.Inline)
	case f.Const != nil:
		return fmt.Sprintf("%s.%s", g.qualifier(f.Const.Pkg()), f.Const.Name())
	case f.Elems != nil:
		var b strings.Builder
		fmt.Fprintf(&b, "%s{\n", g.typeString(f.Type))
		for _, e := range f.Elems {
			fmt.Fprintf(&b, "%s,\n", g.renderValue(e))
		}
		b.WriteString("}")
		return b.String()
	default:
		// An empty array literal is the only value with none of the above set.
		return g.typeString(f.Type) + "{}"
	}
}

// renderLink renders a reference to link -- either a nested composite
// literal (an inline constructor) or the identifier of an already-declared
// top-level var (an Ident cross-reference) -- taking its address when
// target expects a pointer.
func (g *generator) renderLink(target types.Type, link *typeIR, inline bool) string {
	var expr string
	if inline {
		expr = g.renderComposite(link)
	} else {
		expr = varName(link.Name)
	}
	if _, wantsPointer := target.(*types.Pointer); wantsPointer {
		return "&" + expr
	}
	return expr
}

// renderComposite renders t's Fields and Options as a Go composite literal.
// Options collect into a field assumed to be named "Options" (every
// options-bearing base type in this repo names it that), rendered as one
// With<Name>(...) call per option.
func (g *generator) renderComposite(t *typeIR) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s{\n", g.typeString(t.Type))
	for _, f := range t.Fields {
		fmt.Fprintf(&b, "%s: %s,\n", f.Name, g.renderValue(f))
	}
	if len(t.Options) > 0 {
		optType, constraint, ok := g.optionsFieldConstraint(t)
		if !ok {
			// linkAttrs already proved this type has options; a missing
			// "Options" field means the base package doesn't follow this
			// repo's naming convention for it.
			optType, constraint = types.NewSlice(types.Typ[types.Invalid]), types.Typ[types.Invalid]
		}
		fmt.Fprintf(&b, "Options: %s{\n", g.typeString(optType))
		for _, o := range t.Options {
			targs := ""
			if withFuncIsGeneric(o.Pkg, o.Name) {
				// A generic With<Name>'s type parameter only appears in
				// its return type (func(T)), so Go can't infer it from
				// the argument alone -- it must be spelled out explicitly.
				targs = "[" + g.typeString(constraint) + "]"
			}
			fmt.Fprintf(&b, "%s.With%s%s(%s),\n", g.qualifier(o.Pkg), o.Name, targs, g.renderValue(o.Value))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}")
	return b.String()
}

// optionsFieldConstraint looks up t.Type's "Options" field -- expected to
// be a []opt.Option[T]-shaped slice -- and returns both its declared type
// and its type argument T (the constraint every With<Name> constructor for
// t.Options must be explicitly instantiated with).
func (g *generator) optionsFieldConstraint(t *typeIR) (fieldType, constraint types.Type, ok bool) {
	obj, _, _ := types.LookupFieldOrMethod(t.Type, true, declPackage(t.Type), "Options")
	fld, ok := obj.(*types.Var)
	if !ok || !fld.IsField() {
		return nil, nil, false
	}
	fieldType = fld.Type()
	slice, ok := fieldType.Underlying().(*types.Slice)
	if !ok {
		return nil, nil, false
	}
	named, ok := slice.Elem().(*types.Named)
	if !ok {
		return nil, nil, false
	}
	targs := named.TypeArgs()
	if targs == nil || targs.Len() != 1 {
		return nil, nil, false
	}
	return fieldType, targs.At(0), true
}

// withFuncIsGeneric reports whether pkg's With<name> constructor is a
// generic function (as opposed to one written against a single concrete
// option type), which decides whether the constraint type argument needs
// to be spelled out explicitly at its call site.
func withFuncIsGeneric(pkg *types.Package, name string) bool {
	if pkg == nil {
		return false
	}
	fn, ok := pkg.Scope().Lookup("With" + name).(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	return ok && sig.TypeParams().Len() > 0
}

// writeVars emits one package-level var per Data/Actions/Events
// declaration, in declaration order. Order matters: an Ident
// cross-reference can only name a previously declared var, so Data always
// precedes the Actions/Events that might reference it, and within each
// section, source order is preserved.
func (g *generator) writeVars(w io.Writer) {
	var decls []*typeIR
	decls = append(decls, g.ir.Data...)
	decls = append(decls, g.ir.Actions...)
	decls = append(decls, g.ir.Events...)
	for _, d := range decls {
		fmt.Fprintf(w, "var %s = %s\n\n", varName(d.Name), g.renderComposite(d))
	}
}

// actionOrEventRef renders a reference to d suitable for a
// map[string]dsl.Action / map[string]dsl.Event entry: the address of its
// package-level var, since every base Action/Event/Datatype in this repo
// implements its DSL interface on a pointer receiver.
func (g *generator) actionOrEventRef(d *typeIR) string {
	return "&" + varName(d.Name)
}

// writeMain emits func main(): it dials the driver over the Unix domain
// socket named by CLIENT_SOCKET, builds the actions/events/transitions maps
// from ir, and runs the mission to completion via dsl/runtime.DslRuntime.
func (g *generator) writeMain(w io.Writer) {
	fmt.Fprintf(w, "func main() {\n")
	fmt.Fprintf(w, "socket := os.Getenv(%q)\n", "CLIENT_SOCKET")
	fmt.Fprintf(w, "if socket == \"\" {\n")
	fmt.Fprintf(w, "fmt.Fprintln(os.Stderr, \"CLIENT_SOCKET environment variable must be set\")\n")
	fmt.Fprintf(w, "os.Exit(1)\n")
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "conn, err := grpc.NewClient(\"unix://\"+socket, grpc.WithTransportCredentials(insecure.NewCredentials()))\n")
	fmt.Fprintf(w, "if err != nil {\n")
	fmt.Fprintf(w, "fmt.Fprintf(os.Stderr, \"dialing %%s: %%v\\n\", socket, err)\n")
	fmt.Fprintf(w, "os.Exit(1)\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "defer conn.Close()\n\n")

	fmt.Fprintf(w, "actions := map[string]dsl.Action{\n")
	for _, a := range g.ir.Actions {
		fmt.Fprintf(w, "%q: %s,\n", a.Name, g.actionOrEventRef(a))
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "events := map[string]dsl.Event{\n")
	for _, e := range g.ir.Events {
		fmt.Fprintf(w, "%q: %s,\n", e.Name, g.actionOrEventRef(e))
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "transitions := map[string]map[string]string{\n")
	states := make([]string, 0, len(g.ir.Transitions))
	for s := range g.ir.Transitions {
		states = append(states, s)
	}
	sort.Strings(states)
	for _, s := range states {
		fmt.Fprintf(w, "%q: {\n", s)
		for _, t := range g.ir.Transitions[s] {
			fmt.Fprintf(w, "%q: %q,\n", t.Begin.Name, t.End.Name)
		}
		fmt.Fprintf(w, "},\n")
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)\n")
	fmt.Fprintf(w, "defer cancel()\n\n")

	fmt.Fprintf(w, "mission := runtime.NewDslRuntime(%q, transitions, actions, events, conn)\n", g.ir.Start.Name)
	fmt.Fprintf(w, "if err := mission.Start(ctx); err != nil {\n")
	fmt.Fprintf(w, "fmt.Fprintf(os.Stderr, \"mission failed: %%v\\n\", err)\n")
	fmt.Fprintf(w, "os.Exit(1)\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "}\n")
}

// writeImports emits the import block for every package g's rendering
// touched, sorted by import path. Every import is aliased explicitly (even
// when the alias matches the package's own name) so generated source never
// depends on knowing a package's real name up front.
func (g *generator) writeImports(w io.Writer) {
	type imp struct{ alias, path string }
	imps := make([]imp, 0, len(g.pkgAlias))
	for path, alias := range g.pkgAlias {
		imps = append(imps, imp{alias, path})
	}
	sort.Slice(imps, func(i, j int) bool { return imps[i].path < imps[j].path })

	fmt.Fprintln(w, "import (")
	for _, i := range imps {
		fmt.Fprintf(w, "%s %q\n", i.alias, i.path)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
}
