// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.services.vehicle.data;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/vehicle/data;data";

import "steeleagle_protocol/v1/messages/result/result.proto";
import "steeleagle_protocol/v1/messages/telemetry/telemetry.proto";

/*
 * Used to get up-to-date results, telemetry, and video frames.
 *
 * This service is used to retrieve the most recent results, telemetry,
 * and video frames from the driver or other publisher plugins.
 */
service DataService {
  /*
   * Get the most recent produced result.
   *
   * Retrieves the most recent produced result from the named engine.
   */
  rpc GetResult (GetResultRequest)
    returns (GetResultResponse) {}
  /*
   * Get the most recent telemetry data.
   *
   * Retrieves the most recent telemetry data from the driver.
   */
  rpc GetTelemetry (GetTelemetryRequest)
    returns (GetTelemetryResponse) {}
  /*
   * Get the most recent video frame.
   *
   * Retrieves the most recent video frame from the driver.
   */
  rpc GetFrame (GetFrameRequest)
    returns (GetFrameResponse) {}

  /*
   * Stream individual video frames from the vehicle.
   *
   * Retrieves a stream of individual video frame from the vehicle.
   */
  rpc StreamVideoFrames (StreamVideoFramesRequest)
    returns (stream StreamVideoFramesResponse);

  /*
   * Stream telemetry from the vehicle.
   *
   * Streams up-to-date telemetry from the vehicle.
   */
  rpc StreamTelemetry (StreamTelemetryRequest)
    returns (stream StreamTelemetryResponse);
}

message GetResultRequest {
  string name = 1; // name of the result producer to pull from
}

message GetResultResponse {
  steeleagle_protocol.v1.messages.result.ComputeResult result = 1;
}

message GetTelemetryRequest {}

message GetTelemetryResponse {
  steeleagle_protocol.v1.messages.telemetry.Telemetry telemetry = 1; // most recent telemetry
}

message GetFrameRequest {}

message GetFrameResponse {
  steeleagle_protocol.v1.messages.telemetry.EncodedFrame frame = 1; // most recent frame
}

message StreamVideoFramesRequest {}

message StreamVideoFramesResponse {
  steeleagle_protocol.v1.messages.telemetry.EncodedFrame frame = 1; // encoded frame from the camera
}

message StreamTelemetryRequest {}

message StreamTelemetryResponse {
  steeleagle_protocol.v1.messages.telemetry.Telemetry telemetry = 1; // telemetry from the driver
}
