from typing import List
# API imports
from ...base import Action
from ....compiler.registry import register_action

# Type imports
from ...datatypes.common import Response
from ...datatypes import compute as params
from ...datatypes import common as common
from ... import COMPUTE

@register_action
class AddDatasinks(Action):
    """Add datasinks to consumer list.

    Takes a list of datasinks and adds them to the current consumer list.

    Attributes:
        datasinks (List[params.DatasinkInfo]): name of target datasinks
    """
    datasinks: List[params.DatasinkInfo]

    async def execute(self) -> Response:
        """Execute the AddDatasinks action.

        Returns:
            Response: response generated by the RPC call.
        """
        # TODO: convert the common response from grpc to dataypes.common.Response
        return await COMPUTE.add_datasinks(**self.model_dump())

@register_action
class SetDatasinks(Action):
    """Set the datasink consumer list.

    Takes a list of datasinks and replaces the current consumer list with them.

    Attributes:
        datasinks (List[params.DatasinkInfo]): name of target datasinks
    """
    datasinks: List[params.DatasinkInfo]

    async def execute(self) -> Response:
        """Execute the SetDatasinks action.

        Returns:
            Response: response generated by the RPC call.
        """
        return await COMPUTE.set_datasinks(**self.model_dump())

@register_action
class RemoveDatasinks(Action):
    """Remove datasinks from consumer list.

    Takes a list of datasinks and removes them from the current consumer list.

    Attributes:
        datasinks (List[params.DatasinkInfo]): name of target datasinks
    """
    datasinks: List[params.DatasinkInfo]

    async def execute(self) -> Response:
        """Execute the RemoveDatasinks action.

        Returns:
            Response: response generated by the RPC call.
        """
        return await COMPUTE.remove_datasinks(**self.model_dump())
