# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from steeleagle_protocol.v1.services.driver import gimbal_pb2 as steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2


class GimbalServiceStub:
    """
    Used for device gimbal control.

    This services provides a setpoint gimbal interface for the driver. Each
    command creates a target setpoint for the specified gimbal, which will then
    cause the device to actuate toward the setpoint until command completion.
    Each command will:
    1. Set the `gimbal_setpoint` field in the vehicle telemetry for `gimbal_id`
    2. Return the `gimbal_setpoint` field in the response
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetGimbalPoseAngleTarget = channel.unary_unary(
                '/steeleagle_protocol.v1.services.driver.GimbalService/SetGimbalPoseAngleTarget',
                request_serializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetRequest.SerializeToString,
                response_deserializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetResponse.FromString,
                _registered_method=True)
        self.SetGimbalPoseVelocityTarget = channel.unary_unary(
                '/steeleagle_protocol.v1.services.driver.GimbalService/SetGimbalPoseVelocityTarget',
                request_serializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetRequest.SerializeToString,
                response_deserializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetResponse.FromString,
                _registered_method=True)


class GimbalServiceServicer:
    """
    Used for device gimbal control.

    This services provides a setpoint gimbal interface for the driver. Each
    command creates a target setpoint for the specified gimbal, which will then
    cause the device to actuate toward the setpoint until command completion.
    Each command will:
    1. Set the `gimbal_setpoint` field in the vehicle telemetry for `gimbal_id`
    2. Return the `gimbal_setpoint` field in the response
    """

    def SetGimbalPoseAngleTarget(self, request, context):
        """
        Order the device to set the pose of a gimbal.

        The device will interpret the new pose angles according to `frame`
        as follows:
        - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
        - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)

        Populates the `gimbal_setpoints` value of `gimbal_id` with a `Pose` setpoint.
        Returns this as `gimbal_setpoint`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGimbalPoseVelocityTarget(self, request, context):
        """
        Order the device to set the pose of a gimbal.

        The device will interpret the new pose angles according to `frame`
        as follows:
        - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
        - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)

        Populates the `gimbal_setpoints` value of `gimbal_id` with a `PoseVelocity` setpoint.
        Returns this as `gimbal_setpoint`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GimbalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetGimbalPoseAngleTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGimbalPoseAngleTarget,
                    request_deserializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetRequest.FromString,
                    response_serializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetResponse.SerializeToString,
            ),
            'SetGimbalPoseVelocityTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGimbalPoseVelocityTarget,
                    request_deserializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetRequest.FromString,
                    response_serializer=steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'steeleagle_protocol.v1.services.driver.GimbalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('steeleagle_protocol.v1.services.driver.GimbalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GimbalService:
    """
    Used for device gimbal control.

    This services provides a setpoint gimbal interface for the driver. Each
    command creates a target setpoint for the specified gimbal, which will then
    cause the device to actuate toward the setpoint until command completion.
    Each command will:
    1. Set the `gimbal_setpoint` field in the vehicle telemetry for `gimbal_id`
    2. Return the `gimbal_setpoint` field in the response
    """

    @staticmethod
    def SetGimbalPoseAngleTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steeleagle_protocol.v1.services.driver.GimbalService/SetGimbalPoseAngleTarget',
            steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetRequest.SerializeToString,
            steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseAngleTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGimbalPoseVelocityTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/steeleagle_protocol.v1.services.driver.GimbalService/SetGimbalPoseVelocityTarget',
            steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetRequest.SerializeToString,
            steeleagle__protocol_dot_v1_dot_services_dot_driver_dot_gimbal__pb2.SetGimbalPoseVelocityTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
