# SPDX-FileCopyrightText: 2026 Carnegie Mellon University - Satyalab
#
# SPDX-License-Identifier: GPL-2.0-only

[dev]
#localhost ansible_connection=local
fermi ansible_host=fermi ansible_user=root
[dev:vars]
dev_install_docker=false
dev_install_nvidia_container_toolkit=false
dev_apt_packages=['git','curl']
