# SPDX-FileCopyrightText: 2026 Carnegie Mellon University - Satyalab
#
# SPDX-License-Identifier: GPL-2.0-only

[dev]
localhost ansible_connection=local

[dev:vars]
dev_install_docker=true
dev_install_nvidia_container_toolkit=false
