// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.services.swarm;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/swarm;swarm";

import "steeleagle_protocol/v1/common/common.proto";
import "steeleagle_protocol/v1/services/driver/control.proto";
import "steeleagle_protocol/v1/services/mission/mission.proto";

/*
 * Used for swarm-level control over multiple vehicles.
 *
 * This service is hosted by the swarm controller module and represents the
 * teleoperation interface for groups of vehicles. Most methods called here
 * will result in actuation of targeted vehicles (be careful!). Each method
 * will return a stream of result objects. Each result object contains the
 * associated vehicle name and a copy of its response, response code, and
 * response string if applicable. Even if one or more vehicles fails its call,
 * the overall call will _still succeed_. To check for errors, each response
 * should be inspected manually for failures.
 */
service SwarmService {
  /*
   * Order multiple vehicles to take off.
   *
   * Causes vehicles to take off to a specified take off altitude.
   * Implicitly arms the vehicles.
   */
  rpc SwarmTakeOff (SwarmTakeOffRequest)
	returns (stream SwarmTakeOffResponse) {}
  /*
   * Order multiple vehicle to land.
   *
   * Causes vehicles to land at its current location. Implicitly
   * disarms the vehicles.
   */
  rpc SwarmLand (SwarmLandRequest)
	returns (stream SwarmLandResponse) {}
  /*
   * Order multiple vehicle to hold/loiter.
   *
   * Causes vehicles to hold at their current locations and to
   * cancel any ongoing movement commands (`SwarmReturnToHome` e.g.).
   */
  rpc SwarmHold (SwarmHoldRequest)
	returns (stream SwarmHoldResponse) {}
  /*
   * Orders an emergency shutdown of multiple vehicles.
   *
   * Causes vehicles to immediately turn off their motors. _This will
   * result in the vehicles going into freefall, only for emergencies!_
   */
  rpc SwarmKill (SwarmKillRequest)
	returns (stream SwarmKillResponse) {}
  /*
   * Order multiple vehicles to return to their home positions.
   *
   * Causes vehicles to return to their home positions. Vehicles with no
   * home position set will return to their start position (defaults to
   * their takeoff position). Vehicles with home positions set will return
   * there instead. If `return_altitude` is set, the vehicle will ascend
   * to that altitude before transit.
   *
   * Each vehicle will interpret `end_behavior` as follows:
   * - `HOVER` -> hover at `final_altitude` above home position
   * - `LAND` -> land at home position
   */
  rpc SwarmReturnToHome (SwarmReturnToHomeRequest)
	returns (stream SwarmReturnToHomeResponse) {}
  /*
   * Order multiple vehicles to accelerate to a velocity.
   *
   * Causes vehicles to accelerate until they reach a provided velocity. Each
   * vehicle will interpret the input velocity according to `frame` as follows:
   * - `BODY` -> (`x_vel`, `y_vel`, `z_vel`) = (forward velocity, right velocity, up velocity)
   * - `NEU` -> (`x_vel`, `y_vel`, `z_vel`) = (north velocity, east velocity, up velocity)
   */
  rpc SwarmSetVelocityTarget (SwarmSetVelocityTargetRequest)
	returns (stream SwarmSetVelocityTargetResponse) {}
  /*
   * Order multiple vehicles to set the angle of a gimbal.
   *
   * Causes vehicles to actuate a gimbal to a new pose. Each vehicle
   * will interpret the new pose type from `pose_mode` as follows:
   * - `ABSOLUTE` -> absolute angle
   * - `RELATIVE` -> angle relative to current position
   *
   * Each vehicle will interpret the new pose angles according to `frame`
   * as follows:
   * - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
   * - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
   */
  rpc SwarmSetGimbalAngleTarget (SwarmSetGimbalAngleTargetRequest)
	returns (stream SwarmSetGimbalAngleTargetResponse) {}
  /*
   * Order multiple vehicles to start a mission.
   *
   * Causes vehicles to start their uploaded mission. This will enable autonomous
   * control mode, which can be interrupted by sending a `SwarmStopMission` or
   * `SwarmHold`.
   */
  rpc SwarmStartMission (SwarmStartMissionRequest)
    returns (stream SwarmStartMissionResponse) {}
  /*
   * Upload a mission to multiple vehicles.
   *
   * Uploads a mission to targeted vehicles. Can be started by sending a subsequent
   * `SwarmStartMission` command.
   */
  rpc SwarmUploadMission (SwarmUploadMissionRequest)
    returns (stream SwarmUploadMissionResponse) {}
  /*
   * Order multiple vehicles to stop a mission.
   *
   * Causes vehicles to stop their running mission. This will enable manual
   * control mode.
   */
  rpc SwarmStopMission (SwarmStopMissionRequest)
    returns (stream SwarmStopMissionResponse) {}
}

message SwarmTakeOffRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.TakeOffRequest request = 2; // proxied request object
}

message SwarmTakeOffResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.TakeOffResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmLandRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.LandRequest request = 2; // proxied request object
}

message SwarmLandResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.LandResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmHoldRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.HoldRequest request = 2; // proxied request object
}

message SwarmHoldResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.HoldResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmKillRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.KillRequest request = 2; // proxied request object
}

message SwarmKillResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.KillResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmReturnToHomeRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.ReturnToHomeRequest request = 2; // proxied request object
}

message SwarmReturnToHomeResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.ReturnToHomeResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmSetVelocityTargetRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.SetVelocityTargetRequest request = 2; // proxied request object
}

message SwarmSetVelocityTargetResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.SetVelocityTargetResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmSetGimbalAngleTargetRequest{
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.driver.SetGimbalAngleTargetRequest request = 2; // proxied request object
}

message SwarmSetGimbalAngleTargetResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.driver.SetGimbalAngleTargetResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmUploadMissionRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.mission.UploadMissionRequest request = 2; // proxied request object
}

message SwarmUploadMissionResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.mission.UploadMissionResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmStartMissionRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.mission.StartMissionRequest request = 2; // proxied request object
}

message SwarmStartMissionResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.mission.StartMissionResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}

message SwarmStopMissionRequest {
  repeated string vehicles = 1; // target vehicles
  steeleagle_protocol.v1.services.mission.StopMissionRequest request = 2; // proxied request object
}

message SwarmStopMissionResponse {
  string vehicle = 1; // ID of vehicle
  steeleagle_protocol.v1.services.mission.StopMissionResponse response = 2; // proxied response object
  uint32 code = 3; // gRPC status code
  string details = 4; // error details, if applicable
}
