// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response types for RPC functions.
//
// Values 0-2 (`OK`, `IN_PROGRESS`, `COMPLETED`) are specific to the SteelEagle protocol.
// They determine what phase an RPC call is in:
// - `OK` -> ack
// - `IN_PROGRESS` -> in progress
// - `COMPLETED` -> completed
//
// These intermediate phases are generally not exposed to user-facing code and are only used
// for streaming methods. In contrast to normal gRPC procedure, a call is only considered complete
// on a response of `COMPLETED` instead of `OK`. If an error occurs, SteelEagle defers to gRPC error
// codes, 3-18. More details on these codes can be found [here](https://grpc.github.io/grpc/core/md_doc_statuscodes.html).
// Note that the value of these codes is offset by 2 from their original form (e.g. `CANCELLED` = 3 vs = 1).
// Therefore, for error codes, the transformation from gRPC to SteelEagle response code is to add
// 2 to the code. The only codes that differ from their gRPC meaning are codes 9 and 18.
type ResponseStatus int32

const (
	ResponseStatus_OK                  ResponseStatus = 0  // command acknowledged
	ResponseStatus_IN_PROGRESS         ResponseStatus = 1  // command in progress
	ResponseStatus_COMPLETED           ResponseStatus = 2  // command finished without error
	ResponseStatus_CANCELLED           ResponseStatus = 3  // the operation was cancelled, typically by the caller
	ResponseStatus_UNKNOWN             ResponseStatus = 4  // unknown error
	ResponseStatus_INVALID_ARGUMENT    ResponseStatus = 5  // the client specified an invalid argument
	ResponseStatus_DEADLINE_EXCEEDED   ResponseStatus = 6  // the deadline expired before the operation could complete
	ResponseStatus_NOT_FOUND           ResponseStatus = 7  // some requested entity was not found
	ResponseStatus_ALREADY_EXISTS      ResponseStatus = 8  // an entity the client attempted to create already exists
	ResponseStatus_PERMISSION_DENIED   ResponseStatus = 9  // the provided identity is not permitted to execute this operation by the current law (unique to SteelEagle)
	ResponseStatus_RESOURCE_EXHAUSTED  ResponseStatus = 10 // some resource has been exhausted
	ResponseStatus_FAILED_PRECONDITION ResponseStatus = 11 // the operation was rejected because the system is not in a state required for the operation's execution
	ResponseStatus_ABORTED             ResponseStatus = 12 // the operation was aborted, typically due to a concurrency issue such as a sequencer check failure or transaction abort
	ResponseStatus_OUT_OF_RANGE        ResponseStatus = 13 // the operation was attempted past the valid range
	ResponseStatus_UNIMPLEMENTED       ResponseStatus = 14 // the operation is not implemented/supported by the service
	ResponseStatus_INTERNAL            ResponseStatus = 15 // an internal error occurred while executing the operation
	ResponseStatus_UNAVAILABLE         ResponseStatus = 16 // the service is currently unavailable
	ResponseStatus_DATA_LOSS           ResponseStatus = 17 // unrecoverable data loss or corruption
	ResponseStatus_UNAUTHENTICATED     ResponseStatus = 18 // the client failed to provide an identity (unique to SteelEagle)
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0:  "OK",
		1:  "IN_PROGRESS",
		2:  "COMPLETED",
		3:  "CANCELLED",
		4:  "UNKNOWN",
		5:  "INVALID_ARGUMENT",
		6:  "DEADLINE_EXCEEDED",
		7:  "NOT_FOUND",
		8:  "ALREADY_EXISTS",
		9:  "PERMISSION_DENIED",
		10: "RESOURCE_EXHAUSTED",
		11: "FAILED_PRECONDITION",
		12: "ABORTED",
		13: "OUT_OF_RANGE",
		14: "UNIMPLEMENTED",
		15: "INTERNAL",
		16: "UNAVAILABLE",
		17: "DATA_LOSS",
		18: "UNAUTHENTICATED",
	}
	ResponseStatus_value = map[string]int32{
		"OK":                  0,
		"IN_PROGRESS":         1,
		"COMPLETED":           2,
		"CANCELLED":           3,
		"UNKNOWN":             4,
		"INVALID_ARGUMENT":    5,
		"DEADLINE_EXCEEDED":   6,
		"NOT_FOUND":           7,
		"ALREADY_EXISTS":      8,
		"PERMISSION_DENIED":   9,
		"RESOURCE_EXHAUSTED":  10,
		"FAILED_PRECONDITION": 11,
		"ABORTED":             12,
		"OUT_OF_RANGE":        13,
		"UNIMPLEMENTED":       14,
		"INTERNAL":            15,
		"UNAVAILABLE":         16,
		"DATA_LOSS":           17,
		"UNAUTHENTICATED":     18,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Request object for additional request info.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // request timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Global response message returned by all core services.
type Response struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=steeleagle.protocol.common.ResponseStatus" json:"status,omitempty"` // response status
	ResponseString *string                `protobuf:"bytes,2,opt,name=response_string,json=responseString,proto3,oneof" json:"response_string,omitempty"`     // detailed message on reason for response
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                           // response timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_OK
}

func (x *Response) GetResponseString() string {
	if x != nil && x.ResponseString != nil {
		return *x.ResponseString
	}
	return ""
}

func (x *Response) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Angular offsets or poses in 3 dimensions.
type Pose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pitch         *float64               `protobuf:"fixed64,1,opt,name=pitch,proto3,oneof" json:"pitch,omitempty"` // pitch [degrees]
	Roll          *float64               `protobuf:"fixed64,2,opt,name=roll,proto3,oneof" json:"roll,omitempty"`   // roll [degrees]
	Yaw           *float64               `protobuf:"fixed64,3,opt,name=yaw,proto3,oneof" json:"yaw,omitempty"`     // yaw [degrees]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pose) Reset() {
	*x = Pose{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Pose) GetPitch() float64 {
	if x != nil && x.Pitch != nil {
		return *x.Pitch
	}
	return 0
}

func (x *Pose) GetRoll() float64 {
	if x != nil && x.Roll != nil {
		return *x.Roll
	}
	return 0
}

func (x *Pose) GetYaw() float64 {
	if x != nil && x.Yaw != nil {
		return *x.Yaw
	}
	return 0
}

// Representation of velocity in 3-dimensions.
type Velocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XVel          *float64               `protobuf:"fixed64,1,opt,name=x_vel,json=xVel,proto3,oneof" json:"x_vel,omitempty"`                   // forward/north velocity [meters/s]
	YVel          *float64               `protobuf:"fixed64,2,opt,name=y_vel,json=yVel,proto3,oneof" json:"y_vel,omitempty"`                   // right/east velocity [meters/s]
	ZVel          *float64               `protobuf:"fixed64,3,opt,name=z_vel,json=zVel,proto3,oneof" json:"z_vel,omitempty"`                   // up velocity [meters/s]
	AngularVel    *float64               `protobuf:"fixed64,4,opt,name=angular_vel,json=angularVel,proto3,oneof" json:"angular_vel,omitempty"` // angular velocity [degrees/s]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Velocity) Reset() {
	*x = Velocity{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Velocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Velocity) ProtoMessage() {}

func (x *Velocity) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Velocity.ProtoReflect.Descriptor instead.
func (*Velocity) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Velocity) GetXVel() float64 {
	if x != nil && x.XVel != nil {
		return *x.XVel
	}
	return 0
}

func (x *Velocity) GetYVel() float64 {
	if x != nil && x.YVel != nil {
		return *x.YVel
	}
	return 0
}

func (x *Velocity) GetZVel() float64 {
	if x != nil && x.ZVel != nil {
		return *x.ZVel
	}
	return 0
}

func (x *Velocity) GetAngularVel() float64 {
	if x != nil && x.AngularVel != nil {
		return *x.AngularVel
	}
	return 0
}

// Position offset relative to home or current location.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,1,opt,name=x,proto3,oneof" json:"x,omitempty"`         // forward/north offset [meters]
	Y             *float64               `protobuf:"fixed64,2,opt,name=y,proto3,oneof" json:"y,omitempty"`         // right/east offset [meters]
	Z             *float64               `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`         // up offset [meters]
	Angle         *float64               `protobuf:"fixed64,4,opt,name=angle,proto3,oneof" json:"angle,omitempty"` // angular offset [degrees]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Position) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Position) GetAngle() float64 {
	if x != nil && x.Angle != nil {
		return *x.Angle
	}
	return 0
}

// Location in global coordinates.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float64               `protobuf:"fixed64,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`   // global latitude [degrees]
	Longitude     *float64               `protobuf:"fixed64,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"` // global longitude [degrees]
	Altitude      *float64               `protobuf:"fixed64,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`   // altitude above MSL or takeoff [meters]
	Heading       *float64               `protobuf:"fixed64,4,opt,name=heading,proto3,oneof" json:"heading,omitempty"`     // global heading [degrees]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *Location) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Location) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *Location) GetHeading() float64 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x1asteeleagle.protocol.common\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\aRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xca\x01\n" +
	"\bResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.steeleagle.protocol.common.ResponseStatusR\x06status\x12,\n" +
	"\x0fresponse_string\x18\x02 \x01(\tH\x00R\x0eresponseString\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x12\n" +
	"\x10_response_string\"l\n" +
	"\x04Pose\x12\x19\n" +
	"\x05pitch\x18\x01 \x01(\x01H\x00R\x05pitch\x88\x01\x01\x12\x17\n" +
	"\x04roll\x18\x02 \x01(\x01H\x01R\x04roll\x88\x01\x01\x12\x15\n" +
	"\x03yaw\x18\x03 \x01(\x01H\x02R\x03yaw\x88\x01\x01B\b\n" +
	"\x06_pitchB\a\n" +
	"\x05_rollB\x06\n" +
	"\x04_yaw\"\xac\x01\n" +
	"\bVelocity\x12\x18\n" +
	"\x05x_vel\x18\x01 \x01(\x01H\x00R\x04xVel\x88\x01\x01\x12\x18\n" +
	"\x05y_vel\x18\x02 \x01(\x01H\x01R\x04yVel\x88\x01\x01\x12\x18\n" +
	"\x05z_vel\x18\x03 \x01(\x01H\x02R\x04zVel\x88\x01\x01\x12$\n" +
	"\vangular_vel\x18\x04 \x01(\x01H\x03R\n" +
	"angularVel\x88\x01\x01B\b\n" +
	"\x06_x_velB\b\n" +
	"\x06_y_velB\b\n" +
	"\x06_z_velB\x0e\n" +
	"\f_angular_vel\"z\n" +
	"\bPosition\x12\x11\n" +
	"\x01x\x18\x01 \x01(\x01H\x00R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x02 \x01(\x01H\x01R\x01y\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x01H\x02R\x01z\x88\x01\x01\x12\x19\n" +
	"\x05angle\x18\x04 \x01(\x01H\x03R\x05angle\x88\x01\x01B\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\x04\n" +
	"\x02_zB\b\n" +
	"\x06_angle\"\xc2\x01\n" +
	"\bLocation\x12\x1f\n" +
	"\blatitude\x18\x01 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x02 \x01(\x01H\x01R\tlongitude\x88\x01\x01\x12\x1f\n" +
	"\baltitude\x18\x03 \x01(\x01H\x02R\baltitude\x88\x01\x01\x12\x1d\n" +
	"\aheading\x18\x04 \x01(\x01H\x03R\aheading\x88\x01\x01B\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\v\n" +
	"\t_altitudeB\n" +
	"\n" +
	"\b_heading*\xe1\x02\n" +
	"\x0eResponseStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x05\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x06\x12\r\n" +
	"\tNOT_FOUND\x10\a\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\b\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\t\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\n" +
	"\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\v\x12\v\n" +
	"\aABORTED\x10\f\x12\x10\n" +
	"\fOUT_OF_RANGE\x10\r\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\x0e\x12\f\n" +
	"\bINTERNAL\x10\x0f\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x10\x12\r\n" +
	"\tDATA_LOSS\x10\x11\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x12B\xe9\x01\n" +
	"\x1ecom.steeleagle.protocol.commonB\vCommonProtoP\x01Z0github.com/cmusatyalab/steeleagle/runtime/protos\xa2\x02\x03SPC\xaa\x02\x1aSteeleagle.Protocol.Common\xca\x02\x1aSteeleagle\\Protocol\\Common\xe2\x02&Steeleagle\\Protocol\\Common\\GPBMetadata\xea\x02\x1cSteeleagle::Protocol::Commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_goTypes = []any{
	(ResponseStatus)(0),           // 0: steeleagle.protocol.common.ResponseStatus
	(*Request)(nil),               // 1: steeleagle.protocol.common.Request
	(*Response)(nil),              // 2: steeleagle.protocol.common.Response
	(*Pose)(nil),                  // 3: steeleagle.protocol.common.Pose
	(*Velocity)(nil),              // 4: steeleagle.protocol.common.Velocity
	(*Position)(nil),              // 5: steeleagle.protocol.common.Position
	(*Location)(nil),              // 6: steeleagle.protocol.common.Location
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	7, // 0: steeleagle.protocol.common.Request.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: steeleagle.protocol.common.Response.status:type_name -> steeleagle.protocol.common.ResponseStatus
	7, // 2: steeleagle.protocol.common.Response.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_proto_msgTypes[4].OneofWrappers = []any{}
	file_common_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
