{
 "title": "Dashboard 1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Engine Throughput (jobs/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_engine_inputs_processed_total[$window])",
     "legendFormat": "{{engine_id}}"
    }
   ]
  },
  {
   "title": "Input Arrival Rate (frames/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_producer_inputs_received_total[$window]) > 0",
     "legendFormat": "{{producer_id}}"
    }
   ]
  },
  {
   "title": "Engine Service Rate (jobs/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 /\n(\n    sum(rate(gabriel_engine_processing_latency_seconds_sum[$window])) by (engine_id)\n    /\n    sum(rate(gabriel_engine_processing_latency_seconds_count[$window])) by (engine_id)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile Processing Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\n(\n  histogram_quantile(\n    0.99,\n    sum(rate(gabriel_engine_processing_latency_seconds_bucket[$window])) by (le, engine_id)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Processing Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\n(\n    sum(rate(gabriel_engine_processing_latency_seconds_sum[$window])) by (engine_id)\n    /\n    sum(rate(gabriel_engine_processing_latency_seconds_count[$window])) by (engine_id)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Queue Lengths",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gabriel_producer_queue_length > 0",
     "legendFormat": "{{producer_id}}"
    }
   ]
  },
  {
   "title": "Engine Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_engine_processing_latency_seconds_sum[$window])",
     "legendFormat": "{{engine_id}}"
    }
   ]
  }
 ]
}