{
 "title": "Dashboard 1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Engine Throughput (jobs/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_engine_inputs_processed_total[$window])",
     "legendFormat": "{{engine_id}}"
    }
   ]
  },
  {
   "title": "Input Arrival Rate (frames/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_client_inputs_received_total[$window]) > 0",
     "legendFormat": "{{source_id}}"
    }
   ]
  },
  {
   "title": "Engine Service Rate (jobs/sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 /\n(\n    sum(rate(gabriel_engine_processing_latency_seconds_sum[$window])) by (engine_id)\n    /\n    sum(rate(gabriel_engine_processing_latency_seconds_count[$window])) by (engine_id)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile Processing Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\n(\n  histogram_quantile(\n    0.99,\n    sum(rate(gabriel_engine_processing_latency_seconds_bucket[$window])) by (le, engine_id)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Processing Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\n(\n    sum(rate(gabriel_engine_processing_latency_seconds_sum[$window])) by (engine_id)\n    /\n    sum(rate(gabriel_engine_processing_latency_seconds_count[$window])) by (engine_id)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Queue Lengths",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gabriel_source_queue_length > 0",
     "legendFormat": "{{source_id}}"
    }
   ]
  },
  {
   "title": "Engine Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gabriel_engine_processing_latency_seconds_sum[$window])",
     "legendFormat": "{{engine_id}}"
    }
   ]
  },
  {
   "title": "Interarrival Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Interarrival Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(input_inter_arrival_time_seconds_sum[$window])) by (source_id)\n/\nsum(rate(input_inter_arrival_time_seconds_count[$window])) by (source_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95th Percentile Interarrival Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(input_inter_arrival_time_seconds_bucket[$window])) by (le, source_id))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Median Interarrival time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(engine_processing_latency_seconds_bucket[$window])) by (le, source_id))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Engine Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Engine Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(engine_processing_latency_seconds_sum[$window])) by (engine)\n/\nsum(rate(engine_processing_latency_seconds_count[$window])) by (engine)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95th Percentile Engine Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(engine_processing_latency_seconds_bucket[$window])) by (le, engine))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Engine Latency Median",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(engine_processing_latency_seconds_bucket[$window])) by (le, engine))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}