FROM ubuntu:22.04

LABEL org.opencontainers.image.vendor="CMU Satyalab" \
      org.opencontainers.image.authors=satya-group@lists.andrew.cmu.edu

ARG DEBIAN_FRONTEND=noninteractive

# Install build and runtime dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    libgtk-3-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1 \
    python3 \
    python3-pip \
    vim \
    wget \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install Python dependencies
RUN python3 -m pip install --no-cache-dir \
    'opencv-python<5' \
    numpy \
    redis \
    gabriel-server>=5.0.0 \
    protobuf>5.26.1 \
    pymap3d \
    pyzmq \
    zmq \
    pyyaml \
    gabriel-client \
    gabriel-protocol \
    steeleagle-protocol


# Copy project files
RUN mkdir steeleagle
COPY *.py steeleagle/
WORKDIR steeleagle

EXPOSE 5555 9099

# The actual command to run will be specified in docker-compose or at runtime
