#####################################################################
# NOTE: THIS FILE IS AUTOGENERATED BY GENERATE_TYPES.PY. DO NOT EDIT!
#####################################################################
from api.base import Datatype
from dataclasses import dataclass
from enum import Enum
from api.messages.google.timestamp import Timestamp
from dsl.compiler.registry import register_data 


@register_data
@dataclass
class Pose(Datatype):
    '''Angular offsets or poses in 3 dimensions [degrees]'''
    pitch: float

    roll: float

    yaw: float

    @staticmethod
    def get_type_url():
        return 'type.googleapis.com/steeleagle.protocol.common.Pose'

@register_data
@dataclass
class Velocity(Datatype):
    '''Representation of the speed in 3-dimensions [meters/s]'''
    x_vel: float
    '''Forward/north velocity'''
    y_vel: float
    '''Right/east velocity'''
    z_vel: float
    '''Up velocity'''
    angular_vel: float
    '''Angular velocity [degrees/s]'''

    @staticmethod
    def get_type_url():
        return 'type.googleapis.com/steeleagle.protocol.common.Velocity'

@register_data
@dataclass
class Position(Datatype):
    '''Position offset relative to home or current location [meters]'''
    x: float
    '''Forward/north offset'''
    y: float
    '''Right/east offset'''
    z: float
    '''Up offset'''
    angle: float
    '''Angular offset [degrees]'''

    @staticmethod
    def get_type_url():
        return 'type.googleapis.com/steeleagle.protocol.common.Position'

@register_data
@dataclass
class Location(Datatype):
    '''Location in global coordinates [latitude, longitude]'''
    latitude: float

    longitude: float

    altitude: float
    '''Above MSL [meters]'''
    heading: float

    @staticmethod
    def get_type_url():
        return 'type.googleapis.com/steeleagle.protocol.common.Location'

