// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steeleagle_protocol/v1/services/driver/control.proto

package driver

import (
	v1 "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnToHomeEndBehavior int32

const (
	ReturnToHomeEndBehavior_RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED ReturnToHomeEndBehavior = 0 // defaults to `HOVER`
	ReturnToHomeEndBehavior_RETURN_TO_HOME_END_BEHAVIOR_HOVER       ReturnToHomeEndBehavior = 1 // hover upon return to home
	ReturnToHomeEndBehavior_RETURN_TO_HOME_END_BEHAVIOR_LAND        ReturnToHomeEndBehavior = 2 // land upon return to home
)

// Enum value maps for ReturnToHomeEndBehavior.
var (
	ReturnToHomeEndBehavior_name = map[int32]string{
		0: "RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED",
		1: "RETURN_TO_HOME_END_BEHAVIOR_HOVER",
		2: "RETURN_TO_HOME_END_BEHAVIOR_LAND",
	}
	ReturnToHomeEndBehavior_value = map[string]int32{
		"RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED": 0,
		"RETURN_TO_HOME_END_BEHAVIOR_HOVER":       1,
		"RETURN_TO_HOME_END_BEHAVIOR_LAND":        2,
	}
)

func (x ReturnToHomeEndBehavior) Enum() *ReturnToHomeEndBehavior {
	p := new(ReturnToHomeEndBehavior)
	*p = x
	return p
}

func (x ReturnToHomeEndBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnToHomeEndBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[0].Descriptor()
}

func (ReturnToHomeEndBehavior) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[0]
}

func (x ReturnToHomeEndBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnToHomeEndBehavior.Descriptor instead.
func (ReturnToHomeEndBehavior) EnumDescriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{0}
}

// Altitude mode switch.
type AltitudeMode int32

const (
	AltitudeMode_ALTITUDE_MODE_UNSPECIFIED AltitudeMode = 0 // defaults to `ABSOLUTE`
	AltitudeMode_ALTITUDE_MODE_ABSOLUTE    AltitudeMode = 1 // meters above Mean Sea Level
	AltitudeMode_ALTITUDE_MODE_RELATIVE    AltitudeMode = 2 // meters above takeoff position
)

// Enum value maps for AltitudeMode.
var (
	AltitudeMode_name = map[int32]string{
		0: "ALTITUDE_MODE_UNSPECIFIED",
		1: "ALTITUDE_MODE_ABSOLUTE",
		2: "ALTITUDE_MODE_RELATIVE",
	}
	AltitudeMode_value = map[string]int32{
		"ALTITUDE_MODE_UNSPECIFIED": 0,
		"ALTITUDE_MODE_ABSOLUTE":    1,
		"ALTITUDE_MODE_RELATIVE":    2,
	}
)

func (x AltitudeMode) Enum() *AltitudeMode {
	p := new(AltitudeMode)
	*p = x
	return p
}

func (x AltitudeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AltitudeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[1].Descriptor()
}

func (AltitudeMode) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[1]
}

func (x AltitudeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AltitudeMode.Descriptor instead.
func (AltitudeMode) EnumDescriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{1}
}

// Heading mode switch.
type HeadingMode int32

const (
	HeadingMode_HEADING_MODE_UNSPECIFIED HeadingMode = 0 // defaults to `TO_TARGET`
	HeadingMode_HEADING_MODE_TO_TARGET   HeadingMode = 1 // orient towards the target location
	HeadingMode_HEADING_MODE_START       HeadingMode = 2 // orient towards the given heading
)

// Enum value maps for HeadingMode.
var (
	HeadingMode_name = map[int32]string{
		0: "HEADING_MODE_UNSPECIFIED",
		1: "HEADING_MODE_TO_TARGET",
		2: "HEADING_MODE_START",
	}
	HeadingMode_value = map[string]int32{
		"HEADING_MODE_UNSPECIFIED": 0,
		"HEADING_MODE_TO_TARGET":   1,
		"HEADING_MODE_START":       2,
	}
)

func (x HeadingMode) Enum() *HeadingMode {
	p := new(HeadingMode)
	*p = x
	return p
}

func (x HeadingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeadingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[2].Descriptor()
}

func (HeadingMode) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[2]
}

func (x HeadingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeadingMode.Descriptor instead.
func (HeadingMode) EnumDescriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{2}
}

// Reference frame mode switch.
type ReferenceFrame int32

const (
	ReferenceFrame_REFERENCE_FRAME_UNSPECIFIED ReferenceFrame = 0 // defaults to `BODY`
	ReferenceFrame_REFERENCE_FRAME_BODY        ReferenceFrame = 1 // vehicle reference frame
	ReferenceFrame_REFERENCE_FRAME_NEU         ReferenceFrame = 2 // NEU (North, East, Up) reference frame
)

// Enum value maps for ReferenceFrame.
var (
	ReferenceFrame_name = map[int32]string{
		0: "REFERENCE_FRAME_UNSPECIFIED",
		1: "REFERENCE_FRAME_BODY",
		2: "REFERENCE_FRAME_NEU",
	}
	ReferenceFrame_value = map[string]int32{
		"REFERENCE_FRAME_UNSPECIFIED": 0,
		"REFERENCE_FRAME_BODY":        1,
		"REFERENCE_FRAME_NEU":         2,
	}
)

func (x ReferenceFrame) Enum() *ReferenceFrame {
	p := new(ReferenceFrame)
	*p = x
	return p
}

func (x ReferenceFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[3].Descriptor()
}

func (ReferenceFrame) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[3]
}

func (x ReferenceFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceFrame.Descriptor instead.
func (ReferenceFrame) EnumDescriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{3}
}

// Pose mode switch.
type PoseMode int32

const (
	PoseMode_POSE_MODE_UNSPECIFIED PoseMode = 0 // defaults to `ANGLE`
	PoseMode_POSE_MODE_ANGLE       PoseMode = 1 // absolute angle
	PoseMode_POSE_MODE_OFFSET      PoseMode = 2 // offset from current
	PoseMode_POSE_MODE_VELOCITY    PoseMode = 3 // rotational velocities
)

// Enum value maps for PoseMode.
var (
	PoseMode_name = map[int32]string{
		0: "POSE_MODE_UNSPECIFIED",
		1: "POSE_MODE_ANGLE",
		2: "POSE_MODE_OFFSET",
		3: "POSE_MODE_VELOCITY",
	}
	PoseMode_value = map[string]int32{
		"POSE_MODE_UNSPECIFIED": 0,
		"POSE_MODE_ANGLE":       1,
		"POSE_MODE_OFFSET":      2,
		"POSE_MODE_VELOCITY":    3,
	}
)

func (x PoseMode) Enum() *PoseMode {
	p := new(PoseMode)
	*p = x
	return p
}

func (x PoseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[4].Descriptor()
}

func (PoseMode) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes[4]
}

func (x PoseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoseMode.Descriptor instead.
func (PoseMode) EnumDescriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{4}
}

type TakeOffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// take off height in relative altitude [meters]
	TakeOffAltitude float32 `protobuf:"fixed32,1,opt,name=take_off_altitude,json=takeOffAltitude,proto3" json:"take_off_altitude,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TakeOffRequest) Reset() {
	*x = TakeOffRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOffRequest) ProtoMessage() {}

func (x *TakeOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOffRequest.ProtoReflect.Descriptor instead.
func (*TakeOffRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{0}
}

func (x *TakeOffRequest) GetTakeOffAltitude() float32 {
	if x != nil {
		return x.TakeOffAltitude
	}
	return 0
}

type TakeOffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOffResponse) Reset() {
	*x = TakeOffResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOffResponse) ProtoMessage() {}

func (x *TakeOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOffResponse.ProtoReflect.Descriptor instead.
func (*TakeOffResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{1}
}

type LandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandRequest) Reset() {
	*x = LandRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandRequest) ProtoMessage() {}

func (x *LandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandRequest.ProtoReflect.Descriptor instead.
func (*LandRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{2}
}

type LandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandResponse) Reset() {
	*x = LandResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandResponse) ProtoMessage() {}

func (x *LandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandResponse.ProtoReflect.Descriptor instead.
func (*LandResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{3}
}

type HoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{4}
}

type HoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{5}
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{6}
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{7}
}

type SetHomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewHome       *v1.GlobalPosition     `protobuf:"bytes,1,opt,name=new_home,json=newHome,proto3" json:"new_home,omitempty"` // new home location
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHomeRequest) Reset() {
	*x = SetHomeRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHomeRequest) ProtoMessage() {}

func (x *SetHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHomeRequest.ProtoReflect.Descriptor instead.
func (*SetHomeRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{8}
}

func (x *SetHomeRequest) GetNewHome() *v1.GlobalPosition {
	if x != nil {
		return x.NewHome
	}
	return nil
}

type SetHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHomeResponse) Reset() {
	*x = SetHomeResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHomeResponse) ProtoMessage() {}

func (x *SetHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHomeResponse.ProtoReflect.Descriptor instead.
func (*SetHomeResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{9}
}

type ReturnToHomeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what the vehicle should do after returning home
	EndBehavior ReturnToHomeEndBehavior `protobuf:"varint,1,opt,name=end_behavior,json=endBehavior,proto3,enum=steeleagle_protocol.v1.services.driver.control.ReturnToHomeEndBehavior" json:"end_behavior,omitempty"`
	// altitude that the vehicle should move at while reurning home
	ReturnAltitude uint32 `protobuf:"varint,2,opt,name=return_altitude,json=returnAltitude,proto3" json:"return_altitude,omitempty"`
	// altitude that the vehicle should hover AGL (above ground level), for hover end behavior
	FinalAltitude uint32 `protobuf:"varint,3,opt,name=final_altitude,json=finalAltitude,proto3" json:"final_altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnToHomeRequest) Reset() {
	*x = ReturnToHomeRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnToHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnToHomeRequest) ProtoMessage() {}

func (x *ReturnToHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnToHomeRequest.ProtoReflect.Descriptor instead.
func (*ReturnToHomeRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{10}
}

func (x *ReturnToHomeRequest) GetEndBehavior() ReturnToHomeEndBehavior {
	if x != nil {
		return x.EndBehavior
	}
	return ReturnToHomeEndBehavior_RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED
}

func (x *ReturnToHomeRequest) GetReturnAltitude() uint32 {
	if x != nil {
		return x.ReturnAltitude
	}
	return 0
}

func (x *ReturnToHomeRequest) GetFinalAltitude() uint32 {
	if x != nil {
		return x.FinalAltitude
	}
	return 0
}

type ReturnToHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnToHomeResponse) Reset() {
	*x = ReturnToHomeResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnToHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnToHomeResponse) ProtoMessage() {}

func (x *ReturnToHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnToHomeResponse.ProtoReflect.Descriptor instead.
func (*ReturnToHomeResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{11}
}

type GoToGlobalPositionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Position *v1.GlobalPosition     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // target global position
	// determines how the vehicle will orient during transit (default: `TO_TARGET`)
	HeadingMode *HeadingMode `protobuf:"varint,2,opt,name=heading_mode,json=headingMode,proto3,enum=steeleagle_protocol.v1.services.driver.control.HeadingMode,oneof" json:"heading_mode,omitempty"`
	// determines how the vehicle will interpret altitude (default: `ABSOLUTE`)
	AltitudeMode *AltitudeMode `protobuf:"varint,3,opt,name=altitude_mode,json=altitudeMode,proto3,enum=steeleagle_protocol.v1.services.driver.control.AltitudeMode,oneof" json:"altitude_mode,omitempty"`
	// speed during transit
	Speed         *float32 `protobuf:"fixed32,4,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoToGlobalPositionRequest) Reset() {
	*x = GoToGlobalPositionRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoToGlobalPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoToGlobalPositionRequest) ProtoMessage() {}

func (x *GoToGlobalPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoToGlobalPositionRequest.ProtoReflect.Descriptor instead.
func (*GoToGlobalPositionRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{12}
}

func (x *GoToGlobalPositionRequest) GetPosition() *v1.GlobalPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GoToGlobalPositionRequest) GetHeadingMode() HeadingMode {
	if x != nil && x.HeadingMode != nil {
		return *x.HeadingMode
	}
	return HeadingMode_HEADING_MODE_UNSPECIFIED
}

func (x *GoToGlobalPositionRequest) GetAltitudeMode() AltitudeMode {
	if x != nil && x.AltitudeMode != nil {
		return *x.AltitudeMode
	}
	return AltitudeMode_ALTITUDE_MODE_UNSPECIFIED
}

func (x *GoToGlobalPositionRequest) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

type GoToGlobalPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoToGlobalPositionResponse) Reset() {
	*x = GoToGlobalPositionResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoToGlobalPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoToGlobalPositionResponse) ProtoMessage() {}

func (x *GoToGlobalPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoToGlobalPositionResponse.ProtoReflect.Descriptor instead.
func (*GoToGlobalPositionResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{13}
}

type GoToRelativePositionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target relative position
	Position *v1.RelativePosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// speed during transit
	Speed *float32 `protobuf:"fixed32,2,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	// frame of reference
	Frame         *ReferenceFrame `protobuf:"varint,3,opt,name=frame,proto3,enum=steeleagle_protocol.v1.services.driver.control.ReferenceFrame,oneof" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoToRelativePositionRequest) Reset() {
	*x = GoToRelativePositionRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoToRelativePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoToRelativePositionRequest) ProtoMessage() {}

func (x *GoToRelativePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoToRelativePositionRequest.ProtoReflect.Descriptor instead.
func (*GoToRelativePositionRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{14}
}

func (x *GoToRelativePositionRequest) GetPosition() *v1.RelativePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GoToRelativePositionRequest) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *GoToRelativePositionRequest) GetFrame() ReferenceFrame {
	if x != nil && x.Frame != nil {
		return *x.Frame
	}
	return ReferenceFrame_REFERENCE_FRAME_UNSPECIFIED
}

type GoToRelativePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoToRelativePositionResponse) Reset() {
	*x = GoToRelativePositionResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoToRelativePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoToRelativePositionResponse) ProtoMessage() {}

func (x *GoToRelativePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoToRelativePositionResponse.ProtoReflect.Descriptor instead.
func (*GoToRelativePositionResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{15}
}

type SetVelocityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target velocity
	Velocity *v1.Velocity `protobuf:"bytes,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	// frame of reference
	Frame         *ReferenceFrame `protobuf:"varint,2,opt,name=frame,proto3,enum=steeleagle_protocol.v1.services.driver.control.ReferenceFrame,oneof" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVelocityRequest) Reset() {
	*x = SetVelocityRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVelocityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVelocityRequest) ProtoMessage() {}

func (x *SetVelocityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVelocityRequest.ProtoReflect.Descriptor instead.
func (*SetVelocityRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{16}
}

func (x *SetVelocityRequest) GetVelocity() *v1.Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *SetVelocityRequest) GetFrame() ReferenceFrame {
	if x != nil && x.Frame != nil {
		return *x.Frame
	}
	return ReferenceFrame_REFERENCE_FRAME_UNSPECIFIED
}

type SetVelocityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVelocityResponse) Reset() {
	*x = SetVelocityResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVelocityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVelocityResponse) ProtoMessage() {}

func (x *SetVelocityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVelocityResponse.ProtoReflect.Descriptor instead.
func (*SetVelocityResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{17}
}

type SetGimbalPoseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GimbalId      uint32                 `protobuf:"varint,1,opt,name=gimbal_id,json=gimbalId,proto3" json:"gimbal_id,omitempty"`                                                                    // ID of the target gimbal
	Pose          *v1.Pose               `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`                                                                                             // target pose
	PoseMode      *PoseMode              `protobuf:"varint,3,opt,name=pose_mode,json=poseMode,proto3,enum=steeleagle_protocol.v1.services.driver.control.PoseMode,oneof" json:"pose_mode,omitempty"` // specifies how to interpret the target pose
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGimbalPoseRequest) Reset() {
	*x = SetGimbalPoseRequest{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGimbalPoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGimbalPoseRequest) ProtoMessage() {}

func (x *SetGimbalPoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGimbalPoseRequest.ProtoReflect.Descriptor instead.
func (*SetGimbalPoseRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{18}
}

func (x *SetGimbalPoseRequest) GetGimbalId() uint32 {
	if x != nil {
		return x.GimbalId
	}
	return 0
}

func (x *SetGimbalPoseRequest) GetPose() *v1.Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *SetGimbalPoseRequest) GetPoseMode() PoseMode {
	if x != nil && x.PoseMode != nil {
		return *x.PoseMode
	}
	return PoseMode_POSE_MODE_UNSPECIFIED
}

type SetGimbalPoseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGimbalPoseResponse) Reset() {
	*x = SetGimbalPoseResponse{}
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGimbalPoseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGimbalPoseResponse) ProtoMessage() {}

func (x *SetGimbalPoseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGimbalPoseResponse.ProtoReflect.Descriptor instead.
func (*SetGimbalPoseResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP(), []int{19}
}

var File_steeleagle_protocol_v1_services_driver_control_proto protoreflect.FileDescriptor

const file_steeleagle_protocol_v1_services_driver_control_proto_rawDesc = "" +
	"\n" +
	"4steeleagle_protocol/v1/services/driver/control.proto\x12.steeleagle_protocol.v1.services.driver.control\x1a#steeleagle_protocol/v1/common.proto\"<\n" +
	"\x0eTakeOffRequest\x12*\n" +
	"\x11take_off_altitude\x18\x01 \x01(\x02R\x0ftakeOffAltitude\"\x11\n" +
	"\x0fTakeOffResponse\"\r\n" +
	"\vLandRequest\"\x0e\n" +
	"\fLandResponse\"\r\n" +
	"\vHoldRequest\"\x0e\n" +
	"\fHoldResponse\"\r\n" +
	"\vKillRequest\"\x0e\n" +
	"\fKillResponse\"S\n" +
	"\x0eSetHomeRequest\x12A\n" +
	"\bnew_home\x18\x01 \x01(\v2&.steeleagle_protocol.v1.GlobalPositionR\anewHome\"\x11\n" +
	"\x0fSetHomeResponse\"\xd1\x01\n" +
	"\x13ReturnToHomeRequest\x12j\n" +
	"\fend_behavior\x18\x01 \x01(\x0e2G.steeleagle_protocol.v1.services.driver.control.ReturnToHomeEndBehaviorR\vendBehavior\x12'\n" +
	"\x0freturn_altitude\x18\x02 \x01(\rR\x0ereturnAltitude\x12%\n" +
	"\x0efinal_altitude\x18\x03 \x01(\rR\rfinalAltitude\"\x16\n" +
	"\x14ReturnToHomeResponse\"\xf4\x02\n" +
	"\x19GoToGlobalPositionRequest\x12B\n" +
	"\bposition\x18\x01 \x01(\v2&.steeleagle_protocol.v1.GlobalPositionR\bposition\x12c\n" +
	"\fheading_mode\x18\x02 \x01(\x0e2;.steeleagle_protocol.v1.services.driver.control.HeadingModeH\x00R\vheadingMode\x88\x01\x01\x12f\n" +
	"\raltitude_mode\x18\x03 \x01(\x0e2<.steeleagle_protocol.v1.services.driver.control.AltitudeModeH\x01R\faltitudeMode\x88\x01\x01\x12\x19\n" +
	"\x05speed\x18\x04 \x01(\x02H\x02R\x05speed\x88\x01\x01B\x0f\n" +
	"\r_heading_modeB\x10\n" +
	"\x0e_altitude_modeB\b\n" +
	"\x06_speed\"\x1c\n" +
	"\x1aGoToGlobalPositionResponse\"\xed\x01\n" +
	"\x1bGoToRelativePositionRequest\x12D\n" +
	"\bposition\x18\x01 \x01(\v2(.steeleagle_protocol.v1.RelativePositionR\bposition\x12\x19\n" +
	"\x05speed\x18\x02 \x01(\x02H\x00R\x05speed\x88\x01\x01\x12Y\n" +
	"\x05frame\x18\x03 \x01(\x0e2>.steeleagle_protocol.v1.services.driver.control.ReferenceFrameH\x01R\x05frame\x88\x01\x01B\b\n" +
	"\x06_speedB\b\n" +
	"\x06_frame\"\x1e\n" +
	"\x1cGoToRelativePositionResponse\"\xb7\x01\n" +
	"\x12SetVelocityRequest\x12<\n" +
	"\bvelocity\x18\x01 \x01(\v2 .steeleagle_protocol.v1.VelocityR\bvelocity\x12Y\n" +
	"\x05frame\x18\x02 \x01(\x0e2>.steeleagle_protocol.v1.services.driver.control.ReferenceFrameH\x00R\x05frame\x88\x01\x01B\b\n" +
	"\x06_frame\"\x15\n" +
	"\x13SetVelocityResponse\"\xcf\x01\n" +
	"\x14SetGimbalPoseRequest\x12\x1b\n" +
	"\tgimbal_id\x18\x01 \x01(\rR\bgimbalId\x120\n" +
	"\x04pose\x18\x02 \x01(\v2\x1c.steeleagle_protocol.v1.PoseR\x04pose\x12Z\n" +
	"\tpose_mode\x18\x03 \x01(\x0e28.steeleagle_protocol.v1.services.driver.control.PoseModeH\x00R\bposeMode\x88\x01\x01B\f\n" +
	"\n" +
	"_pose_mode\"\x17\n" +
	"\x15SetGimbalPoseResponse*\x93\x01\n" +
	"\x17ReturnToHomeEndBehavior\x12+\n" +
	"'RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED\x10\x00\x12%\n" +
	"!RETURN_TO_HOME_END_BEHAVIOR_HOVER\x10\x01\x12$\n" +
	" RETURN_TO_HOME_END_BEHAVIOR_LAND\x10\x02*e\n" +
	"\fAltitudeMode\x12\x1d\n" +
	"\x19ALTITUDE_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALTITUDE_MODE_ABSOLUTE\x10\x01\x12\x1a\n" +
	"\x16ALTITUDE_MODE_RELATIVE\x10\x02*_\n" +
	"\vHeadingMode\x12\x1c\n" +
	"\x18HEADING_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HEADING_MODE_TO_TARGET\x10\x01\x12\x16\n" +
	"\x12HEADING_MODE_START\x10\x02*d\n" +
	"\x0eReferenceFrame\x12\x1f\n" +
	"\x1bREFERENCE_FRAME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REFERENCE_FRAME_BODY\x10\x01\x12\x17\n" +
	"\x13REFERENCE_FRAME_NEU\x10\x02*h\n" +
	"\bPoseMode\x12\x19\n" +
	"\x15POSE_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPOSE_MODE_ANGLE\x10\x01\x12\x14\n" +
	"\x10POSE_MODE_OFFSET\x10\x02\x12\x16\n" +
	"\x12POSE_MODE_VELOCITY\x10\x032\x80\f\n" +
	"\x0eControlService\x12\x8c\x01\n" +
	"\aTakeOff\x12>.steeleagle_protocol.v1.services.driver.control.TakeOffRequest\x1a?.steeleagle_protocol.v1.services.driver.control.TakeOffResponse\"\x00\x12\x83\x01\n" +
	"\x04Land\x12;.steeleagle_protocol.v1.services.driver.control.LandRequest\x1a<.steeleagle_protocol.v1.services.driver.control.LandResponse\"\x00\x12\x83\x01\n" +
	"\x04Hold\x12;.steeleagle_protocol.v1.services.driver.control.HoldRequest\x1a<.steeleagle_protocol.v1.services.driver.control.HoldResponse\"\x00\x12\x83\x01\n" +
	"\x04Kill\x12;.steeleagle_protocol.v1.services.driver.control.KillRequest\x1a<.steeleagle_protocol.v1.services.driver.control.KillResponse\"\x00\x12\x8c\x01\n" +
	"\aSetHome\x12>.steeleagle_protocol.v1.services.driver.control.SetHomeRequest\x1a?.steeleagle_protocol.v1.services.driver.control.SetHomeResponse\"\x00\x12\x9b\x01\n" +
	"\fReturnToHome\x12C.steeleagle_protocol.v1.services.driver.control.ReturnToHomeRequest\x1aD.steeleagle_protocol.v1.services.driver.control.ReturnToHomeResponse\"\x00\x12\xad\x01\n" +
	"\x12GoToGlobalPosition\x12I.steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest\x1aJ.steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionResponse\"\x00\x12\xb3\x01\n" +
	"\x14GoToRelativePosition\x12K.steeleagle_protocol.v1.services.driver.control.GoToRelativePositionRequest\x1aL.steeleagle_protocol.v1.services.driver.control.GoToRelativePositionResponse\"\x00\x12\x98\x01\n" +
	"\vSetVelocity\x12B.steeleagle_protocol.v1.services.driver.control.SetVelocityRequest\x1aC.steeleagle_protocol.v1.services.driver.control.SetVelocityResponse\"\x00\x12\x9e\x01\n" +
	"\rSetGimbalPose\x12D.steeleagle_protocol.v1.services.driver.control.SetGimbalPoseRequest\x1aE.steeleagle_protocol.v1.services.driver.control.SetGimbalPoseResponse\"\x00B\xed\x02\n" +
	"2com.steeleagle_protocol.v1.services.driver.controlB\fControlProtoP\x01ZOgithub.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/driver\xa2\x02\x05SVSDC\xaa\x02-SteeleagleProtocol.V1.Services.Driver.Control\xca\x02-SteeleagleProtocol\\V1\\Services\\Driver\\Control\xe2\x029SteeleagleProtocol\\V1\\Services\\Driver\\Control\\GPBMetadata\xea\x021SteeleagleProtocol::V1::Services::Driver::Controlb\x06proto3"

var (
	file_steeleagle_protocol_v1_services_driver_control_proto_rawDescOnce sync.Once
	file_steeleagle_protocol_v1_services_driver_control_proto_rawDescData []byte
)

func file_steeleagle_protocol_v1_services_driver_control_proto_rawDescGZIP() []byte {
	file_steeleagle_protocol_v1_services_driver_control_proto_rawDescOnce.Do(func() {
		file_steeleagle_protocol_v1_services_driver_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steeleagle_protocol_v1_services_driver_control_proto_rawDesc), len(file_steeleagle_protocol_v1_services_driver_control_proto_rawDesc)))
	})
	return file_steeleagle_protocol_v1_services_driver_control_proto_rawDescData
}

var file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_steeleagle_protocol_v1_services_driver_control_proto_goTypes = []any{
	(ReturnToHomeEndBehavior)(0),         // 0: steeleagle_protocol.v1.services.driver.control.ReturnToHomeEndBehavior
	(AltitudeMode)(0),                    // 1: steeleagle_protocol.v1.services.driver.control.AltitudeMode
	(HeadingMode)(0),                     // 2: steeleagle_protocol.v1.services.driver.control.HeadingMode
	(ReferenceFrame)(0),                  // 3: steeleagle_protocol.v1.services.driver.control.ReferenceFrame
	(PoseMode)(0),                        // 4: steeleagle_protocol.v1.services.driver.control.PoseMode
	(*TakeOffRequest)(nil),               // 5: steeleagle_protocol.v1.services.driver.control.TakeOffRequest
	(*TakeOffResponse)(nil),              // 6: steeleagle_protocol.v1.services.driver.control.TakeOffResponse
	(*LandRequest)(nil),                  // 7: steeleagle_protocol.v1.services.driver.control.LandRequest
	(*LandResponse)(nil),                 // 8: steeleagle_protocol.v1.services.driver.control.LandResponse
	(*HoldRequest)(nil),                  // 9: steeleagle_protocol.v1.services.driver.control.HoldRequest
	(*HoldResponse)(nil),                 // 10: steeleagle_protocol.v1.services.driver.control.HoldResponse
	(*KillRequest)(nil),                  // 11: steeleagle_protocol.v1.services.driver.control.KillRequest
	(*KillResponse)(nil),                 // 12: steeleagle_protocol.v1.services.driver.control.KillResponse
	(*SetHomeRequest)(nil),               // 13: steeleagle_protocol.v1.services.driver.control.SetHomeRequest
	(*SetHomeResponse)(nil),              // 14: steeleagle_protocol.v1.services.driver.control.SetHomeResponse
	(*ReturnToHomeRequest)(nil),          // 15: steeleagle_protocol.v1.services.driver.control.ReturnToHomeRequest
	(*ReturnToHomeResponse)(nil),         // 16: steeleagle_protocol.v1.services.driver.control.ReturnToHomeResponse
	(*GoToGlobalPositionRequest)(nil),    // 17: steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest
	(*GoToGlobalPositionResponse)(nil),   // 18: steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionResponse
	(*GoToRelativePositionRequest)(nil),  // 19: steeleagle_protocol.v1.services.driver.control.GoToRelativePositionRequest
	(*GoToRelativePositionResponse)(nil), // 20: steeleagle_protocol.v1.services.driver.control.GoToRelativePositionResponse
	(*SetVelocityRequest)(nil),           // 21: steeleagle_protocol.v1.services.driver.control.SetVelocityRequest
	(*SetVelocityResponse)(nil),          // 22: steeleagle_protocol.v1.services.driver.control.SetVelocityResponse
	(*SetGimbalPoseRequest)(nil),         // 23: steeleagle_protocol.v1.services.driver.control.SetGimbalPoseRequest
	(*SetGimbalPoseResponse)(nil),        // 24: steeleagle_protocol.v1.services.driver.control.SetGimbalPoseResponse
	(*v1.GlobalPosition)(nil),            // 25: steeleagle_protocol.v1.GlobalPosition
	(*v1.RelativePosition)(nil),          // 26: steeleagle_protocol.v1.RelativePosition
	(*v1.Velocity)(nil),                  // 27: steeleagle_protocol.v1.Velocity
	(*v1.Pose)(nil),                      // 28: steeleagle_protocol.v1.Pose
}
var file_steeleagle_protocol_v1_services_driver_control_proto_depIdxs = []int32{
	25, // 0: steeleagle_protocol.v1.services.driver.control.SetHomeRequest.new_home:type_name -> steeleagle_protocol.v1.GlobalPosition
	0,  // 1: steeleagle_protocol.v1.services.driver.control.ReturnToHomeRequest.end_behavior:type_name -> steeleagle_protocol.v1.services.driver.control.ReturnToHomeEndBehavior
	25, // 2: steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest.position:type_name -> steeleagle_protocol.v1.GlobalPosition
	2,  // 3: steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest.heading_mode:type_name -> steeleagle_protocol.v1.services.driver.control.HeadingMode
	1,  // 4: steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest.altitude_mode:type_name -> steeleagle_protocol.v1.services.driver.control.AltitudeMode
	26, // 5: steeleagle_protocol.v1.services.driver.control.GoToRelativePositionRequest.position:type_name -> steeleagle_protocol.v1.RelativePosition
	3,  // 6: steeleagle_protocol.v1.services.driver.control.GoToRelativePositionRequest.frame:type_name -> steeleagle_protocol.v1.services.driver.control.ReferenceFrame
	27, // 7: steeleagle_protocol.v1.services.driver.control.SetVelocityRequest.velocity:type_name -> steeleagle_protocol.v1.Velocity
	3,  // 8: steeleagle_protocol.v1.services.driver.control.SetVelocityRequest.frame:type_name -> steeleagle_protocol.v1.services.driver.control.ReferenceFrame
	28, // 9: steeleagle_protocol.v1.services.driver.control.SetGimbalPoseRequest.pose:type_name -> steeleagle_protocol.v1.Pose
	4,  // 10: steeleagle_protocol.v1.services.driver.control.SetGimbalPoseRequest.pose_mode:type_name -> steeleagle_protocol.v1.services.driver.control.PoseMode
	5,  // 11: steeleagle_protocol.v1.services.driver.control.ControlService.TakeOff:input_type -> steeleagle_protocol.v1.services.driver.control.TakeOffRequest
	7,  // 12: steeleagle_protocol.v1.services.driver.control.ControlService.Land:input_type -> steeleagle_protocol.v1.services.driver.control.LandRequest
	9,  // 13: steeleagle_protocol.v1.services.driver.control.ControlService.Hold:input_type -> steeleagle_protocol.v1.services.driver.control.HoldRequest
	11, // 14: steeleagle_protocol.v1.services.driver.control.ControlService.Kill:input_type -> steeleagle_protocol.v1.services.driver.control.KillRequest
	13, // 15: steeleagle_protocol.v1.services.driver.control.ControlService.SetHome:input_type -> steeleagle_protocol.v1.services.driver.control.SetHomeRequest
	15, // 16: steeleagle_protocol.v1.services.driver.control.ControlService.ReturnToHome:input_type -> steeleagle_protocol.v1.services.driver.control.ReturnToHomeRequest
	17, // 17: steeleagle_protocol.v1.services.driver.control.ControlService.GoToGlobalPosition:input_type -> steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionRequest
	19, // 18: steeleagle_protocol.v1.services.driver.control.ControlService.GoToRelativePosition:input_type -> steeleagle_protocol.v1.services.driver.control.GoToRelativePositionRequest
	21, // 19: steeleagle_protocol.v1.services.driver.control.ControlService.SetVelocity:input_type -> steeleagle_protocol.v1.services.driver.control.SetVelocityRequest
	23, // 20: steeleagle_protocol.v1.services.driver.control.ControlService.SetGimbalPose:input_type -> steeleagle_protocol.v1.services.driver.control.SetGimbalPoseRequest
	6,  // 21: steeleagle_protocol.v1.services.driver.control.ControlService.TakeOff:output_type -> steeleagle_protocol.v1.services.driver.control.TakeOffResponse
	8,  // 22: steeleagle_protocol.v1.services.driver.control.ControlService.Land:output_type -> steeleagle_protocol.v1.services.driver.control.LandResponse
	10, // 23: steeleagle_protocol.v1.services.driver.control.ControlService.Hold:output_type -> steeleagle_protocol.v1.services.driver.control.HoldResponse
	12, // 24: steeleagle_protocol.v1.services.driver.control.ControlService.Kill:output_type -> steeleagle_protocol.v1.services.driver.control.KillResponse
	14, // 25: steeleagle_protocol.v1.services.driver.control.ControlService.SetHome:output_type -> steeleagle_protocol.v1.services.driver.control.SetHomeResponse
	16, // 26: steeleagle_protocol.v1.services.driver.control.ControlService.ReturnToHome:output_type -> steeleagle_protocol.v1.services.driver.control.ReturnToHomeResponse
	18, // 27: steeleagle_protocol.v1.services.driver.control.ControlService.GoToGlobalPosition:output_type -> steeleagle_protocol.v1.services.driver.control.GoToGlobalPositionResponse
	20, // 28: steeleagle_protocol.v1.services.driver.control.ControlService.GoToRelativePosition:output_type -> steeleagle_protocol.v1.services.driver.control.GoToRelativePositionResponse
	22, // 29: steeleagle_protocol.v1.services.driver.control.ControlService.SetVelocity:output_type -> steeleagle_protocol.v1.services.driver.control.SetVelocityResponse
	24, // 30: steeleagle_protocol.v1.services.driver.control.ControlService.SetGimbalPose:output_type -> steeleagle_protocol.v1.services.driver.control.SetGimbalPoseResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_steeleagle_protocol_v1_services_driver_control_proto_init() }
func file_steeleagle_protocol_v1_services_driver_control_proto_init() {
	if File_steeleagle_protocol_v1_services_driver_control_proto != nil {
		return
	}
	file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[12].OneofWrappers = []any{}
	file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[14].OneofWrappers = []any{}
	file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[16].OneofWrappers = []any{}
	file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steeleagle_protocol_v1_services_driver_control_proto_rawDesc), len(file_steeleagle_protocol_v1_services_driver_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steeleagle_protocol_v1_services_driver_control_proto_goTypes,
		DependencyIndexes: file_steeleagle_protocol_v1_services_driver_control_proto_depIdxs,
		EnumInfos:         file_steeleagle_protocol_v1_services_driver_control_proto_enumTypes,
		MessageInfos:      file_steeleagle_protocol_v1_services_driver_control_proto_msgTypes,
	}.Build()
	File_steeleagle_protocol_v1_services_driver_control_proto = out.File
	file_steeleagle_protocol_v1_services_driver_control_proto_goTypes = nil
	file_steeleagle_protocol_v1_services_driver_control_proto_depIdxs = nil
}
