---
# SPDX-FileCopyrightText: 2026 Carnegie Mellon University - Satyalab
#
# SPDX-License-Identifier: GPL-2.0-only

- name: Bootstrap dev environment targets
  hosts: dev
  gather_facts: false
  roles:
    - bootstrap

- name: Provision the steeleagle contributor dev environment
  hosts: dev
  roles:
    - dev_environment
