// Code generated by protoc interface plugin. DO NOT EDIT.

package types

import (
	fmt "fmt"
	telemetry "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/messages/telemetry"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type batteryInfoWrapper struct {
	inner *telemetry.BatteryInfo // generated concrete type
}

func (w *batteryInfoWrapper) GetPercentage() uint32 {
	return w.inner.GetPercentage()
}

func (w *batteryInfoWrapper) SetPercentage(v uint32) {
	w.inner.SetPercentage(v)
}

type gpsInfoWrapper struct {
	inner *telemetry.GpsInfo // generated concrete type
}

func (w *gpsInfoWrapper) GetSatellites() uint32 {
	return w.inner.GetSatellites()
}

func (w *gpsInfoWrapper) SetSatellites(v uint32) {
	w.inner.SetSatellites(v)
}

type positionInfoWrapper struct {
	inner *telemetry.PositionInfo // generated concrete type
}

func (w *positionInfoWrapper) GetHome() (GlobalPosition, error) {
	if !w.hasHome() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &globalPositionWrapper{inner: w.inner.GetHome()}, nil
}

func (w *positionInfoWrapper) hasHome() bool {
	return w.inner.HasHome()
}

func (w *positionInfoWrapper) SetHome(v GlobalPosition) {
	if v == nil {
		w.inner.SetHome(nil)
		return
	}
	w.inner.SetHome(v.(*globalPositionWrapper).inner)
}

func (w *positionInfoWrapper) GetGlobalPosition() (GlobalPosition, error) {
	if !w.hasGlobalPosition() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &globalPositionWrapper{inner: w.inner.GetGlobalPosition()}, nil
}

func (w *positionInfoWrapper) hasGlobalPosition() bool {
	return w.inner.HasGlobalPosition()
}

func (w *positionInfoWrapper) SetGlobalPosition(v GlobalPosition) {
	if v == nil {
		w.inner.SetGlobalPosition(nil)
		return
	}
	w.inner.SetGlobalPosition(v.(*globalPositionWrapper).inner)
}

func (w *positionInfoWrapper) GetRelativePosition() (RelativePosition, error) {
	if !w.hasRelativePosition() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &relativePositionWrapper{inner: w.inner.GetRelativePosition()}, nil
}

func (w *positionInfoWrapper) hasRelativePosition() bool {
	return w.inner.HasRelativePosition()
}

func (w *positionInfoWrapper) SetRelativePosition(v RelativePosition) {
	if v == nil {
		w.inner.SetRelativePosition(nil)
		return
	}
	w.inner.SetRelativePosition(v.(*relativePositionWrapper).inner)
}

func (w *positionInfoWrapper) GetVelocityBody() (Velocity, error) {
	if !w.hasVelocityBody() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &velocityWrapper{inner: w.inner.GetVelocityBody()}, nil
}

func (w *positionInfoWrapper) hasVelocityBody() bool {
	return w.inner.HasVelocityBody()
}

func (w *positionInfoWrapper) SetVelocityBody(v Velocity) {
	if v == nil {
		w.inner.SetVelocityBody(nil)
		return
	}
	w.inner.SetVelocityBody(v.(*velocityWrapper).inner)
}

func (w *positionInfoWrapper) GetVelocityNeu() (Velocity, error) {
	if !w.hasVelocityNeu() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &velocityWrapper{inner: w.inner.GetVelocityNeu()}, nil
}

func (w *positionInfoWrapper) hasVelocityNeu() bool {
	return w.inner.HasVelocityNeu()
}

func (w *positionInfoWrapper) SetVelocityNeu(v Velocity) {
	if v == nil {
		w.inner.SetVelocityNeu(nil)
		return
	}
	w.inner.SetVelocityNeu(v.(*velocityWrapper).inner)
}

func (w *positionInfoWrapper) GetMotionStatus() PositionInfo_MotionStatus {
	return PositionInfo_MotionStatus(w.inner.GetMotionStatus())
}

func (w *positionInfoWrapper) SetMotionStatus(v PositionInfo_MotionStatus) {
	w.inner.SetMotionStatus(telemetry.PositionInfo_MotionStatus(v))
}

func (w *positionInfoWrapper) GetSetpoint() (*anypb.Any, error) {
	if !w.hasSetpoint() {
		var zero *anypb.Any
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetSetpoint(), nil
}

func (w *positionInfoWrapper) hasSetpoint() bool {
	return w.inner.HasSetpoint()
}

func (w *positionInfoWrapper) SetSetpoint(v *anypb.Any) {
	w.inner.SetSetpoint(v)
}

type gimbalStatusWrapper struct {
	inner *telemetry.GimbalStatus // generated concrete type
}

func (w *gimbalStatusWrapper) GetId() uint32 {
	return w.inner.GetId()
}

func (w *gimbalStatusWrapper) SetId(v uint32) {
	w.inner.SetId(v)
}

func (w *gimbalStatusWrapper) GetPoseBody() (Pose, error) {
	if !w.hasPoseBody() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &poseWrapper{inner: w.inner.GetPoseBody()}, nil
}

func (w *gimbalStatusWrapper) hasPoseBody() bool {
	return w.inner.HasPoseBody()
}

func (w *gimbalStatusWrapper) SetPoseBody(v Pose) {
	if v == nil {
		w.inner.SetPoseBody(nil)
		return
	}
	w.inner.SetPoseBody(v.(*poseWrapper).inner)
}

func (w *gimbalStatusWrapper) GetPoseNeu() (Pose, error) {
	if !w.hasPoseNeu() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &poseWrapper{inner: w.inner.GetPoseNeu()}, nil
}

func (w *gimbalStatusWrapper) hasPoseNeu() bool {
	return w.inner.HasPoseNeu()
}

func (w *gimbalStatusWrapper) SetPoseNeu(v Pose) {
	if v == nil {
		w.inner.SetPoseNeu(nil)
		return
	}
	w.inner.SetPoseNeu(v.(*poseWrapper).inner)
}

func (w *gimbalStatusWrapper) GetAngularVelocityBody() (Pose, error) {
	if !w.hasAngularVelocityBody() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &poseWrapper{inner: w.inner.GetAngularVelocityBody()}, nil
}

func (w *gimbalStatusWrapper) hasAngularVelocityBody() bool {
	return w.inner.HasAngularVelocityBody()
}

func (w *gimbalStatusWrapper) SetAngularVelocityBody(v Pose) {
	if v == nil {
		w.inner.SetAngularVelocityBody(nil)
		return
	}
	w.inner.SetAngularVelocityBody(v.(*poseWrapper).inner)
}

func (w *gimbalStatusWrapper) GetAngularVelocityNeu() (Pose, error) {
	if !w.hasAngularVelocityNeu() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &poseWrapper{inner: w.inner.GetAngularVelocityNeu()}, nil
}

func (w *gimbalStatusWrapper) hasAngularVelocityNeu() bool {
	return w.inner.HasAngularVelocityNeu()
}

func (w *gimbalStatusWrapper) SetAngularVelocityNeu(v Pose) {
	if v == nil {
		w.inner.SetAngularVelocityNeu(nil)
		return
	}
	w.inner.SetAngularVelocityNeu(v.(*poseWrapper).inner)
}

type gimbalInfoWrapper struct {
	inner *telemetry.GimbalInfo // generated concrete type
}

func (w *gimbalInfoWrapper) GetGimbals() []GimbalStatus {
	src := w.inner.GetGimbals()
	out := make([]GimbalStatus, len(src))
	for i, v := range src {
		out[i] = &gimbalStatusWrapper{inner: v}
	}
	return out
}

type alertInfoWrapper struct {
	inner *telemetry.AlertInfo // generated concrete type
}

func (w *alertInfoWrapper) GetBatteryWarning() AlertInfo_BatteryWarning {
	return AlertInfo_BatteryWarning(w.inner.GetBatteryWarning())
}

func (w *alertInfoWrapper) SetBatteryWarning(v AlertInfo_BatteryWarning) {
	w.inner.SetBatteryWarning(telemetry.AlertInfo_BatteryWarning(v))
}

func (w *alertInfoWrapper) GetGpsWarning() AlertInfo_GpsWarning {
	return AlertInfo_GpsWarning(w.inner.GetGpsWarning())
}

func (w *alertInfoWrapper) SetGpsWarning(v AlertInfo_GpsWarning) {
	w.inner.SetGpsWarning(telemetry.AlertInfo_GpsWarning(v))
}

func (w *alertInfoWrapper) GetMagnetometerWarning() AlertInfo_MagnetometerWarning {
	return AlertInfo_MagnetometerWarning(w.inner.GetMagnetometerWarning())
}

func (w *alertInfoWrapper) SetMagnetometerWarning(v AlertInfo_MagnetometerWarning) {
	w.inner.SetMagnetometerWarning(telemetry.AlertInfo_MagnetometerWarning(v))
}

func (w *alertInfoWrapper) GetConnectionWarning() AlertInfo_ConnectionWarning {
	return AlertInfo_ConnectionWarning(w.inner.GetConnectionWarning())
}

func (w *alertInfoWrapper) SetConnectionWarning(v AlertInfo_ConnectionWarning) {
	w.inner.SetConnectionWarning(telemetry.AlertInfo_ConnectionWarning(v))
}

func (w *alertInfoWrapper) GetCompassWarning() AlertInfo_CompassWarning {
	return AlertInfo_CompassWarning(w.inner.GetCompassWarning())
}

func (w *alertInfoWrapper) SetCompassWarning(v AlertInfo_CompassWarning) {
	w.inner.SetCompassWarning(telemetry.AlertInfo_CompassWarning(v))
}

type telemetryWrapper struct {
	inner *telemetry.Telemetry // generated concrete type
}

func (w *telemetryWrapper) GetTimestamp() (*timestamppb.Timestamp, error) {
	if !w.hasTimestamp() {
		var zero *timestamppb.Timestamp
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetTimestamp(), nil
}

func (w *telemetryWrapper) hasTimestamp() bool {
	return w.inner.HasTimestamp()
}

func (w *telemetryWrapper) SetTimestamp(v *timestamppb.Timestamp) {
	w.inner.SetTimestamp(v)
}

func (w *telemetryWrapper) GetBatteryInfo() (BatteryInfo, error) {
	if !w.hasBatteryInfo() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &batteryInfoWrapper{inner: w.inner.GetBatteryInfo()}, nil
}

func (w *telemetryWrapper) hasBatteryInfo() bool {
	return w.inner.HasBatteryInfo()
}

func (w *telemetryWrapper) SetBatteryInfo(v BatteryInfo) {
	if v == nil {
		w.inner.SetBatteryInfo(nil)
		return
	}
	w.inner.SetBatteryInfo(v.(*batteryInfoWrapper).inner)
}

func (w *telemetryWrapper) GetGpsInfo() (GpsInfo, error) {
	if !w.hasGpsInfo() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &gpsInfoWrapper{inner: w.inner.GetGpsInfo()}, nil
}

func (w *telemetryWrapper) hasGpsInfo() bool {
	return w.inner.HasGpsInfo()
}

func (w *telemetryWrapper) SetGpsInfo(v GpsInfo) {
	if v == nil {
		w.inner.SetGpsInfo(nil)
		return
	}
	w.inner.SetGpsInfo(v.(*gpsInfoWrapper).inner)
}

func (w *telemetryWrapper) GetPositionInfo() (PositionInfo, error) {
	if !w.hasPositionInfo() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &positionInfoWrapper{inner: w.inner.GetPositionInfo()}, nil
}

func (w *telemetryWrapper) hasPositionInfo() bool {
	return w.inner.HasPositionInfo()
}

func (w *telemetryWrapper) SetPositionInfo(v PositionInfo) {
	if v == nil {
		w.inner.SetPositionInfo(nil)
		return
	}
	w.inner.SetPositionInfo(v.(*positionInfoWrapper).inner)
}

func (w *telemetryWrapper) GetGimbalInfo() (GimbalInfo, error) {
	if !w.hasGimbalInfo() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &gimbalInfoWrapper{inner: w.inner.GetGimbalInfo()}, nil
}

func (w *telemetryWrapper) hasGimbalInfo() bool {
	return w.inner.HasGimbalInfo()
}

func (w *telemetryWrapper) SetGimbalInfo(v GimbalInfo) {
	if v == nil {
		w.inner.SetGimbalInfo(nil)
		return
	}
	w.inner.SetGimbalInfo(v.(*gimbalInfoWrapper).inner)
}

func (w *telemetryWrapper) GetAlertInfo() (AlertInfo, error) {
	if !w.hasAlertInfo() {
		return nil, fmt.Errorf("field not present in message, using default value")
	}
	return &alertInfoWrapper{inner: w.inner.GetAlertInfo()}, nil
}

func (w *telemetryWrapper) hasAlertInfo() bool {
	return w.inner.HasAlertInfo()
}

func (w *telemetryWrapper) SetAlertInfo(v AlertInfo) {
	if v == nil {
		w.inner.SetAlertInfo(nil)
		return
	}
	w.inner.SetAlertInfo(v.(*alertInfoWrapper).inner)
}
