// Code generated by protoc interface plugin. DO NOT EDIT.

package types

type ReturnToHomeEndBehavior int32

const (
	ReturnToHomeEndBehaviorUnspecified ReturnToHomeEndBehavior = 0
	ReturnToHomeEndBehaviorHover       ReturnToHomeEndBehavior = 1
	ReturnToHomeEndBehaviorLand        ReturnToHomeEndBehavior = 2
)

type AltitudeMode int32

const (
	AltitudeModeUnspecified AltitudeMode = 0
	AltitudeModeRelative    AltitudeMode = 1
	AltitudeModeAbsolute    AltitudeMode = 2
)

type HeadingMode int32

const (
	HeadingModeUnspecified HeadingMode = 0
	HeadingModeToTarget    HeadingMode = 1
	HeadingModeStart       HeadingMode = 2
)

type ReferenceFrame int32

const (
	ReferenceFrameUnspecified ReferenceFrame = 0
	ReferenceFrameBody        ReferenceFrame = 1
	ReferenceFrameNeu         ReferenceFrame = 2
)

type PoseMode int32

const (
	PoseModeUnspecified PoseMode = 0
	PoseModeAngle       PoseMode = 1
	PoseModeOffset      PoseMode = 2
	PoseModeVelocity    PoseMode = 3
)

type TakeOffRequest interface {
	GetAltitude() float32
	SetAltitude(v float32)
}

type TakeOffResponse interface {
}

type LandRequest interface {
}

type LandResponse interface {
}

type HoldRequest interface {
}

type HoldResponse interface {
}

type KillRequest interface {
}

type KillResponse interface {
}

type SetHomeRequest interface {
	GetNewHome() (GlobalPosition, error)
	hasNewHome() bool
	SetNewHome(v GlobalPosition)
}

type SetHomeResponse interface {
}

type ReturnToHomeRequest interface {
	GetEndBehavior() ReturnToHomeEndBehavior
	SetEndBehavior(v ReturnToHomeEndBehavior)
	GetMinReturnAltitude() uint32
	SetMinReturnAltitude(v uint32)
	GetFinalAltitude() uint32
	SetFinalAltitude(v uint32)
}

type ReturnToHomeResponse interface {
}

type GoToGlobalPositionRequest interface {
	GetPosition() (GlobalPosition, error)
	hasPosition() bool
	SetPosition(v GlobalPosition)
	GetHeadingMode() (HeadingMode, error)
	hasHeadingMode() bool
	SetHeadingMode(v HeadingMode)
	GetAltitudeMode() (AltitudeMode, error)
	hasAltitudeMode() bool
	SetAltitudeMode(v AltitudeMode)
	GetSpeed() (float32, error)
	hasSpeed() bool
	SetSpeed(v float32)
	GetAngularSpeed() (float32, error)
	hasAngularSpeed() bool
	SetAngularSpeed(v float32)
}

type GoToGlobalPositionResponse interface {
}

type GoToRelativePositionRequest interface {
	GetPosition() (RelativePosition, error)
	hasPosition() bool
	SetPosition(v RelativePosition)
	GetSpeed() (float32, error)
	hasSpeed() bool
	SetSpeed(v float32)
	GetAngularSpeed() (float32, error)
	hasAngularSpeed() bool
	SetAngularSpeed(v float32)
	GetFrame() (ReferenceFrame, error)
	hasFrame() bool
	SetFrame(v ReferenceFrame)
}

type GoToRelativePositionResponse interface {
}

type SetVelocityRequest interface {
	GetVelocity() (Velocity, error)
	hasVelocity() bool
	SetVelocity(v Velocity)
	GetFrame() (ReferenceFrame, error)
	hasFrame() bool
	SetFrame(v ReferenceFrame)
}

type SetVelocityResponse interface {
}

type SetGimbalPoseRequest interface {
	GetGimbalId() uint32
	SetGimbalId(v uint32)
	GetPose() (Pose, error)
	hasPose() bool
	SetPose(v Pose)
	GetPoseMode() (PoseMode, error)
	hasPoseMode() bool
	SetPoseMode(v PoseMode)
}

type SetGimbalPoseResponse interface {
}

type GetVehicleInfoRequest interface {
}

type GetVehicleInfoResponse interface {
	GetModel() string
	SetModel(v string)
}
