// Code generated by protoc interface plugin. DO NOT EDIT.

package types

import (
	fmt "fmt"
	v1 "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1"
)

type poseWrapper struct {
	inner *v1.Pose // generated concrete type
}

func (w *poseWrapper) GetPitch() (float64, error) {
	if !w.hasPitch() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetPitch(), nil
}

func (w *poseWrapper) hasPitch() bool {
	return w.inner.HasPitch()
}

func (w *poseWrapper) GetRoll() (float64, error) {
	if !w.hasRoll() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetRoll(), nil
}

func (w *poseWrapper) hasRoll() bool {
	return w.inner.HasRoll()
}

func (w *poseWrapper) GetYaw() (float64, error) {
	if !w.hasYaw() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetYaw(), nil
}

func (w *poseWrapper) hasYaw() bool {
	return w.inner.HasYaw()
}

type velocityWrapper struct {
	inner *v1.Velocity // generated concrete type
}

func (w *velocityWrapper) GetXVel() (float64, error) {
	if !w.hasXVel() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetXVel(), nil
}

func (w *velocityWrapper) hasXVel() bool {
	return w.inner.HasXVel()
}

func (w *velocityWrapper) GetYVel() (float64, error) {
	if !w.hasYVel() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetYVel(), nil
}

func (w *velocityWrapper) hasYVel() bool {
	return w.inner.HasYVel()
}

func (w *velocityWrapper) GetZVel() (float64, error) {
	if !w.hasZVel() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetZVel(), nil
}

func (w *velocityWrapper) hasZVel() bool {
	return w.inner.HasZVel()
}

func (w *velocityWrapper) GetAngularVel() (float64, error) {
	if !w.hasAngularVel() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetAngularVel(), nil
}

func (w *velocityWrapper) hasAngularVel() bool {
	return w.inner.HasAngularVel()
}

type globalPositionWrapper struct {
	inner *v1.GlobalPosition // generated concrete type
}

func (w *globalPositionWrapper) GetLatitude() (float64, error) {
	if !w.hasLatitude() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetLatitude(), nil
}

func (w *globalPositionWrapper) hasLatitude() bool {
	return w.inner.HasLatitude()
}

func (w *globalPositionWrapper) GetLongitude() (float64, error) {
	if !w.hasLongitude() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetLongitude(), nil
}

func (w *globalPositionWrapper) hasLongitude() bool {
	return w.inner.HasLongitude()
}

func (w *globalPositionWrapper) GetAltitude() (float64, error) {
	if !w.hasAltitude() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetAltitude(), nil
}

func (w *globalPositionWrapper) hasAltitude() bool {
	return w.inner.HasAltitude()
}

func (w *globalPositionWrapper) GetHeading() (float64, error) {
	if !w.hasHeading() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetHeading(), nil
}

func (w *globalPositionWrapper) hasHeading() bool {
	return w.inner.HasHeading()
}

type relativePositionWrapper struct {
	inner *v1.RelativePosition // generated concrete type
}

func (w *relativePositionWrapper) GetX() (float64, error) {
	if !w.hasX() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetX(), nil
}

func (w *relativePositionWrapper) hasX() bool {
	return w.inner.HasX()
}

func (w *relativePositionWrapper) GetY() (float64, error) {
	if !w.hasY() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetY(), nil
}

func (w *relativePositionWrapper) hasY() bool {
	return w.inner.HasY()
}

func (w *relativePositionWrapper) GetZ() (float64, error) {
	if !w.hasZ() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetZ(), nil
}

func (w *relativePositionWrapper) hasZ() bool {
	return w.inner.HasZ()
}

func (w *relativePositionWrapper) GetAngle() (float64, error) {
	if !w.hasAngle() {
		var zero float64
		return zero, fmt.Errorf("field not present in message, using default value")
	}
	return w.inner.GetAngle(), nil
}

func (w *relativePositionWrapper) hasAngle() bool {
	return w.inner.HasAngle()
}
