# Initial control state
first = 'REMOTE'

# State definitions start here!
[[states]]
name = 'REMOTE'
allowed = []
match = [
    ['server/**.Mission/Start', 'LOCAL']
]

[[states]]
name = 'LOCAL'
allowed = [
    'internal/**.Control/*',
    'internal/**.Compute/*',
]
match = [
    ['server/**', 'REMOTE']
]
