# Initial control state
first = 'REMOTE'

# State definitions start here!
[[states]]
name = 'REMOTE'
allowed = []
match = [
    ['server/**.MissionService/Start', 'LOCAL']
]

[[states]]
name = 'LOCAL'
allowed = [
    'internal/**.ControlService/*',
    'internal/**.ComputeService/*',
]
match = [
    ['server/**', 'REMOTE']
]
