# Initial control state
first = 'REMOTE'

# State definitions start here!
[[states]]
name = 'REMOTE'
allowed = []
match = [
    ['server/**.MissionService/StartMission', 'LOCAL']
]

[[states]]
name = 'LOCAL'
allowed = [
    'mission/**.ControlService/*',
    'mission/**.DataService/*',
]
match = [
    ['server/**', 'REMOTE']
]
