services:
  taky:
    build:
      context: ./tak
      dockerfile: tak/Dockerfile.taky
    restart: unless-stopped
    ports:
      - "8088:8088"

  steeleagle-tak:
    build: ./tak
    restart: unless-stopped
    env:
      COT_URL: "${COT_URL}"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_USERNAME: "steeleagle"
      REDIS_PASSWORD: "${REDIS_AUTH}"
    networks:
      - redis
