// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.messages.telemetry;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/messages/telemetry;telemetry";

import "steeleagle_protocol/v1/common/common.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

// Information about the vehicle battery.
message BatteryInfo {
  optional uint32 percentage = 1; // battery level [0-100]%
}

// Information about the vehicle GPS fix.
message GpsInfo {
  optional uint32 satellites = 1; // number of satellites used in GPS fix
}

// Information about the vehicle position.
message PositionInfo {
  // global position that will be used when returning home
  optional common.GlobalPosition home = 1;
  // current global position of the vehicle
  optional common.GlobalPosition global_position = 2;
  /*
   * current relative position of the vehicle in the global NEU
   * (North, East, Up) coordinate frame, relative to start
   * position
   */
  optional common.RelativePosition relative_position = 3;
  /*
   * current velocity of the vehicle in the body (forward, right, up)
   * coordinate frame
   */
  optional common.Velocity velocity_body = 4;
  /*
   * current velocity of the vehicle in the global NEU (North, East, Up)
   * coordinate frame
   */
  optional common.Velocity velocity_neu = 5;
  // setpoint of the vehicle (for guidance commands)
  google.protobuf.Any setpoint = 6;
}

// Information about the primary gimbal.
message GimbalInfo {
  // current pose in the body (forward, right, up) reference frame
  optional common.Pose pose_body = 1;
  // current pose in the NEU (North, East, Up) reference frame
  optional common.Pose pose_neu = 2;
  // angular velocity in the body (forward, right, up) reference frame
  optional common.PoseVelocity angular_velocity_body = 3;
  // angular velocity in the NEU (North, East, Up) reference frame
  optional common.PoseVelocity angular_velocity_neu = 4;
  // setpoint for the gimbal
  google.protobuf.Any gimbal_setpoint = 5;
}

// Information about all vehicle warning and alerts.
message AlertInfo {
  // Battery warnings and alerts.
  enum BatteryWarning {
    // the vehicle is above 30% battery
    BATTERY_WARNING_UNSPECIFIED = 0;
    // the vehicle is below 30% battery
    BATTERY_WARNING_LOW = 1;
    // the vehicle is below 15% battery
    BATTERY_WARNING_CRITICAL = 2;
  }
  // battery warnings
  BatteryWarning battery_warning = 1;
  // GPS fix warnings and alerts.
  enum GpsWarning {
    // GPS readings are nominal and a fix has been achieved
    GPS_WARNING_UNSPECIFIED = 0;
    // weak GPS fix, expect errant global position data
    GPS_WARNING_WEAK_SIGNAL = 1;
    // no GPS fix
    GPS_WARNING_NO_FIX = 2;
  }
  // GPS warnings
  GpsWarning gps_warning = 2;
  // Magnetometer warnings and alerts.
  enum MagnetometerWarning {
    // magnetometer readings are nominal
    MAGNETOMETER_WARNING_UNSPECIFIED = 0;
    // the vehicle is experiencing magnetic perturbations
    MAGNETOMETER_WARNING_PERTURBATIONS = 1;
  }
  // magnetometer warnings
  MagnetometerWarning magnetometer_warning = 3;
  // Connection warnings and alerts.
  enum ConnectionWarning {
    // connection to remote server is nominal
    CONNECTION_WARNING_UNSPECIFIED = 0;
    // contact has been lost with the remote server
    CONNECTION_WARNING_DISCONNECTED = 1;
    // connection is experiencing interference or is weak
    CONNECTION_WARNING_WEAK_CONNECTION = 2;
  }
  // connection warnings
  ConnectionWarning connection_warning = 4;
  // Compass warnings and alerts.
  enum CompassWarning {
    // absolute heading is nominal
    COMPASS_WARNING_UNSPECIFIED = 0;
    // absolute heading is available but may be incorrect
    COMPASS_WARNING_WEAK_LOCK = 1;
    // no absolute heading available from the vehicle
    COMPASS_WARNING_NO_LOCK = 2;
  }
  // compass warnings
  CompassWarning compass_warning = 5;
}

// Current flight mode of the vehicle.
enum Mode {
  // the vehicle is not providing mode information
  MODE_UNSPECIFIED = 0;
  // the vehicle is in takeoff mode
  MODE_TAKEOFF = 1;
  // the vehicle is in land mode
  MODE_LAND = 2;
  // the vehicle is in loiter mode
  MODE_LOITER = 3;
  // the vehicle is in guided mode
  MODE_GUIDED = 4;
  // the vehicle is returning to home
  MODE_RETURN_TO_HOME = 5;
  // the vehicle is experiencing an emergency
  MODE_EMERGENCY = 6;
}

// Motion status of the vehicle.
enum MotionStatus {
  // the vehicle is not providing information on its motion status
  MOTION_STATUS_UNSPECIFIED = 0;
  // the vehicle is holding
  MOTION_STATUS_HOLDING = 1;
  // the vehicle is in transit
  MOTION_STATUS_IN_TRANSIT = 2;
  // the vehicle is stopped/disarmed
  MOTION_STATUS_STOPPED = 3;
}

/*
 * Telemetry message for the vehicle, originating from the driver module.
 *
 * This message provides frame data from currently streaming imaging sensors.
 * It is one of two message (`Telemetry`, `Frame`) that is broadcast by the
 * driver.
 */
message Telemetry {
  // timestamp of message
  google.protobuf.Timestamp timestamp = 1;
  // battery info
  BatteryInfo battery_info = 2;
  // GPS and satellite info
  GpsInfo gps_info = 3;
  // positional info about the vehicle
  PositionInfo position_info = 4;
  // primary gimbal info
  GimbalInfo gimbal_info = 5;
  // enumeration of vehicle warnings
  AlertInfo alert_info = 6;
  // flight mode of the vehicle
  optional Mode mode = 7;
  // Motion status of the vehicle
  optional MotionStatus motion_status = 8;
}

// Raw camera frames
message RawFrame {
  // capture timestamp of the frame
  google.protobuf.Timestamp timestamp = 1;
  // raw bytes representing the frame
  bytes data = 2;
  // horizontal frame resolution in pixels
  uint64 h_res = 3;
  // vertical frame resolution in pixels
  uint64 v_res = 4;
  // depth resolution in pixels
  uint64 d_res = 5;
  // number of channels
  uint64 channels = 6;
  // frame ID for future correlation
  uint64 id = 7;
  // positional info about the vehicle
  PositionInfo position_info = 8;
  // info on the gimbal this frame is attached to, if applicable
  GimbalInfo gimbal_info = 9;
  // ID of origin camera
  uint64 camera_id = 10;
}

// Compressed camera frames (JPG encoded)
message EncodedFrame {
  // capture timestamp of the frame
  google.protobuf.Timestamp timestamp = 1;
  // encoded bytes representing the frame
  bytes encoded_data = 2;
  // frame ID for future correlation
  uint64 id = 3;
  // info on the gimbal this frame is attached to, if applicable
  GimbalInfo gimbal_info = 4;
  // positional info about the vehicle
  PositionInfo position_info = 5;
  // ID of origin camera
  uint64 camera_id = 6;
}
