// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steeleagle_protocol/v1/services/vehicle/data.proto

package vehicle

import (
	result "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/messages/result"
	telemetry "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/messages/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // name of the result producer to pull from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetResultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *result.ComputeResult  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultResponse) Reset() {
	*x = GetResultResponse{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultResponse) ProtoMessage() {}

func (x *GetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultResponse.ProtoReflect.Descriptor instead.
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetResultResponse) GetResult() *result.ComputeResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{2}
}

type GetTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *telemetry.Telemetry   `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"` // most recent telemetry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryResponse) Reset() {
	*x = GetTelemetryResponse{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryResponse) ProtoMessage() {}

func (x *GetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetTelemetryResponse) GetTelemetry() *telemetry.Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type GetFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrameRequest) Reset() {
	*x = GetFrameRequest{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrameRequest) ProtoMessage() {}

func (x *GetFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrameRequest.ProtoReflect.Descriptor instead.
func (*GetFrameRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{4}
}

type GetFrameResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Frame         *telemetry.EncodedFrame `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // most recent frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrameResponse) Reset() {
	*x = GetFrameResponse{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrameResponse) ProtoMessage() {}

func (x *GetFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrameResponse.ProtoReflect.Descriptor instead.
func (*GetFrameResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetFrameResponse) GetFrame() *telemetry.EncodedFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type StreamVideoFramesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVideoFramesRequest) Reset() {
	*x = StreamVideoFramesRequest{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVideoFramesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoFramesRequest) ProtoMessage() {}

func (x *StreamVideoFramesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoFramesRequest.ProtoReflect.Descriptor instead.
func (*StreamVideoFramesRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{6}
}

type StreamVideoFramesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Frame         *telemetry.EncodedFrame `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // encoded frame from the camera
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVideoFramesResponse) Reset() {
	*x = StreamVideoFramesResponse{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVideoFramesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoFramesResponse) ProtoMessage() {}

func (x *StreamVideoFramesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoFramesResponse.ProtoReflect.Descriptor instead.
func (*StreamVideoFramesResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{7}
}

func (x *StreamVideoFramesResponse) GetFrame() *telemetry.EncodedFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type StreamTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{8}
}

type StreamTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *telemetry.Telemetry   `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"` // telemetry from the driver
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryResponse) Reset() {
	*x = StreamTelemetryResponse{}
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryResponse) ProtoMessage() {}

func (x *StreamTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryResponse.ProtoReflect.Descriptor instead.
func (*StreamTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP(), []int{9}
}

func (x *StreamTelemetryResponse) GetTelemetry() *telemetry.Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

var File_steeleagle_protocol_v1_services_vehicle_data_proto protoreflect.FileDescriptor

const file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDesc = "" +
	"\n" +
	"2steeleagle_protocol/v1/services/vehicle/data.proto\x12,steeleagle_protocol.v1.services.vehicle.data\x1a3steeleagle_protocol/v1/messages/result/result.proto\x1a9steeleagle_protocol/v1/messages/telemetry/telemetry.proto\"&\n" +
	"\x10GetResultRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\x11GetResultResponse\x12M\n" +
	"\x06result\x18\x01 \x01(\v25.steeleagle_protocol.v1.messages.result.ComputeResultR\x06result\"\x15\n" +
	"\x13GetTelemetryRequest\"j\n" +
	"\x14GetTelemetryResponse\x12R\n" +
	"\ttelemetry\x18\x01 \x01(\v24.steeleagle_protocol.v1.messages.telemetry.TelemetryR\ttelemetry\"\x11\n" +
	"\x0fGetFrameRequest\"a\n" +
	"\x10GetFrameResponse\x12M\n" +
	"\x05frame\x18\x01 \x01(\v27.steeleagle_protocol.v1.messages.telemetry.EncodedFrameR\x05frame\"\x1a\n" +
	"\x18StreamVideoFramesRequest\"j\n" +
	"\x19StreamVideoFramesResponse\x12M\n" +
	"\x05frame\x18\x01 \x01(\v27.steeleagle_protocol.v1.messages.telemetry.EncodedFrameR\x05frame\"\x18\n" +
	"\x16StreamTelemetryRequest\"m\n" +
	"\x17StreamTelemetryResponse\x12R\n" +
	"\ttelemetry\x18\x01 \x01(\v24.steeleagle_protocol.v1.messages.telemetry.TelemetryR\ttelemetry2\x92\x06\n" +
	"\vDataService\x12\x8e\x01\n" +
	"\tGetResult\x12>.steeleagle_protocol.v1.services.vehicle.data.GetResultRequest\x1a?.steeleagle_protocol.v1.services.vehicle.data.GetResultResponse\"\x00\x12\x97\x01\n" +
	"\fGetTelemetry\x12A.steeleagle_protocol.v1.services.vehicle.data.GetTelemetryRequest\x1aB.steeleagle_protocol.v1.services.vehicle.data.GetTelemetryResponse\"\x00\x12\x8b\x01\n" +
	"\bGetFrame\x12=.steeleagle_protocol.v1.services.vehicle.data.GetFrameRequest\x1a>.steeleagle_protocol.v1.services.vehicle.data.GetFrameResponse\"\x00\x12\xa6\x01\n" +
	"\x11StreamVideoFrames\x12F.steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesRequest\x1aG.steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesResponse0\x01\x12\xa0\x01\n" +
	"\x0fStreamTelemetry\x12D.steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryRequest\x1aE.steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryResponse0\x01B\xe1\x02\n" +
	"0com.steeleagle_protocol.v1.services.vehicle.dataB\tDataProtoP\x01ZPgithub.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/vehicle\xa2\x02\x05SVSVD\xaa\x02+SteeleagleProtocol.V1.Services.Vehicle.Data\xca\x02+SteeleagleProtocol\\V1\\Services\\Vehicle\\Data\xe2\x027SteeleagleProtocol\\V1\\Services\\Vehicle\\Data\\GPBMetadata\xea\x02/SteeleagleProtocol::V1::Services::Vehicle::Datab\x06proto3"

var (
	file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescOnce sync.Once
	file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescData []byte
)

func file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescGZIP() []byte {
	file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescOnce.Do(func() {
		file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDesc), len(file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDesc)))
	})
	return file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDescData
}

var file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_steeleagle_protocol_v1_services_vehicle_data_proto_goTypes = []any{
	(*GetResultRequest)(nil),          // 0: steeleagle_protocol.v1.services.vehicle.data.GetResultRequest
	(*GetResultResponse)(nil),         // 1: steeleagle_protocol.v1.services.vehicle.data.GetResultResponse
	(*GetTelemetryRequest)(nil),       // 2: steeleagle_protocol.v1.services.vehicle.data.GetTelemetryRequest
	(*GetTelemetryResponse)(nil),      // 3: steeleagle_protocol.v1.services.vehicle.data.GetTelemetryResponse
	(*GetFrameRequest)(nil),           // 4: steeleagle_protocol.v1.services.vehicle.data.GetFrameRequest
	(*GetFrameResponse)(nil),          // 5: steeleagle_protocol.v1.services.vehicle.data.GetFrameResponse
	(*StreamVideoFramesRequest)(nil),  // 6: steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesRequest
	(*StreamVideoFramesResponse)(nil), // 7: steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesResponse
	(*StreamTelemetryRequest)(nil),    // 8: steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryRequest
	(*StreamTelemetryResponse)(nil),   // 9: steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryResponse
	(*result.ComputeResult)(nil),      // 10: steeleagle_protocol.v1.messages.result.ComputeResult
	(*telemetry.Telemetry)(nil),       // 11: steeleagle_protocol.v1.messages.telemetry.Telemetry
	(*telemetry.EncodedFrame)(nil),    // 12: steeleagle_protocol.v1.messages.telemetry.EncodedFrame
}
var file_steeleagle_protocol_v1_services_vehicle_data_proto_depIdxs = []int32{
	10, // 0: steeleagle_protocol.v1.services.vehicle.data.GetResultResponse.result:type_name -> steeleagle_protocol.v1.messages.result.ComputeResult
	11, // 1: steeleagle_protocol.v1.services.vehicle.data.GetTelemetryResponse.telemetry:type_name -> steeleagle_protocol.v1.messages.telemetry.Telemetry
	12, // 2: steeleagle_protocol.v1.services.vehicle.data.GetFrameResponse.frame:type_name -> steeleagle_protocol.v1.messages.telemetry.EncodedFrame
	12, // 3: steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesResponse.frame:type_name -> steeleagle_protocol.v1.messages.telemetry.EncodedFrame
	11, // 4: steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryResponse.telemetry:type_name -> steeleagle_protocol.v1.messages.telemetry.Telemetry
	0,  // 5: steeleagle_protocol.v1.services.vehicle.data.DataService.GetResult:input_type -> steeleagle_protocol.v1.services.vehicle.data.GetResultRequest
	2,  // 6: steeleagle_protocol.v1.services.vehicle.data.DataService.GetTelemetry:input_type -> steeleagle_protocol.v1.services.vehicle.data.GetTelemetryRequest
	4,  // 7: steeleagle_protocol.v1.services.vehicle.data.DataService.GetFrame:input_type -> steeleagle_protocol.v1.services.vehicle.data.GetFrameRequest
	6,  // 8: steeleagle_protocol.v1.services.vehicle.data.DataService.StreamVideoFrames:input_type -> steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesRequest
	8,  // 9: steeleagle_protocol.v1.services.vehicle.data.DataService.StreamTelemetry:input_type -> steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryRequest
	1,  // 10: steeleagle_protocol.v1.services.vehicle.data.DataService.GetResult:output_type -> steeleagle_protocol.v1.services.vehicle.data.GetResultResponse
	3,  // 11: steeleagle_protocol.v1.services.vehicle.data.DataService.GetTelemetry:output_type -> steeleagle_protocol.v1.services.vehicle.data.GetTelemetryResponse
	5,  // 12: steeleagle_protocol.v1.services.vehicle.data.DataService.GetFrame:output_type -> steeleagle_protocol.v1.services.vehicle.data.GetFrameResponse
	7,  // 13: steeleagle_protocol.v1.services.vehicle.data.DataService.StreamVideoFrames:output_type -> steeleagle_protocol.v1.services.vehicle.data.StreamVideoFramesResponse
	9,  // 14: steeleagle_protocol.v1.services.vehicle.data.DataService.StreamTelemetry:output_type -> steeleagle_protocol.v1.services.vehicle.data.StreamTelemetryResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_steeleagle_protocol_v1_services_vehicle_data_proto_init() }
func file_steeleagle_protocol_v1_services_vehicle_data_proto_init() {
	if File_steeleagle_protocol_v1_services_vehicle_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDesc), len(file_steeleagle_protocol_v1_services_vehicle_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steeleagle_protocol_v1_services_vehicle_data_proto_goTypes,
		DependencyIndexes: file_steeleagle_protocol_v1_services_vehicle_data_proto_depIdxs,
		MessageInfos:      file_steeleagle_protocol_v1_services_vehicle_data_proto_msgTypes,
	}.Build()
	File_steeleagle_protocol_v1_services_vehicle_data_proto = out.File
	file_steeleagle_protocol_v1_services_vehicle_data_proto_goTypes = nil
	file_steeleagle_protocol_v1_services_vehicle_data_proto_depIdxs = nil
}
