// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steeleagle_protocol/v1/services/vehicle/data.proto

package vehicle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_GetResult_FullMethodName         = "/steeleagle_protocol.v1.services.vehicle.data.DataService/GetResult"
	DataService_GetTelemetry_FullMethodName      = "/steeleagle_protocol.v1.services.vehicle.data.DataService/GetTelemetry"
	DataService_GetFrame_FullMethodName          = "/steeleagle_protocol.v1.services.vehicle.data.DataService/GetFrame"
	DataService_StreamVideoFrames_FullMethodName = "/steeleagle_protocol.v1.services.vehicle.data.DataService/StreamVideoFrames"
	DataService_StreamTelemetry_FullMethodName   = "/steeleagle_protocol.v1.services.vehicle.data.DataService/StreamTelemetry"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Used to get up-to-date results, telemetry, and video frames.
//
// This service is used to retrieve the most recent results, telemetry,
// and video frames from the driver or other publisher plugins.
type DataServiceClient interface {
	// Get the most recent produced result.
	//
	// Retrieves the most recent produced result from the named engine.
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	// Get the most recent telemetry data.
	//
	// Retrieves the most recent telemetry data from the driver.
	GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error)
	// Get the most recent video frame.
	//
	// Retrieves the most recent video frame from the driver.
	GetFrame(ctx context.Context, in *GetFrameRequest, opts ...grpc.CallOption) (*GetFrameResponse, error)
	// Stream individual video frames from the vehicle.
	//
	// Retrieves a stream of individual video frame from the vehicle.
	StreamVideoFrames(ctx context.Context, in *StreamVideoFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamVideoFramesResponse], error)
	// Stream telemetry from the vehicle.
	//
	// Streams up-to-date telemetry from the vehicle.
	StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamTelemetryResponse], error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, DataService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetryResponse)
	err := c.cc.Invoke(ctx, DataService_GetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetFrame(ctx context.Context, in *GetFrameRequest, opts ...grpc.CallOption) (*GetFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFrameResponse)
	err := c.cc.Invoke(ctx, DataService_GetFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) StreamVideoFrames(ctx context.Context, in *StreamVideoFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamVideoFramesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_StreamVideoFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamVideoFramesRequest, StreamVideoFramesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamVideoFramesClient = grpc.ServerStreamingClient[StreamVideoFramesResponse]

func (c *dataServiceClient) StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamTelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], DataService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTelemetryRequest, StreamTelemetryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamTelemetryClient = grpc.ServerStreamingClient[StreamTelemetryResponse]

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
//
// Used to get up-to-date results, telemetry, and video frames.
//
// This service is used to retrieve the most recent results, telemetry,
// and video frames from the driver or other publisher plugins.
type DataServiceServer interface {
	// Get the most recent produced result.
	//
	// Retrieves the most recent produced result from the named engine.
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	// Get the most recent telemetry data.
	//
	// Retrieves the most recent telemetry data from the driver.
	GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error)
	// Get the most recent video frame.
	//
	// Retrieves the most recent video frame from the driver.
	GetFrame(context.Context, *GetFrameRequest) (*GetFrameResponse, error)
	// Stream individual video frames from the vehicle.
	//
	// Retrieves a stream of individual video frame from the vehicle.
	StreamVideoFrames(*StreamVideoFramesRequest, grpc.ServerStreamingServer[StreamVideoFramesResponse]) error
	// Stream telemetry from the vehicle.
	//
	// Streams up-to-date telemetry from the vehicle.
	StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[StreamTelemetryResponse]) error
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedDataServiceServer) GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetry not implemented")
}
func (UnimplementedDataServiceServer) GetFrame(context.Context, *GetFrameRequest) (*GetFrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFrame not implemented")
}
func (UnimplementedDataServiceServer) StreamVideoFrames(*StreamVideoFramesRequest, grpc.ServerStreamingServer[StreamVideoFramesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamVideoFrames not implemented")
}
func (UnimplementedDataServiceServer) StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[StreamTelemetryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetTelemetry(ctx, req.(*GetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetFrame(ctx, req.(*GetFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_StreamVideoFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamVideoFramesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).StreamVideoFrames(m, &grpc.GenericServerStream[StreamVideoFramesRequest, StreamVideoFramesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamVideoFramesServer = grpc.ServerStreamingServer[StreamVideoFramesResponse]

func _DataService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).StreamTelemetry(m, &grpc.GenericServerStream[StreamTelemetryRequest, StreamTelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamTelemetryServer = grpc.ServerStreamingServer[StreamTelemetryResponse]

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steeleagle_protocol.v1.services.vehicle.data.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResult",
			Handler:    _DataService_GetResult_Handler,
		},
		{
			MethodName: "GetTelemetry",
			Handler:    _DataService_GetTelemetry_Handler,
		},
		{
			MethodName: "GetFrame",
			Handler:    _DataService_GetFrame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVideoFrames",
			Handler:       _DataService_StreamVideoFrames_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTelemetry",
			Handler:       _DataService_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "steeleagle_protocol/v1/services/vehicle/data.proto",
}
