// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: services/control_service.proto

package services

import (
	context "context"
	common "github.com/cmusatyalab/steeleagle/tree/vehicle-go/protocol/bindings/go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Control_Connect_FullMethodName                      = "/steeleagle.protocol.services.control_service.Control/Connect"
	Control_Disconnect_FullMethodName                   = "/steeleagle.protocol.services.control_service.Control/Disconnect"
	Control_Arm_FullMethodName                          = "/steeleagle.protocol.services.control_service.Control/Arm"
	Control_Disarm_FullMethodName                       = "/steeleagle.protocol.services.control_service.Control/Disarm"
	Control_Joystick_FullMethodName                     = "/steeleagle.protocol.services.control_service.Control/Joystick"
	Control_TakeOff_FullMethodName                      = "/steeleagle.protocol.services.control_service.Control/TakeOff"
	Control_Land_FullMethodName                         = "/steeleagle.protocol.services.control_service.Control/Land"
	Control_Hold_FullMethodName                         = "/steeleagle.protocol.services.control_service.Control/Hold"
	Control_Kill_FullMethodName                         = "/steeleagle.protocol.services.control_service.Control/Kill"
	Control_SetHome_FullMethodName                      = "/steeleagle.protocol.services.control_service.Control/SetHome"
	Control_ReturnToHome_FullMethodName                 = "/steeleagle.protocol.services.control_service.Control/ReturnToHome"
	Control_SetGlobalPosition_FullMethodName            = "/steeleagle.protocol.services.control_service.Control/SetGlobalPosition"
	Control_SetRelativePosition_FullMethodName          = "/steeleagle.protocol.services.control_service.Control/SetRelativePosition"
	Control_SetVelocity_FullMethodName                  = "/steeleagle.protocol.services.control_service.Control/SetVelocity"
	Control_SetHeading_FullMethodName                   = "/steeleagle.protocol.services.control_service.Control/SetHeading"
	Control_SetGimbalPose_FullMethodName                = "/steeleagle.protocol.services.control_service.Control/SetGimbalPose"
	Control_SetGimbalPoseTarget_FullMethodName          = "/steeleagle.protocol.services.control_service.Control/SetGimbalPoseTarget"
	Control_ConfigureImagingSensorStream_FullMethodName = "/steeleagle.protocol.services.control_service.Control/ConfigureImagingSensorStream"
	Control_ConfigureTelemetryStream_FullMethodName     = "/steeleagle.protocol.services.control_service.Control/ConfigureTelemetryStream"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Used for low-level control of a vehicle.
//
// This service is hosted by the driver module and represents the global
// control interface for the vehicle. Most methods called here will result
// in actuation of the vehicle if it is armed (be careful!). Some methods,
// like TakeOff, may take some time to complete. For this reason, it is
// not advisable to set a timeout/deadline on the RPC call. However, to
// ensure that the service is progressing, a client can either check
// telemetry or listen for `IN_PROGRESS` response heartbeats which are
// streamed back from the RPC while executing an operation.
type ControlClient interface {
	// Connect to the vehicle.
	//
	// Connects to the underlying vehicle hardware. Generally, this
	// method is called by the law authority on startup and is not
	// called by user code.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Disconnect from the vehicle.
	//
	// Disconnects from the underlying vehicle hardware. Generally,
	// this method is called by the law authority when it attempts
	// a driver restart and is not called by user code.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Order the vehicle to arm.
	//
	// Arms the vehicle. This is required before any other commands
	// are run, otherwise the methods will return `FAILED_PRECONDITION`.
	// Once the vehicle is armed, all subsequent actuation methods
	// _will move the vehicle_. Make sure to go over the manufacturer
	// recommended vehicle-specific pre-operation checklist before arming.
	Arm(ctx context.Context, in *ArmRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Order the vehicle to disarm.
	//
	// Disarms the vehicle. Prevents any further actuation methods
	// from executing, unless the vehicle is re-armed.
	Disarm(ctx context.Context, in *DisarmRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Send a joystick command to the vehicle.
	//
	// Causes the vehicle to accelerate towards a provided velocity
	// setpoint over a provided duration. This is useful for fine-grained
	// control based on streamed datasink results or for tele-operating
	// the vehicle from a remote commander.
	Joystick(ctx context.Context, in *JoystickRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Order the vehicle to take off.
	//
	// Causes the vehicle to take off to a specified take off altitude.
	// If the vehicle is not a UAV, this method will be unimplemented.
	TakeOff(ctx context.Context, in *TakeOffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to land.
	//
	// Causes the vehicle to land at its current location. If the
	// vehicle is not a UAV, this method will be unimplemented.
	Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to hold/loiter.
	//
	// Causes the vehicle to hold at its current location and to
	// cancel any ongoing movement commands (`ReturnToHome` e.g.).
	Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Orders an emergency shutdown of the vehicle motors.
	//
	// Causes the vehicle to immediately turn off its motors. _If the
	// vehicle is a UAV, this will result in a freefall_. Use this
	// method only in emergency situations.
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Set the home location of the vehicle.
	//
	// Changes the home location of the vehicle. Future `ReturnToHome`
	// commands will move the vehicle to the provided location instead
	// of its starting position.
	SetHome(ctx context.Context, in *SetHomeRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Order the vehicle to return to its home position.
	//
	// Causes the vehicle to return to its home position. If the home position
	// has not been explicitly set, this will be its start position (defined
	// as its takeoff position for UAVs). If the home position has been
	// explicitly set, by `SetHome`, the vehicle will return to that
	// position instead.
	ReturnToHome(ctx context.Context, in *ReturnToHomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to move to a global position.
	//
	// Causes the vehicle to transit to the provided global position. The vehicle
	// will interpret the heading of travel according to `heading_mode`:
	// - `TO_TARGET` -> turn to face the target position bearing
	// - `HEADING_START` -> turn to face the provided heading in the global position object.
	//
	// This will be the heading the vehicle maintains for the duration of transit.
	// Generally only UAVs will support `HEADING_START`.
	//
	// The vehicle will move towards the target at the specified maximum velocity
	// until the vehicle has reached its destination. Error tolerance is determined
	// by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
	// - `x_vel` -> maximum _horizontal_ velocity
	// - `y_vel` -> ignored
	// - `z_vel` -> maximum _vertical_ velocity _(UAV only)_
	//
	// If no maximum velocity is provided, the driver will use a preset speed usually
	// determined by the manufacturer or hardware settings.
	//
	// _(UAV only)_ During motion, the vehicle will also ascend or descend towards the
	// target altitude, linearly interpolating this movement over the duration of
	// travel. The vehicle will interpret altitude from `altitude_mode` as follows:
	// - `ABSOLUTE` -> altitude is relative to MSL (Mean Sea Level)
	// - `RELATIVE` -> altitude is relative to take off position
	SetGlobalPosition(ctx context.Context, in *SetGlobalPositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to move to a relative position.
	//
	// Causes the vehicle to transit to the provided relative position. The vehicle
	// will interpret the input position according to `frame` as follows:
	// - `BODY` -> (`x`, `y`, `z`) = (forward offset, right offset, up offset) _from current position_
	// - `NEU` -> (`x`, `y`, `z`) = (north offset, east offset, up offset) _from start position_
	//
	// The vehicle will move towards the target at the specified maximum velocity
	// until the vehicle has reached its destination. Error tolerance is determined
	// by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
	// - `x_vel` -> maximum _horizontal_ velocity
	// - `y_vel` -> ignored
	// - `z_vel` -> maximum _vertical_ velocity _(UAV only)_
	//
	// If no maximum velocity is provided, the driver will use a preset speed usually
	// determined by the manufacturer or hardware settings.
	SetRelativePosition(ctx context.Context, in *SetRelativePositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to accelerate to a velocity.
	//
	// Causes the vehicle to accelerate until it reaches a provided velocity.
	// Error tolerance is determined by the driver. The vehicle will interpret
	// the input velocity according to `frame` as follows:
	// - `BODY` -> (`x_vel`, `y_vel`, `z_vel`) = (forward velocity, right velocity, up velocity)
	// - `NEU` -> (`x_vel`, `y_vel`, `z_vel`) = (north velocity, east velocity, up velocity)
	SetVelocity(ctx context.Context, in *SetVelocityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to set a new heading.
	//
	// Causes the vehicle to turn to face the provided global position. The vehicle
	// will interpret the final heading according to `heading_mode`:
	// - `TO_TARGET` -> turn to face the target position bearing
	// - `HEADING_START` -> turn to face the provided heading in the global position object.
	SetHeading(ctx context.Context, in *SetHeadingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to set the pose of a gimbal.
	//
	// Causes the vehicle to actuate a gimbal to a new pose. The vehicle
	// will interpret the new pose type from `pose_mode` as follows:
	// - `ABSOLUTE` -> absolute angle
	// - `RELATIVE` -> angle relative to current position
	// - `VELOCITY` -> angular velocities
	//
	// The vehicle will interpret the new pose angles according to `frame`
	// as follows:
	// - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
	// - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
	SetGimbalPose(ctx context.Context, in *SetGimbalPoseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error)
	// Order the vehicle to set the pose of a gimbal asynchronously.
	//
	// Causes the vehicle to actuate a gimbal to a new pose. The vehicle
	// will interpret the new pose type from `pose_mode` as follows:
	// - `ABSOLUTE` -> absolute angle
	// - `RELATIVE` -> angle relative to current position
	// - `VELOCITY` -> angular velocities
	//
	// The vehicle will interpret the new pose angles according to `frame`
	// as follows:
	// - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
	// - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
	SetGimbalPoseTarget(ctx context.Context, in *SetGimbalPoseTargetRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Configure the vehicle imaging stream.
	//
	// Sets which imaging sensors are streaming and sets their target
	// frame rates.
	ConfigureImagingSensorStream(ctx context.Context, in *ConfigureImagingSensorStreamRequest, opts ...grpc.CallOption) (*common.Response, error)
	// Configure the vehicle telemetry stream.
	//
	// Sets the frequency of the telemetry stream.
	ConfigureTelemetryStream(ctx context.Context, in *ConfigureTelemetryStreamRequest, opts ...grpc.CallOption) (*common.Response, error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Arm(ctx context.Context, in *ArmRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_Arm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Disarm(ctx context.Context, in *DisarmRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_Disarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Joystick(ctx context.Context, in *JoystickRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_Joystick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) TakeOff(ctx context.Context, in *TakeOffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[0], Control_TakeOff_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TakeOffRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_TakeOffClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[1], Control_Land_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LandRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_LandClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[2], Control_Hold_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HoldRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_HoldClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[3], Control_Kill_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KillRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_KillClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetHome(ctx context.Context, in *SetHomeRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_SetHome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ReturnToHome(ctx context.Context, in *ReturnToHomeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[4], Control_ReturnToHome_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReturnToHomeRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_ReturnToHomeClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetGlobalPosition(ctx context.Context, in *SetGlobalPositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[5], Control_SetGlobalPosition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetGlobalPositionRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetGlobalPositionClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetRelativePosition(ctx context.Context, in *SetRelativePositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[6], Control_SetRelativePosition_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetRelativePositionRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetRelativePositionClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetVelocity(ctx context.Context, in *SetVelocityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[7], Control_SetVelocity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetVelocityRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetVelocityClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetHeading(ctx context.Context, in *SetHeadingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[8], Control_SetHeading_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetHeadingRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetHeadingClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetGimbalPose(ctx context.Context, in *SetGimbalPoseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[9], Control_SetGimbalPose_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetGimbalPoseRequest, common.Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetGimbalPoseClient = grpc.ServerStreamingClient[common.Response]

func (c *controlClient) SetGimbalPoseTarget(ctx context.Context, in *SetGimbalPoseTargetRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_SetGimbalPoseTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ConfigureImagingSensorStream(ctx context.Context, in *ConfigureImagingSensorStreamRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_ConfigureImagingSensorStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ConfigureTelemetryStream(ctx context.Context, in *ConfigureTelemetryStreamRequest, opts ...grpc.CallOption) (*common.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Response)
	err := c.cc.Invoke(ctx, Control_ConfigureTelemetryStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// Used for low-level control of a vehicle.
//
// This service is hosted by the driver module and represents the global
// control interface for the vehicle. Most methods called here will result
// in actuation of the vehicle if it is armed (be careful!). Some methods,
// like TakeOff, may take some time to complete. For this reason, it is
// not advisable to set a timeout/deadline on the RPC call. However, to
// ensure that the service is progressing, a client can either check
// telemetry or listen for `IN_PROGRESS` response heartbeats which are
// streamed back from the RPC while executing an operation.
type ControlServer interface {
	// Connect to the vehicle.
	//
	// Connects to the underlying vehicle hardware. Generally, this
	// method is called by the law authority on startup and is not
	// called by user code.
	Connect(context.Context, *ConnectRequest) (*common.Response, error)
	// Disconnect from the vehicle.
	//
	// Disconnects from the underlying vehicle hardware. Generally,
	// this method is called by the law authority when it attempts
	// a driver restart and is not called by user code.
	Disconnect(context.Context, *DisconnectRequest) (*common.Response, error)
	// Order the vehicle to arm.
	//
	// Arms the vehicle. This is required before any other commands
	// are run, otherwise the methods will return `FAILED_PRECONDITION`.
	// Once the vehicle is armed, all subsequent actuation methods
	// _will move the vehicle_. Make sure to go over the manufacturer
	// recommended vehicle-specific pre-operation checklist before arming.
	Arm(context.Context, *ArmRequest) (*common.Response, error)
	// Order the vehicle to disarm.
	//
	// Disarms the vehicle. Prevents any further actuation methods
	// from executing, unless the vehicle is re-armed.
	Disarm(context.Context, *DisarmRequest) (*common.Response, error)
	// Send a joystick command to the vehicle.
	//
	// Causes the vehicle to accelerate towards a provided velocity
	// setpoint over a provided duration. This is useful for fine-grained
	// control based on streamed datasink results or for tele-operating
	// the vehicle from a remote commander.
	Joystick(context.Context, *JoystickRequest) (*common.Response, error)
	// Order the vehicle to take off.
	//
	// Causes the vehicle to take off to a specified take off altitude.
	// If the vehicle is not a UAV, this method will be unimplemented.
	TakeOff(*TakeOffRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to land.
	//
	// Causes the vehicle to land at its current location. If the
	// vehicle is not a UAV, this method will be unimplemented.
	Land(*LandRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to hold/loiter.
	//
	// Causes the vehicle to hold at its current location and to
	// cancel any ongoing movement commands (`ReturnToHome` e.g.).
	Hold(*HoldRequest, grpc.ServerStreamingServer[common.Response]) error
	// Orders an emergency shutdown of the vehicle motors.
	//
	// Causes the vehicle to immediately turn off its motors. _If the
	// vehicle is a UAV, this will result in a freefall_. Use this
	// method only in emergency situations.
	Kill(*KillRequest, grpc.ServerStreamingServer[common.Response]) error
	// Set the home location of the vehicle.
	//
	// Changes the home location of the vehicle. Future `ReturnToHome`
	// commands will move the vehicle to the provided location instead
	// of its starting position.
	SetHome(context.Context, *SetHomeRequest) (*common.Response, error)
	// Order the vehicle to return to its home position.
	//
	// Causes the vehicle to return to its home position. If the home position
	// has not been explicitly set, this will be its start position (defined
	// as its takeoff position for UAVs). If the home position has been
	// explicitly set, by `SetHome`, the vehicle will return to that
	// position instead.
	ReturnToHome(*ReturnToHomeRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to move to a global position.
	//
	// Causes the vehicle to transit to the provided global position. The vehicle
	// will interpret the heading of travel according to `heading_mode`:
	// - `TO_TARGET` -> turn to face the target position bearing
	// - `HEADING_START` -> turn to face the provided heading in the global position object.
	//
	// This will be the heading the vehicle maintains for the duration of transit.
	// Generally only UAVs will support `HEADING_START`.
	//
	// The vehicle will move towards the target at the specified maximum velocity
	// until the vehicle has reached its destination. Error tolerance is determined
	// by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
	// - `x_vel` -> maximum _horizontal_ velocity
	// - `y_vel` -> ignored
	// - `z_vel` -> maximum _vertical_ velocity _(UAV only)_
	//
	// If no maximum velocity is provided, the driver will use a preset speed usually
	// determined by the manufacturer or hardware settings.
	//
	// _(UAV only)_ During motion, the vehicle will also ascend or descend towards the
	// target altitude, linearly interpolating this movement over the duration of
	// travel. The vehicle will interpret altitude from `altitude_mode` as follows:
	// - `ABSOLUTE` -> altitude is relative to MSL (Mean Sea Level)
	// - `RELATIVE` -> altitude is relative to take off position
	SetGlobalPosition(*SetGlobalPositionRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to move to a relative position.
	//
	// Causes the vehicle to transit to the provided relative position. The vehicle
	// will interpret the input position according to `frame` as follows:
	// - `BODY` -> (`x`, `y`, `z`) = (forward offset, right offset, up offset) _from current position_
	// - `NEU` -> (`x`, `y`, `z`) = (north offset, east offset, up offset) _from start position_
	//
	// The vehicle will move towards the target at the specified maximum velocity
	// until the vehicle has reached its destination. Error tolerance is determined
	// by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
	// - `x_vel` -> maximum _horizontal_ velocity
	// - `y_vel` -> ignored
	// - `z_vel` -> maximum _vertical_ velocity _(UAV only)_
	//
	// If no maximum velocity is provided, the driver will use a preset speed usually
	// determined by the manufacturer or hardware settings.
	SetRelativePosition(*SetRelativePositionRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to accelerate to a velocity.
	//
	// Causes the vehicle to accelerate until it reaches a provided velocity.
	// Error tolerance is determined by the driver. The vehicle will interpret
	// the input velocity according to `frame` as follows:
	// - `BODY` -> (`x_vel`, `y_vel`, `z_vel`) = (forward velocity, right velocity, up velocity)
	// - `NEU` -> (`x_vel`, `y_vel`, `z_vel`) = (north velocity, east velocity, up velocity)
	SetVelocity(*SetVelocityRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to set a new heading.
	//
	// Causes the vehicle to turn to face the provided global position. The vehicle
	// will interpret the final heading according to `heading_mode`:
	// - `TO_TARGET` -> turn to face the target position bearing
	// - `HEADING_START` -> turn to face the provided heading in the global position object.
	SetHeading(*SetHeadingRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to set the pose of a gimbal.
	//
	// Causes the vehicle to actuate a gimbal to a new pose. The vehicle
	// will interpret the new pose type from `pose_mode` as follows:
	// - `ABSOLUTE` -> absolute angle
	// - `RELATIVE` -> angle relative to current position
	// - `VELOCITY` -> angular velocities
	//
	// The vehicle will interpret the new pose angles according to `frame`
	// as follows:
	// - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
	// - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
	SetGimbalPose(*SetGimbalPoseRequest, grpc.ServerStreamingServer[common.Response]) error
	// Order the vehicle to set the pose of a gimbal asynchronously.
	//
	// Causes the vehicle to actuate a gimbal to a new pose. The vehicle
	// will interpret the new pose type from `pose_mode` as follows:
	// - `ABSOLUTE` -> absolute angle
	// - `RELATIVE` -> angle relative to current position
	// - `VELOCITY` -> angular velocities
	//
	// The vehicle will interpret the new pose angles according to `frame`
	// as follows:
	// - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
	// - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
	SetGimbalPoseTarget(context.Context, *SetGimbalPoseTargetRequest) (*common.Response, error)
	// Configure the vehicle imaging stream.
	//
	// Sets which imaging sensors are streaming and sets their target
	// frame rates.
	ConfigureImagingSensorStream(context.Context, *ConfigureImagingSensorStreamRequest) (*common.Response, error)
	// Configure the vehicle telemetry stream.
	//
	// Sets the frequency of the telemetry stream.
	ConfigureTelemetryStream(context.Context, *ConfigureTelemetryStreamRequest) (*common.Response, error)
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) Connect(context.Context, *ConnectRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedControlServer) Disconnect(context.Context, *DisconnectRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedControlServer) Arm(context.Context, *ArmRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Arm not implemented")
}
func (UnimplementedControlServer) Disarm(context.Context, *DisarmRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Disarm not implemented")
}
func (UnimplementedControlServer) Joystick(context.Context, *JoystickRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Joystick not implemented")
}
func (UnimplementedControlServer) TakeOff(*TakeOffRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method TakeOff not implemented")
}
func (UnimplementedControlServer) Land(*LandRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method Land not implemented")
}
func (UnimplementedControlServer) Hold(*HoldRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method Hold not implemented")
}
func (UnimplementedControlServer) Kill(*KillRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedControlServer) SetHome(context.Context, *SetHomeRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHome not implemented")
}
func (UnimplementedControlServer) ReturnToHome(*ReturnToHomeRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method ReturnToHome not implemented")
}
func (UnimplementedControlServer) SetGlobalPosition(*SetGlobalPositionRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method SetGlobalPosition not implemented")
}
func (UnimplementedControlServer) SetRelativePosition(*SetRelativePositionRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method SetRelativePosition not implemented")
}
func (UnimplementedControlServer) SetVelocity(*SetVelocityRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method SetVelocity not implemented")
}
func (UnimplementedControlServer) SetHeading(*SetHeadingRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method SetHeading not implemented")
}
func (UnimplementedControlServer) SetGimbalPose(*SetGimbalPoseRequest, grpc.ServerStreamingServer[common.Response]) error {
	return status.Error(codes.Unimplemented, "method SetGimbalPose not implemented")
}
func (UnimplementedControlServer) SetGimbalPoseTarget(context.Context, *SetGimbalPoseTargetRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGimbalPoseTarget not implemented")
}
func (UnimplementedControlServer) ConfigureImagingSensorStream(context.Context, *ConfigureImagingSensorStreamRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureImagingSensorStream not implemented")
}
func (UnimplementedControlServer) ConfigureTelemetryStream(context.Context, *ConfigureTelemetryStreamRequest) (*common.Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureTelemetryStream not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Arm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Arm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Arm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Arm(ctx, req.(*ArmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Disarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Disarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Disarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Disarm(ctx, req.(*DisarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Joystick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoystickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Joystick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Joystick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Joystick(ctx, req.(*JoystickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_TakeOff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TakeOffRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).TakeOff(m, &grpc.GenericServerStream[TakeOffRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_TakeOffServer = grpc.ServerStreamingServer[common.Response]

func _Control_Land_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).Land(m, &grpc.GenericServerStream[LandRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_LandServer = grpc.ServerStreamingServer[common.Response]

func _Control_Hold_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HoldRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).Hold(m, &grpc.GenericServerStream[HoldRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_HoldServer = grpc.ServerStreamingServer[common.Response]

func _Control_Kill_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KillRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).Kill(m, &grpc.GenericServerStream[KillRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_KillServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SetHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SetHome(ctx, req.(*SetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ReturnToHome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReturnToHomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).ReturnToHome(m, &grpc.GenericServerStream[ReturnToHomeRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_ReturnToHomeServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetGlobalPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetGlobalPositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).SetGlobalPosition(m, &grpc.GenericServerStream[SetGlobalPositionRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetGlobalPositionServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetRelativePosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetRelativePositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).SetRelativePosition(m, &grpc.GenericServerStream[SetRelativePositionRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetRelativePositionServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetVelocity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetVelocityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).SetVelocity(m, &grpc.GenericServerStream[SetVelocityRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetVelocityServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetHeading_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetHeadingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).SetHeading(m, &grpc.GenericServerStream[SetHeadingRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetHeadingServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetGimbalPose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetGimbalPoseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).SetGimbalPose(m, &grpc.GenericServerStream[SetGimbalPoseRequest, common.Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_SetGimbalPoseServer = grpc.ServerStreamingServer[common.Response]

func _Control_SetGimbalPoseTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGimbalPoseTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SetGimbalPoseTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SetGimbalPoseTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SetGimbalPoseTarget(ctx, req.(*SetGimbalPoseTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ConfigureImagingSensorStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureImagingSensorStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ConfigureImagingSensorStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ConfigureImagingSensorStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ConfigureImagingSensorStream(ctx, req.(*ConfigureImagingSensorStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ConfigureTelemetryStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureTelemetryStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ConfigureTelemetryStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ConfigureTelemetryStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ConfigureTelemetryStream(ctx, req.(*ConfigureTelemetryStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steeleagle.protocol.services.control_service.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Control_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Control_Disconnect_Handler,
		},
		{
			MethodName: "Arm",
			Handler:    _Control_Arm_Handler,
		},
		{
			MethodName: "Disarm",
			Handler:    _Control_Disarm_Handler,
		},
		{
			MethodName: "Joystick",
			Handler:    _Control_Joystick_Handler,
		},
		{
			MethodName: "SetHome",
			Handler:    _Control_SetHome_Handler,
		},
		{
			MethodName: "SetGimbalPoseTarget",
			Handler:    _Control_SetGimbalPoseTarget_Handler,
		},
		{
			MethodName: "ConfigureImagingSensorStream",
			Handler:    _Control_ConfigureImagingSensorStream_Handler,
		},
		{
			MethodName: "ConfigureTelemetryStream",
			Handler:    _Control_ConfigureTelemetryStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TakeOff",
			Handler:       _Control_TakeOff_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Land",
			Handler:       _Control_Land_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Hold",
			Handler:       _Control_Hold_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Kill",
			Handler:       _Control_Kill_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReturnToHome",
			Handler:       _Control_ReturnToHome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetGlobalPosition",
			Handler:       _Control_SetGlobalPosition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetRelativePosition",
			Handler:       _Control_SetRelativePosition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetVelocity",
			Handler:       _Control_SetVelocity_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetHeading",
			Handler:       _Control_SetHeading_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetGimbalPose",
			Handler:       _Control_SetGimbalPose_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/control_service.proto",
}
