// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.services.driver;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/driver;driver";

import "steeleagle_protocol/v1/common/common.proto";
import "steeleagle_protocol/v1/messages/telemetry/telemetry.proto";

/*
 * Used for low-level control of the driver.
 *
 * This service provides a setpoint control interface for the driver. Each
 * command creates a target setpoint for the device, which will then cause the
 * device to actuate toward the setpoint until command completion. Each command
 * will:
 * - [Action/Guidance/Gimbal] Clear the `setpoint`/`gimbal_setpoint` field in Telemetry
 * - [Guidance/Gimbal] Return a `setpoint`/`gimbal_setpoint` in NEU frame
 * - [Guidance/Gimbal] Set the `setpoint`/`gimbal_setpoint` Telemetry field to be `setpoint`/`gimbal_setpoint`
 * - [Action/Guidance] Return an `expected_mode` which is the expected end-state Mode
 * - [Action/Guidance] Return an `expected_status` which is the expected end-state MotionStatus
 * - [Action/Guidance] Set the `mode` field in the vehicle telemetry
 *
 * These commands will result in actuation of the device if it is active (be careful!).
 */
service ControlService {
  /*
   * Order the vehicle to take off _(Action)_.
   *
   * Causes the vehicle to take off to a specified take off altitude.
   * Implicitly arms the vehicle.
   *
   * Returns an _Action_ style response with `expected_mode` set to LOITER
   * and `expected_status` set to `MOTION_STATUS_HOLDING`.
   */
  rpc TakeOff (TakeOffRequest)
	returns (TakeOffResponse) {}
  /*
   * Order the vehicle to land _(Action)_.
   *
   * Causes the vehicle to land at its current location. Implicitly
   * disarms the vehicle.
   *
   * Returns an _Action_ style response with `expected_mode` set to LAND
   * and `expected_status` set to `MOTION_STATUS_STOPPED`.
   */
  rpc Land (LandRequest)
	returns (LandResponse) {}
  /*
   * Order the vehicle to hold/loiter _(Action)_.
   *
   * Causes the vehicle to hold at its current location and to
   * cancel any ongoing movement commands (`ReturnToHome` e.g.).
   *
   * Returns an _Action_ style response with `expected_mode` set to LOITER
   * and `expected_status` set to `MOTION_STATUS_HOLDING`.
   */
  rpc Hold (HoldRequest)
	returns (HoldResponse) {}
  /*
   * Orders an emergency shutdown of the vehicle motors _(Action)_.
   *
   * Causes the vehicle to immediately turn off its motors. _This will
   * result in the vehicle going into freefall, only for emergencies!_
   *
   * Returns an _Action_ style response with `expected_mode` set to EMERGENCY
   * and `expected_status` set to `MOTION_STATUS_STOPPED`.
   */
  rpc Kill (KillRequest)
	returns (KillResponse) {}
  /*
   * Order the vehicle to return to its home position _(Action)_.
   *
   * Causes the vehicle to return to its home position. If the home position
   * has not been explicitly set, this will be its start position (defined
   * as its takeoff position by default). If the home position has been
   * explicitly set, by `SetHome`, the vehicle will return to that
   * position instead. If `return_altitude` is set, the vehicle will ascend
   * to that altitude before transit.
   *
   * The vehicle will interpret `end_behavior` as follows:
   * - `HOVER` -> hover at `final_altitude` above home position
   * - `LAND` -> land at home position
   *
   * Returns an _Action_ style response with `expected_mode` set to either LOITER 
   * or LAND and `expected_status` set to `MOTION_STATUS_HOLDING` or 
   * `MOTION_STATUS_STOPPED`.
   */
  rpc ReturnToHome (ReturnToHomeRequest)
	returns (ReturnToHomeResponse) {}
  /*
   * Order the device to move to a global position target _(Guidance)_.
   *
   * Causes the device to transit to the provided `GlobalPosition`. The device
   * will interpret the heading of travel according to `heading_mode`:
   * - `TO_TARGET` -> turn to face the target position bearing (`heading` of `GlobalPosition` is ignored)
   * - `HEADING_START` -> turn to face the provided `heading` in `GlobalPosition`
   *
   * This will be the heading the device maintains for the duration of transit.
   *
   * The device will move towards the target at the specified `speed` and turn at
   * the specified `angular_speed` until the device has reached its destination.
   * If neither are provided, the device will choose hardware defaults.
   *
   * During motion, the device will also ascend or descend towards the target
   * altitude, linearly interpolating this movement over the duration of travel.
   * The device will interpret altitude from `altitude_mode` as follows:
   * - `ABSOLUTE` -> altitude is relative to MSL (Mean Sea Level)
   * - `RELATIVE` -> altitude is relative to take off position
   *
   * An unspecified `altitude_mode` will default to `ABSOLUTE`, unless this is unsupported
   * in which case it will default to `RELATIVE`.
   *
   * Returns a _Guidance_ style response, with `setpoint` set to the target `GlobalPosition`
   * and `expected_status` set to `MOTION_STATUS_HOLDING`.
   */
  rpc SetGlobalPositionTarget (SetGlobalPositionTargetRequest)
	returns (SetGlobalPositionTargetResponse) {}
  /*
   * Order the device to move to a relative position target _(Guidance)_.
   *
   * Causes the device to transit to the provided `RelativePosition`. The device
   * will interpret the input position according to `frame` as follows:
   * - `BODY` -> (`x`, `y`, `z`, `angle`) = (forward offset, right offset, up offset, angle offset) _from current position_
   * - `NEU` -> (`x`, `y`, `z`, `angle`) = (north offset, east offset, up offset, absolute heading) _from start position_
   *
   * The device will move towards the target at the specified `speed` and turn at
   * the specified `angular_speed` until the device has reached its destination.
   * If neither are provided, the device will choose hardware defaults.
   *
   * Returns a _Guidance_ style response with `setpoint` set to the target `RelativePosition` in
   * the NEU frame, and `expected_status` set to `MOTION_STATUS_HOLDING`.
   */
  rpc SetRelativePositionTarget (SetRelativePositionTargetRequest)
	returns (SetRelativePositionTargetResponse) {}
  /*
   * Order the device to accelerate to a velocity target _(Guidance)_.
   *
   * Causes the device to accelerate until it reaches a provided velocity.
   * The device will interpret the input velocity according to `frame` as follows:
   * - `BODY` -> (`x_vel`, `y_vel`, `z_vel`) = (forward velocity, right velocity, up velocity)
   * - `NEU` -> (`x_vel`, `y_vel`, `z_vel`) = (north velocity, east velocity, up velocity)
   *
   * Returns a _Guidance_ style response, with `setpoint` set to the target `Velocity` in
   * the NEU frame, and `expected_status` set to `MOTION_STATUS_IN_TRANSIT`.
   */
  rpc SetVelocityTarget (SetVelocityTargetRequest)
	returns (SetVelocityTargetResponse) {}
  /*
   * Order the device to set the angle pose of the gimbal _(Gimbal)_.
   *
   * The device will interpret the new pose angles according to `frame`
   * as follows:
   * - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
   * - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
   * 
   * Returns a _Gimbal_ style response, with `setpoint` set to the target `Pose` in
   * the NEU frame.
   */
  rpc SetGimbalAngleTarget (SetGimbalAngleTargetRequest)
	returns (SetGimbalAngleTargetResponse) {}
  /*
   * Order the device to set the velocity of the gimbal _(Gimbal)_.
   *
   * The device will interpret the new pose angles according to `frame`
   * as follows:
   * - `BODY` -> (`pitch_vel`, `roll_vel`, `yaw_vel`) = (body pitch velocity, body roll velocity, body yaw velocity)
   * - `NEU` -> (`pitch_vel`, `roll_vel`, `yaw_vel`) = (body pitch velocity, body roll velocity, global yaw velocity)
   *
   * Returns a _Gimbal_ style response, with `setpoint` set to the target `PoseVelocity` in
   * the NEU frame.
   */
  rpc SetGimbalVelocityTarget (SetGimbalVelocityTargetRequest)
	returns (SetGimbalVelocityTargetResponse) {}
}

// ReturnToHome mode switch.
enum ReturnToHomeEndBehavior {
  RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED = 0; // defaults to `HOVER`
  RETURN_TO_HOME_END_BEHAVIOR_HOVER = 1; // hover upon return to home
  RETURN_TO_HOME_END_BEHAVIOR_LAND = 2; // land upon return to home
}

// Altitude mode switch.
enum AltitudeMode {
  ALTITUDE_MODE_UNSPECIFIED = 0; // defaults to `RELATIVE`
  ALTITUDE_MODE_RELATIVE = 1; // meters above takeoff position
  ALTITUDE_MODE_ABSOLUTE = 2; // meters above Mean Sea Level
}

// Heading mode switch.
enum HeadingMode {
  HEADING_MODE_UNSPECIFIED = 0; // defaults to `TO_TARGET`
  HEADING_MODE_TO_TARGET = 1; // orient towards the target location
  HEADING_MODE_START = 2; // orient towards the given heading
}

// Reference frame mode switch.
enum ReferenceFrame {
  REFERENCE_FRAME_UNSPECIFIED = 0; // defaults to `BODY`
  REFERENCE_FRAME_BODY = 1; // device reference frame
  REFERENCE_FRAME_NEU = 2; // NEU (North, East, Up) reference frame
}

// Angle mode switch.
enum AngleMode {
  ANGLE_MODE_UNSPECIFIED = 0; // defaults to `ABSOLUTE`
  ANGLE_MODE_ABSOLUTE = 1; // absolute angle
  ANGLE_MODE_OFFSET = 2; // offset from current
}

message TakeOffRequest {
  // take off height in relative altitude [meters]
  optional float altitude = 1;
}

message TakeOffResponse {
  steeleagle_protocol.v1.messages.telemetry.Mode expected_mode = 1; // flight mode expectation
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message LandRequest {}

message LandResponse {
  steeleagle_protocol.v1.messages.telemetry.Mode expected_mode = 1; // flight mode expectation
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message HoldRequest {}

message HoldResponse {
  steeleagle_protocol.v1.messages.telemetry.Mode expected_mode = 1; // flight mode expectation
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message KillRequest {}

message KillResponse {
  steeleagle_protocol.v1.messages.telemetry.Mode expected_mode = 1; // flight mode expectation
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message ReturnToHomeRequest {
  // what the vehicle should do after returning home
  ReturnToHomeEndBehavior end_behavior = 1;
  // minimum altitude that the vehicle should move at while reurning home
  float min_return_altitude = 2;
  // altitude that the vehicle should hover AGL (above ground level), for hover end behavior
  float final_altitude = 3;
}

message ReturnToHomeResponse {
  steeleagle_protocol.v1.messages.telemetry.Mode expected_mode = 1; // flight mode expectation
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message SetGlobalPositionTargetRequest {
  common.GlobalPosition position = 1; // target global position
  // determines how the device will orient during transit (default: `TO_TARGET`)
  optional HeadingMode heading_mode = 2;
  // determines how the device will interpret altitude (default: `ABSOLUTE`)
  optional AltitudeMode altitude_mode = 3;
  // speed during transit
  optional float speed = 4;
  // angular speed during transit
  optional float angular_speed = 5;
}

message SetGlobalPositionTargetResponse {
  common.GlobalPosition setpoint = 1; // global position setpoint for the request
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message SetRelativePositionTargetRequest {
  // target relative position
  common.RelativePosition position = 1;
  // speed during transit
  optional float speed = 2;
  // angular speed during transit
  optional float angular_speed = 3;
  // frame of reference
  optional ReferenceFrame frame = 4;
}

message SetRelativePositionTargetResponse {
  // relative position setpoint for the request (converted to NEU)
  common.RelativePosition setpoint = 1;
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message SetVelocityTargetRequest {
  // target velocity
  common.Velocity velocity = 1;
  // frame of reference
  optional ReferenceFrame frame = 2;
}

message SetVelocityTargetResponse {
  common.Velocity setpoint = 1; // velocity setpoint for the request (converted to NEU)
  steeleagle_protocol.v1.messages.telemetry.MotionStatus expected_status = 2; // motion status expectation
}

message SetGimbalAngleTargetRequest {
  common.Pose pose = 1; // target pose
  optional AngleMode angle_mode = 2; // specifies how to interpret the target pose
  optional ReferenceFrame frame = 3; // frame of reference
}

message SetGimbalAngleTargetResponse {
  common.Pose setpoint = 1; // absolute angle pose setpoint for the request (NEU frame)
}

message SetGimbalVelocityTargetRequest {
  common.PoseVelocity pose_velocity = 1; // target pose velocity
  optional ReferenceFrame frame = 2; // frame of reference
}

message SetGimbalVelocityTargetResponse {
  common.PoseVelocity setpoint = 1; // absolute angle pose setpoint for the request (NEU frame)
}
