// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.services.driver.control;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/driver/control;control";

import "steeleagle_protocol/v1/common.proto";

/*
 * Used for low-level control of a vehicle.
 *
 * This service is hosted by the driver module and represents the global
 * control interface for the vehicle. Most methods called here will result
 * in actuation of the vehicle if it is armed (be careful!).
 */
service ControlService {
  /*
   * Order the vehicle to take off.
   *
   * Causes the vehicle to take off to a specified take off altitude.
   * Implicitly arms the vehicle.
   */
  rpc TakeOff (TakeOffRequest)
	returns (TakeOffResponse) {}
  /*
   * Order the vehicle to land.
   *
   * Causes the vehicle to land at its current location. Implicitly
   * disarms the vehicle.
   */
  rpc Land (LandRequest)
	returns (LandResponse) {}
  /*
   * Order the vehicle to hold/loiter.
   *
   * Causes the vehicle to hold at its current location and to
   * cancel any ongoing movement commands (`ReturnToHome` e.g.).
   */
  rpc Hold (HoldRequest)
	returns (HoldResponse) {}
  /*
   * Orders an emergency shutdown of the vehicle motors.
   *
   * Causes the vehicle to immediately turn off its motors. _This will
   * result in the vehicle going into freefall, only for emergencies!_
   */
  rpc Kill (KillRequest)
	returns (KillResponse) {}
  /*
   * Set the home location of the vehicle.
   *
   * Changes the home location of the vehicle. Future `ReturnToHome`
   * commands will move the vehicle to the provided location instead
   * of its starting position.
   */
  rpc SetHome (SetHomeRequest)
	returns (SetHomeResponse) {}
  /*
   * Order the vehicle to return to its home position.
   *
   * Causes the vehicle to return to its home position. If the home position
   * has not been explicitly set, this will be its start position (defined
   * as its takeoff position by default). If the home position has been
   * explicitly set, by `SetHome`, the vehicle will return to that
   * position instead. If `return_altitude` is set, the vehicle will ascend
   * to that altitude before transit.
   *
   * The vehicle will interpret `end_behavior` as follows:
   * - `HOVER` -> hover at `final_altitude` above home position
   * - `LAND` -> land at home position
   */
  rpc ReturnToHome (ReturnToHomeRequest)
	returns (ReturnToHomeResponse) {}
  /*
   * Order the vehicle to move to a global position.
   *
   * Causes the vehicle to transit to the provided global position. The vehicle
   * will interpret the heading of travel according to `heading_mode`:
   * - `TO_TARGET` -> turn to face the target position bearing
   * - `HEADING_START` -> turn to face the provided heading in the global position object.
   *
   * This will be the heading the vehicle maintains for the duration of transit.
   *
   * The vehicle will move towards the target at the specified maximum velocity
   * until the vehicle has reached its destination. Error tolerance is determined
   * by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
   * - `x_vel` -> maximum _horizontal_ velocity
   * - `y_vel` -> ignored
   * - `z_vel` -> maximum _vertical_ velocity
   *
   * If no maximum velocity is provided, the driver will use a preset speed usually
   * determined by the manufacturer or hardware settings.
   *
   * During motion, the vehicle will also ascend or descend towards the target
   * altitude, linearly interpolating this movement over the duration of travel.
   * The vehicle will interpret altitude from `altitude_mode` as follows:
   * - `ABSOLUTE` -> altitude is relative to MSL (Mean Sea Level)
   * - `RELATIVE` -> altitude is relative to take off position
   */
  rpc GoToGlobalPosition (GoToGlobalPositionRequest)
	returns (GoToGlobalPositionResponse) {}
  /*
   * Order the vehicle to move to a relative position.
   *
   * Causes the vehicle to transit to the provided relative position. The vehicle
   * will interpret the input position according to `frame` as follows:
   * - `BODY` -> (`x`, `y`, `z`) = (forward offset, right offset, up offset) _from current position_
   * - `NEU` -> (`x`, `y`, `z`) = (north offset, east offset, up offset) _from start position_
   *
   * The vehicle will move towards the target at the specified maximum velocity
   * until the vehicle has reached its destination. Error tolerance is determined
   * by the driver. Maximum velocity is interpreted from `max_velocity` as follows:
   * - `x_vel` -> maximum _horizontal_ velocity
   * - `y_vel` -> ignored
   * - `z_vel` -> maximum _vertical_ velocity
   *
   * If no maximum velocity is provided, the driver will use a preset speed usually
   * determined by the manufacturer or hardware settings.
   */
  rpc GoToRelativePosition (GoToRelativePositionRequest)
	returns (GoToRelativePositionResponse) {}
  /*
   * Order the vehicle to accelerate to a velocity.
   *
   * Causes the vehicle to accelerate until it reaches a provided velocity.
   * The vehicle will interpret the input velocity according to `frame` as follows:
   * - `BODY` -> (`x_vel`, `y_vel`, `z_vel`) = (forward velocity, right velocity, up velocity)
   * - `NEU` -> (`x_vel`, `y_vel`, `z_vel`) = (north velocity, east velocity, up velocity)
   */
  rpc SetVelocity (SetVelocityRequest)
	returns (SetVelocityResponse) {}
  /*
   * Order the vehicle to set the pose of a gimbal.
   *
   * Causes the vehicle to actuate a gimbal to a new pose. The vehicle
   * will interpret the new pose type from `pose_mode` as follows:
   * - `ABSOLUTE` -> absolute angle
   * - `RELATIVE` -> angle relative to current position
   * - `VELOCITY` -> angular velocities
   *
   * The vehicle will interpret the new pose angles according to `frame`
   * as follows:
   * - `BODY` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, body yaw)
   * - `NEU` -> (`pitch`, `roll`, `yaw`) = (body pitch, body roll, global yaw)
   */
  rpc SetGimbalPose (SetGimbalPoseRequest)
	returns (SetGimbalPoseResponse) {}
}

message TakeOffRequest {
  // take off height in relative altitude [meters]
  float take_off_altitude = 1;
}

message TakeOffResponse {}

message LandRequest {}

message LandResponse {}

message HoldRequest {}

message HoldResponse {}

message KillRequest {}

message KillResponse {}

message SetHomeRequest {
  GlobalPosition new_home = 1; // new home location
}

message SetHomeResponse {}

enum ReturnToHomeEndBehavior {
  RETURN_TO_HOME_END_BEHAVIOR_UNSPECIFIED = 0; // defaults to `HOVER`
  RETURN_TO_HOME_END_BEHAVIOR_HOVER = 1; // hover upon return to home
  RETURN_TO_HOME_END_BEHAVIOR_LAND = 2; // land upon return to home
}

message ReturnToHomeRequest {
  // what the vehicle should do after returning home
  ReturnToHomeEndBehavior end_behavior = 1;
  // altitude that the vehicle should move at while reurning home
  uint32 return_altitude = 2;
  // altitude that the vehicle should hover AGL (above ground level), for hover end behavior
  uint32 final_altitude = 3;
}

message ReturnToHomeResponse {}

// Altitude mode switch.
enum AltitudeMode {
  ALTITUDE_MODE_UNSPECIFIED = 0; // defaults to `RELATIVE`
  ALTITUDE_MODE_RELATIVE = 1; // meters above takeoff position
  ALTITUDE_MODE_ABSOLUTE = 2; // meters above Mean Sea Level
}

// Heading mode switch.
enum HeadingMode {
  HEADING_MODE_UNSPECIFIED = 0; // defaults to `TO_TARGET`
  HEADING_MODE_TO_TARGET = 1; // orient towards the target location
  HEADING_MODE_START = 2; // orient towards the given heading
}

message GoToGlobalPositionRequest {
  GlobalPosition position = 1; // target global position
  // determines how the vehicle will orient during transit (default: `TO_TARGET`)
  optional HeadingMode heading_mode = 2;
  // determines how the vehicle will interpret altitude (default: `ABSOLUTE`)
  optional AltitudeMode altitude_mode = 3;
  // speed during transit
  optional float speed = 4;
  // angular speed during transit
  optional float angular_speed = 5;
}

message GoToGlobalPositionResponse {}

// Reference frame mode switch.
enum ReferenceFrame {
  REFERENCE_FRAME_UNSPECIFIED = 0; // defaults to `BODY`
  REFERENCE_FRAME_BODY = 1; // vehicle reference frame
  REFERENCE_FRAME_NEU = 2; // NEU (North, East, Up) reference frame
}

message GoToRelativePositionRequest {
  // target relative position
  RelativePosition position = 1;
  // speed during transit
  optional float speed = 2;
  // angular speed during transit
  optional float angular_speed = 3;
  // frame of reference
  optional ReferenceFrame frame = 4;
}

message GoToRelativePositionResponse {}

message SetVelocityRequest {
  // target velocity
  Velocity velocity = 1;
  // frame of reference
  optional ReferenceFrame frame = 2;
}

message SetVelocityResponse {}

// Pose mode switch.
enum PoseMode {
  POSE_MODE_UNSPECIFIED = 0; // defaults to `ANGLE`
  POSE_MODE_ANGLE = 1; // absolute angle
  POSE_MODE_OFFSET = 2; // offset from current
  POSE_MODE_VELOCITY = 3; // rotational velocities
}

message SetGimbalPoseRequest {
  uint32 gimbal_id = 1; // ID of the target gimbal
  Pose pose = 2; // target pose
  optional PoseMode pose_mode = 3; // specifies how to interpret the target pose
}

message SetGimbalPoseResponse {}
