// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - Living Edge Lab
//
// SPDX-License-Identifier: GPL-2.0-only

syntax = "proto3";
package steeleagle_protocol.v1.services.driver;

option go_package = "github.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/driver;driver";

import "steeleagle_protocol/v1/messages/telemetry/telemetry.proto";

/*
 * Used to get streams from the driver.
 *
 * This is an internal service used to retrieve imagery and telemetry from the
 * driver. These are processed by the OS and then served as the `DataService`
 * to other connected plugins.
 */
service StreamService {
  /*
   * Get the video streaming URL from the vehicle.
   *
   * Retrieves the video stream URL from the vehicle so that it can be
   * broadcast to the rest of the system. This function should only be called
   * by the OS, and not by any plugins.
   */
  rpc GetVideoStreamURL (GetVideoStreamURLRequest)
    returns (GetVideoStreamURLResponse);

  /*
   * Stream individual video frames from the vehicle.
   *
   * Retrieves a stream of individual video frame from the vehicle. This is
   * used when camera data is accessible without needing a stream. This
   * function should only be called by the OS, and not by any plugins.
   */
  rpc StreamVideoFrames (StreamVideoFramesRequest)
    returns (stream StreamVideoFramesResponse);

  /*
   * Stream telemetry from the vehicle.
   *
   * Streams up-to-date telemetry from the vehicle. This function should only
   * be called by the OS, and not by any plugins.
   */
  rpc StreamTelemetry (StreamTelemetryRequest)
    returns (stream StreamTelemetryResponse);
}

enum Resolution {
  RESOLUTION_UNSPECIFIED = 0; // defaults to 720P
  RESOLUTION_480P = 1;
  RESOLUTION_720P = 2;
  RESOLUTION_1080P = 3;
  RESOLUTION_4K = 4;
}

message GetVideoStreamURLRequest {
  Resolution resolution = 1; // video stream resolution
}

message GetVideoStreamURLResponse {
  string stream_url = 1; // URL of the video stream
  optional uint32 target_fps = 2; // target fps to stream at, if 0 is provided will choose fps
}

message StreamVideoFramesRequest {
  optional uint32 target_fps = 1; // target fps to stream at, if 0 is provided will choose fps
  Resolution resolution = 2; // target frame resolution, if unspecified the driver's native resolution is used
}

message StreamVideoFramesResponse {
  steeleagle_protocol.v1.messages.telemetry.EncodedFrame frame = 1; // encoded frame from the camera
}

message StreamTelemetryRequest {
  optional uint32 target_fps = 1; // target fps to stream at, if 0 is provided will choose fps
}

message StreamTelemetryResponse {
  steeleagle_protocol.v1.messages.telemetry.Telemetry telemetry = 1; // telemetry from the driver
}
