// SPDX-FileCopyrightText: 2025 Carnegie Mellon University - LivingEdgeLab
//
// SPDX-License-Identifier: GPL-2.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: steeleagle_protocol/v1/services/eagled/eagled.proto

package eagled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginCategory int32

const (
	PluginCategory_PLUGIN_CATEGORY_UNSPECIFIED PluginCategory = 0
	PluginCategory_PLUGIN_CATEGORY_DRIVER      PluginCategory = 1
	PluginCategory_PLUGIN_CATEGORY_MISSION     PluginCategory = 2
	PluginCategory_PLUGIN_CATEGORY_EXTRA       PluginCategory = 3
)

// Enum value maps for PluginCategory.
var (
	PluginCategory_name = map[int32]string{
		0: "PLUGIN_CATEGORY_UNSPECIFIED",
		1: "PLUGIN_CATEGORY_DRIVER",
		2: "PLUGIN_CATEGORY_MISSION",
		3: "PLUGIN_CATEGORY_EXTRA",
	}
	PluginCategory_value = map[string]int32{
		"PLUGIN_CATEGORY_UNSPECIFIED": 0,
		"PLUGIN_CATEGORY_DRIVER":      1,
		"PLUGIN_CATEGORY_MISSION":     2,
		"PLUGIN_CATEGORY_EXTRA":       3,
	}
)

func (x PluginCategory) Enum() *PluginCategory {
	p := new(PluginCategory)
	*p = x
	return p
}

func (x PluginCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_steeleagle_protocol_v1_services_eagled_eagled_proto_enumTypes[0].Descriptor()
}

func (PluginCategory) Type() protoreflect.EnumType {
	return &file_steeleagle_protocol_v1_services_eagled_eagled_proto_enumTypes[0]
}

func (x PluginCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConfigureRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConfigToml string                 `protobuf:"bytes,1,opt,name=config_toml,json=configToml,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureRequest) GetConfigToml() string {
	if x != nil {
		return x.xxx_hidden_ConfigToml
	}
	return ""
}

func (x *ConfigureRequest) SetConfigToml(v string) {
	x.xxx_hidden_ConfigToml = v
}

type ConfigureRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ConfigToml string
}

func (b0 ConfigureRequest_builder) Build() *ConfigureRequest {
	m0 := &ConfigureRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConfigToml = b.ConfigToml
	return m0
}

type ConfigureResponse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vehicles               *[]*VehicleResult      `protobuf:"bytes,1,rep,name=vehicles,proto3"`
	xxx_hidden_DaemonSettingsApplied  bool                   `protobuf:"varint,2,opt,name=daemon_settings_applied,json=daemonSettingsApplied,proto3"`
	xxx_hidden_DaemonSettingsDiverged bool                   `protobuf:"varint,3,opt,name=daemon_settings_diverged,json=daemonSettingsDiverged,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureResponse) GetVehicles() []*VehicleResult {
	if x != nil {
		if x.xxx_hidden_Vehicles != nil {
			return *x.xxx_hidden_Vehicles
		}
	}
	return nil
}

func (x *ConfigureResponse) GetDaemonSettingsApplied() bool {
	if x != nil {
		return x.xxx_hidden_DaemonSettingsApplied
	}
	return false
}

func (x *ConfigureResponse) GetDaemonSettingsDiverged() bool {
	if x != nil {
		return x.xxx_hidden_DaemonSettingsDiverged
	}
	return false
}

func (x *ConfigureResponse) SetVehicles(v []*VehicleResult) {
	x.xxx_hidden_Vehicles = &v
}

func (x *ConfigureResponse) SetDaemonSettingsApplied(v bool) {
	x.xxx_hidden_DaemonSettingsApplied = v
}

func (x *ConfigureResponse) SetDaemonSettingsDiverged(v bool) {
	x.xxx_hidden_DaemonSettingsDiverged = v
}

type ConfigureResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vehicles []*VehicleResult
	// True only for the first Configure call a fresh daemon ever receives, when
	// daemon-wide settings were actually established from this call.
	DaemonSettingsApplied bool
	// True when this was not the first Configure call and this call's
	// daemon-wide settings differ from what's already active -- i.e. some
	// requested settings were silently not applied. Always false when
	// daemon_settings_applied is true, and also false on a later call whose
	// daemon-wide settings already matched what's active (nothing to report).
	DaemonSettingsDiverged bool
}

func (b0 ConfigureResponse_builder) Build() *ConfigureResponse {
	m0 := &ConfigureResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vehicles = &b.Vehicles
	x.xxx_hidden_DaemonSettingsApplied = b.DaemonSettingsApplied
	x.xxx_hidden_DaemonSettingsDiverged = b.DaemonSettingsDiverged
	return m0
}

type StopVehiclesRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StopVehiclesRequest) Reset() {
	*x = StopVehiclesRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVehiclesRequest) ProtoMessage() {}

func (x *StopVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopVehiclesRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *StopVehiclesRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type StopVehiclesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 StopVehiclesRequest_builder) Build() *StopVehiclesRequest {
	m0 := &StopVehiclesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

type StopVehiclesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vehicles *[]*VehicleResult      `protobuf:"bytes,1,rep,name=vehicles,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StopVehiclesResponse) Reset() {
	*x = StopVehiclesResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVehiclesResponse) ProtoMessage() {}

func (x *StopVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopVehiclesResponse) GetVehicles() []*VehicleResult {
	if x != nil {
		if x.xxx_hidden_Vehicles != nil {
			return *x.xxx_hidden_Vehicles
		}
	}
	return nil
}

func (x *StopVehiclesResponse) SetVehicles(v []*VehicleResult) {
	x.xxx_hidden_Vehicles = &v
}

type StopVehiclesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vehicles []*VehicleResult
}

func (b0 StopVehiclesResponse_builder) Build() *StopVehiclesResponse {
	m0 := &StopVehiclesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vehicles = &b.Vehicles
	return m0
}

type RestartVehiclesRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestartVehiclesRequest) Reset() {
	*x = RestartVehiclesRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVehiclesRequest) ProtoMessage() {}

func (x *RestartVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartVehiclesRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *RestartVehiclesRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type RestartVehiclesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 RestartVehiclesRequest_builder) Build() *RestartVehiclesRequest {
	m0 := &RestartVehiclesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

type RestartVehiclesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vehicles *[]*VehicleResult      `protobuf:"bytes,1,rep,name=vehicles,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestartVehiclesResponse) Reset() {
	*x = RestartVehiclesResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVehiclesResponse) ProtoMessage() {}

func (x *RestartVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartVehiclesResponse) GetVehicles() []*VehicleResult {
	if x != nil {
		if x.xxx_hidden_Vehicles != nil {
			return *x.xxx_hidden_Vehicles
		}
	}
	return nil
}

func (x *RestartVehiclesResponse) SetVehicles(v []*VehicleResult) {
	x.xxx_hidden_Vehicles = &v
}

type RestartVehiclesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vehicles []*VehicleResult
}

func (b0 RestartVehiclesResponse_builder) Build() *RestartVehiclesResponse {
	m0 := &RestartVehiclesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vehicles = &b.Vehicles
	return m0
}

type ForgetVehiclesRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForgetVehiclesRequest) Reset() {
	*x = ForgetVehiclesRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetVehiclesRequest) ProtoMessage() {}

func (x *ForgetVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForgetVehiclesRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *ForgetVehiclesRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type ForgetVehiclesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 ForgetVehiclesRequest_builder) Build() *ForgetVehiclesRequest {
	m0 := &ForgetVehiclesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

type ForgetVehiclesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vehicles *[]*VehicleResult      `protobuf:"bytes,1,rep,name=vehicles,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ForgetVehiclesResponse) Reset() {
	*x = ForgetVehiclesResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetVehiclesResponse) ProtoMessage() {}

func (x *ForgetVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForgetVehiclesResponse) GetVehicles() []*VehicleResult {
	if x != nil {
		if x.xxx_hidden_Vehicles != nil {
			return *x.xxx_hidden_Vehicles
		}
	}
	return nil
}

func (x *ForgetVehiclesResponse) SetVehicles(v []*VehicleResult) {
	x.xxx_hidden_Vehicles = &v
}

type ForgetVehiclesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vehicles []*VehicleResult
}

func (b0 ForgetVehiclesResponse_builder) Build() *ForgetVehiclesResponse {
	m0 := &ForgetVehiclesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vehicles = &b.Vehicles
	return m0
}

type VehicleResult struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name            string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Ok              bool                   `protobuf:"varint,2,opt,name=ok,proto3"`
	xxx_hidden_Error           string                 `protobuf:"bytes,3,opt,name=error,proto3"`
	xxx_hidden_Reconfigured    bool                   `protobuf:"varint,4,opt,name=reconfigured,proto3"`
	xxx_hidden_RestartRequired bool                   `protobuf:"varint,5,opt,name=restart_required,json=restartRequired,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VehicleResult) Reset() {
	*x = VehicleResult{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleResult) ProtoMessage() {}

func (x *VehicleResult) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VehicleResult) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *VehicleResult) GetOk() bool {
	if x != nil {
		return x.xxx_hidden_Ok
	}
	return false
}

func (x *VehicleResult) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *VehicleResult) GetReconfigured() bool {
	if x != nil {
		return x.xxx_hidden_Reconfigured
	}
	return false
}

func (x *VehicleResult) GetRestartRequired() bool {
	if x != nil {
		return x.xxx_hidden_RestartRequired
	}
	return false
}

func (x *VehicleResult) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *VehicleResult) SetOk(v bool) {
	x.xxx_hidden_Ok = v
}

func (x *VehicleResult) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *VehicleResult) SetReconfigured(v bool) {
	x.xxx_hidden_Reconfigured = v
}

func (x *VehicleResult) SetRestartRequired(v bool) {
	x.xxx_hidden_RestartRequired = v
}

type VehicleResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  string
	Ok    bool
	Error string
	// True iff ok and this Configure call replaced an already-known vehicle's
	// config -- as opposed to configuring name for the first time. Only
	// meaningful in a ConfigureResponse; always false from StopVehicles/
	// RestartVehicles/ForgetVehicles.
	Reconfigured bool
	// True iff ok, reconfigured, and name was already running: its new config
	// is saved and becomes what a future RestartVehicles/eagled restart uses,
	// but the running process itself was left alone, so it's still running
	// under its *previous* config until explicitly restarted. Only meaningful
	// in a ConfigureResponse.
	RestartRequired bool
}

func (b0 VehicleResult_builder) Build() *VehicleResult {
	m0 := &VehicleResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Ok = b.Ok
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Reconfigured = b.Reconfigured
	x.xxx_hidden_RestartRequired = b.RestartRequired
	return m0
}

type InstallPluginRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name     string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Repo     string                 `protobuf:"bytes,2,opt,name=repo,proto3"`
	xxx_hidden_Ref      string                 `protobuf:"bytes,3,opt,name=ref,proto3"`
	xxx_hidden_Subpath  string                 `protobuf:"bytes,4,opt,name=subpath,proto3"`
	xxx_hidden_Category PluginCategory         `protobuf:"varint,5,opt,name=category,proto3,enum=steeleagle_protocol.v1.services.eagled.PluginCategory"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstallPluginRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *InstallPluginRequest) GetRepo() string {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return ""
}

func (x *InstallPluginRequest) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *InstallPluginRequest) GetSubpath() string {
	if x != nil {
		return x.xxx_hidden_Subpath
	}
	return ""
}

func (x *InstallPluginRequest) GetCategory() PluginCategory {
	if x != nil {
		return x.xxx_hidden_Category
	}
	return PluginCategory_PLUGIN_CATEGORY_UNSPECIFIED
}

func (x *InstallPluginRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *InstallPluginRequest) SetRepo(v string) {
	x.xxx_hidden_Repo = v
}

func (x *InstallPluginRequest) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *InstallPluginRequest) SetSubpath(v string) {
	x.xxx_hidden_Subpath = v
}

func (x *InstallPluginRequest) SetCategory(v PluginCategory) {
	x.xxx_hidden_Category = v
}

type InstallPluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name     string
	Repo     string
	Ref      string
	Subpath  string
	Category PluginCategory
}

func (b0 InstallPluginRequest_builder) Build() *InstallPluginRequest {
	m0 := &InstallPluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Subpath = b.Subpath
	x.xxx_hidden_Category = b.Category
	return m0
}

type InstallPluginResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3"`
	xxx_hidden_Error string                 `protobuf:"bytes,2,opt,name=error,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InstallPluginResponse) Reset() {
	*x = InstallPluginResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginResponse) ProtoMessage() {}

func (x *InstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstallPluginResponse) GetOk() bool {
	if x != nil {
		return x.xxx_hidden_Ok
	}
	return false
}

func (x *InstallPluginResponse) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *InstallPluginResponse) SetOk(v bool) {
	x.xxx_hidden_Ok = v
}

func (x *InstallPluginResponse) SetError(v string) {
	x.xxx_hidden_Error = v
}

type InstallPluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ok    bool
	Error string
}

func (b0 InstallPluginResponse_builder) Build() *InstallPluginResponse {
	m0 := &InstallPluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ok = b.Ok
	x.xxx_hidden_Error = b.Error
	return m0
}

type GetInstalledPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstalledPluginsRequest) Reset() {
	*x = GetInstalledPluginsRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstalledPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstalledPluginsRequest) ProtoMessage() {}

func (x *GetInstalledPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetInstalledPluginsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetInstalledPluginsRequest_builder) Build() *GetInstalledPluginsRequest {
	m0 := &GetInstalledPluginsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetInstalledPluginsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Plugins *[]*InstalledPlugin    `protobuf:"bytes,1,rep,name=plugins,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInstalledPluginsResponse) Reset() {
	*x = GetInstalledPluginsResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstalledPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstalledPluginsResponse) ProtoMessage() {}

func (x *GetInstalledPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInstalledPluginsResponse) GetPlugins() []*InstalledPlugin {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *GetInstalledPluginsResponse) SetPlugins(v []*InstalledPlugin) {
	x.xxx_hidden_Plugins = &v
}

type GetInstalledPluginsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plugins []*InstalledPlugin
}

func (b0 GetInstalledPluginsResponse_builder) Build() *GetInstalledPluginsResponse {
	m0 := &GetInstalledPluginsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plugins = &b.Plugins
	return m0
}

type InstalledPlugin struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name     string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Ref      string                 `protobuf:"bytes,2,opt,name=ref,proto3"`
	xxx_hidden_Category PluginCategory         `protobuf:"varint,3,opt,name=category,proto3,enum=steeleagle_protocol.v1.services.eagled.PluginCategory"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstalledPlugin) Reset() {
	*x = InstalledPlugin{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPlugin) ProtoMessage() {}

func (x *InstalledPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstalledPlugin) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *InstalledPlugin) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *InstalledPlugin) GetCategory() PluginCategory {
	if x != nil {
		return x.xxx_hidden_Category
	}
	return PluginCategory_PLUGIN_CATEGORY_UNSPECIFIED
}

func (x *InstalledPlugin) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *InstalledPlugin) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *InstalledPlugin) SetCategory(v PluginCategory) {
	x.xxx_hidden_Category = v
}

type InstalledPlugin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name     string
	Ref      string
	Category PluginCategory
}

func (b0 InstalledPlugin_builder) Build() *InstalledPlugin {
	m0 := &InstalledPlugin{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Category = b.Category
	return m0
}

type ResetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetConfigRequest) Reset() {
	*x = ResetConfigRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetConfigRequest) ProtoMessage() {}

func (x *ResetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetConfigRequest_builder) Build() *ResetConfigRequest {
	m0 := &ResetConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ResetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetConfigResponse) Reset() {
	*x = ResetConfigResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetConfigResponse) ProtoMessage() {}

func (x *ResetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResetConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResetConfigResponse_builder) Build() *ResetConfigResponse {
	m0 := &ResetConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RestartDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDaemonRequest) Reset() {
	*x = RestartDaemonRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDaemonRequest) ProtoMessage() {}

func (x *RestartDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RestartDaemonRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RestartDaemonRequest_builder) Build() *RestartDaemonRequest {
	m0 := &RestartDaemonRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RestartDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDaemonResponse) Reset() {
	*x = RestartDaemonResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDaemonResponse) ProtoMessage() {}

func (x *RestartDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RestartDaemonResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RestartDaemonResponse_builder) Build() *RestartDaemonResponse {
	m0 := &RestartDaemonResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetStatusRequest_builder) Build() *GetStatusRequest {
	m0 := &GetStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetStatusResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Configured bool                   `protobuf:"varint,1,opt,name=configured,proto3"`
	xxx_hidden_Config     *DaemonConfig          `protobuf:"bytes,2,opt,name=config,proto3"`
	xxx_hidden_Vehicles   *[]*VehicleStatus      `protobuf:"bytes,3,rep,name=vehicles,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetStatusResponse) GetConfigured() bool {
	if x != nil {
		return x.xxx_hidden_Configured
	}
	return false
}

func (x *GetStatusResponse) GetConfig() *DaemonConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *GetStatusResponse) GetVehicles() []*VehicleStatus {
	if x != nil {
		if x.xxx_hidden_Vehicles != nil {
			return *x.xxx_hidden_Vehicles
		}
	}
	return nil
}

func (x *GetStatusResponse) SetConfigured(v bool) {
	x.xxx_hidden_Configured = v
}

func (x *GetStatusResponse) SetConfig(v *DaemonConfig) {
	x.xxx_hidden_Config = v
}

func (x *GetStatusResponse) SetVehicles(v []*VehicleStatus) {
	x.xxx_hidden_Vehicles = &v
}

func (x *GetStatusResponse) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *GetStatusResponse) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type GetStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Configured bool
	Config     *DaemonConfig
	Vehicles   []*VehicleStatus
}

func (b0 GetStatusResponse_builder) Build() *GetStatusResponse {
	m0 := &GetStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Configured = b.Configured
	x.xxx_hidden_Config = b.Config
	x.xxx_hidden_Vehicles = &b.Vehicles
	return m0
}

// DaemonConfig reports the daemon-wide settings established by the first
// Configure call. Secrets stay out of it: authkey_env names the env var
// holding the tsnet auth key, never the resolved key itself.
type DaemonConfig struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vpn                    bool                   `protobuf:"varint,1,opt,name=vpn,proto3"`
	xxx_hidden_VehicleVpn             bool                   `protobuf:"varint,2,opt,name=vehicle_vpn,json=vehicleVpn,proto3"`
	xxx_hidden_PortBase               int32                  `protobuf:"varint,3,opt,name=port_base,json=portBase,proto3"`
	xxx_hidden_PluginDir              string                 `protobuf:"bytes,4,opt,name=plugin_dir,json=pluginDir,proto3"`
	xxx_hidden_TailscaleHostname      string                 `protobuf:"bytes,5,opt,name=tailscale_hostname,json=tailscaleHostname,proto3"`
	xxx_hidden_TailscaleAuthkeyEnv    string                 `protobuf:"bytes,6,opt,name=tailscale_authkey_env,json=tailscaleAuthkeyEnv,proto3"`
	xxx_hidden_SwarmControllerAddress string                 `protobuf:"bytes,7,opt,name=swarm_controller_address,json=swarmControllerAddress,proto3"`
	xxx_hidden_DaemonName             string                 `protobuf:"bytes,8,opt,name=daemon_name,json=daemonName,proto3"`
	xxx_hidden_GabrielServerEndpoint  string                 `protobuf:"bytes,9,opt,name=gabriel_server_endpoint,json=gabrielServerEndpoint,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *DaemonConfig) Reset() {
	*x = DaemonConfig{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfig) ProtoMessage() {}

func (x *DaemonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DaemonConfig) GetVpn() bool {
	if x != nil {
		return x.xxx_hidden_Vpn
	}
	return false
}

func (x *DaemonConfig) GetVehicleVpn() bool {
	if x != nil {
		return x.xxx_hidden_VehicleVpn
	}
	return false
}

func (x *DaemonConfig) GetPortBase() int32 {
	if x != nil {
		return x.xxx_hidden_PortBase
	}
	return 0
}

func (x *DaemonConfig) GetPluginDir() string {
	if x != nil {
		return x.xxx_hidden_PluginDir
	}
	return ""
}

func (x *DaemonConfig) GetTailscaleHostname() string {
	if x != nil {
		return x.xxx_hidden_TailscaleHostname
	}
	return ""
}

func (x *DaemonConfig) GetTailscaleAuthkeyEnv() string {
	if x != nil {
		return x.xxx_hidden_TailscaleAuthkeyEnv
	}
	return ""
}

func (x *DaemonConfig) GetSwarmControllerAddress() string {
	if x != nil {
		return x.xxx_hidden_SwarmControllerAddress
	}
	return ""
}

func (x *DaemonConfig) GetDaemonName() string {
	if x != nil {
		return x.xxx_hidden_DaemonName
	}
	return ""
}

func (x *DaemonConfig) GetGabrielServerEndpoint() string {
	if x != nil {
		return x.xxx_hidden_GabrielServerEndpoint
	}
	return ""
}

func (x *DaemonConfig) SetVpn(v bool) {
	x.xxx_hidden_Vpn = v
}

func (x *DaemonConfig) SetVehicleVpn(v bool) {
	x.xxx_hidden_VehicleVpn = v
}

func (x *DaemonConfig) SetPortBase(v int32) {
	x.xxx_hidden_PortBase = v
}

func (x *DaemonConfig) SetPluginDir(v string) {
	x.xxx_hidden_PluginDir = v
}

func (x *DaemonConfig) SetTailscaleHostname(v string) {
	x.xxx_hidden_TailscaleHostname = v
}

func (x *DaemonConfig) SetTailscaleAuthkeyEnv(v string) {
	x.xxx_hidden_TailscaleAuthkeyEnv = v
}

func (x *DaemonConfig) SetSwarmControllerAddress(v string) {
	x.xxx_hidden_SwarmControllerAddress = v
}

func (x *DaemonConfig) SetDaemonName(v string) {
	x.xxx_hidden_DaemonName = v
}

func (x *DaemonConfig) SetGabrielServerEndpoint(v string) {
	x.xxx_hidden_GabrielServerEndpoint = v
}

type DaemonConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vpn                    bool
	VehicleVpn             bool
	PortBase               int32
	PluginDir              string
	TailscaleHostname      string
	TailscaleAuthkeyEnv    string
	SwarmControllerAddress string
	DaemonName             string
	GabrielServerEndpoint  string
}

func (b0 DaemonConfig_builder) Build() *DaemonConfig {
	m0 := &DaemonConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vpn = b.Vpn
	x.xxx_hidden_VehicleVpn = b.VehicleVpn
	x.xxx_hidden_PortBase = b.PortBase
	x.xxx_hidden_PluginDir = b.PluginDir
	x.xxx_hidden_TailscaleHostname = b.TailscaleHostname
	x.xxx_hidden_TailscaleAuthkeyEnv = b.TailscaleAuthkeyEnv
	x.xxx_hidden_SwarmControllerAddress = b.SwarmControllerAddress
	x.xxx_hidden_DaemonName = b.DaemonName
	x.xxx_hidden_GabrielServerEndpoint = b.GabrielServerEndpoint
	return m0
}

type VehicleStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Driver      string                 `protobuf:"bytes,2,opt,name=driver,proto3"`
	xxx_hidden_Running     bool                   `protobuf:"varint,3,opt,name=running,proto3"`
	xxx_hidden_Port        int32                  `protobuf:"varint,4,opt,name=port,proto3"`
	xxx_hidden_ConfigStale bool                   `protobuf:"varint,5,opt,name=config_stale,json=configStale,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VehicleStatus) Reset() {
	*x = VehicleStatus{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatus) ProtoMessage() {}

func (x *VehicleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VehicleStatus) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *VehicleStatus) GetDriver() string {
	if x != nil {
		return x.xxx_hidden_Driver
	}
	return ""
}

func (x *VehicleStatus) GetRunning() bool {
	if x != nil {
		return x.xxx_hidden_Running
	}
	return false
}

func (x *VehicleStatus) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *VehicleStatus) GetConfigStale() bool {
	if x != nil {
		return x.xxx_hidden_ConfigStale
	}
	return false
}

func (x *VehicleStatus) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *VehicleStatus) SetDriver(v string) {
	x.xxx_hidden_Driver = v
}

func (x *VehicleStatus) SetRunning(v bool) {
	x.xxx_hidden_Running = v
}

func (x *VehicleStatus) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *VehicleStatus) SetConfigStale(v bool) {
	x.xxx_hidden_ConfigStale = v
}

type VehicleStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    string
	Driver  string
	Running bool
	Port    int32
	// True iff running and a Configure call has replaced this vehicle's config
	// since this running process was spawned -- it's still running under its
	// previous config, and picks up the new one on its next restart. Always
	// false when not running.
	ConfigStale bool
}

func (b0 VehicleStatus_builder) Build() *VehicleStatus {
	m0 := &VehicleStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Driver = b.Driver
	x.xxx_hidden_Running = b.Running
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_ConfigStale = b.ConfigStale
	return m0
}

type StreamLogsRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sources  []string               `protobuf:"bytes,1,rep,name=sources,proto3"`
	xxx_hidden_Tail     int32                  `protobuf:"varint,2,opt,name=tail,proto3"`
	xxx_hidden_Follow   bool                   `protobuf:"varint,3,opt,name=follow,proto3"`
	xxx_hidden_AfterSeq map[string]uint64      `protobuf:"bytes,4,rep,name=after_seq,json=afterSeq,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamLogsRequest) GetSources() []string {
	if x != nil {
		return x.xxx_hidden_Sources
	}
	return nil
}

func (x *StreamLogsRequest) GetTail() int32 {
	if x != nil {
		return x.xxx_hidden_Tail
	}
	return 0
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.xxx_hidden_Follow
	}
	return false
}

func (x *StreamLogsRequest) GetAfterSeq() map[string]uint64 {
	if x != nil {
		return x.xxx_hidden_AfterSeq
	}
	return nil
}

func (x *StreamLogsRequest) SetSources(v []string) {
	x.xxx_hidden_Sources = v
}

func (x *StreamLogsRequest) SetTail(v int32) {
	x.xxx_hidden_Tail = v
}

func (x *StreamLogsRequest) SetFollow(v bool) {
	x.xxx_hidden_Follow = v
}

func (x *StreamLogsRequest) SetAfterSeq(v map[string]uint64) {
	x.xxx_hidden_AfterSeq = v
}

type StreamLogsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sources  []string
	Tail     int32
	Follow   bool
	AfterSeq map[string]uint64
}

func (b0 StreamLogsRequest_builder) Build() *StreamLogsRequest {
	m0 := &StreamLogsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sources = b.Sources
	x.xxx_hidden_Tail = b.Tail
	x.xxx_hidden_Follow = b.Follow
	x.xxx_hidden_AfterSeq = b.AfterSeq
	return m0
}

type LogRecord struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source  string                 `protobuf:"bytes,1,opt,name=source,proto3"`
	xxx_hidden_Seq     uint64                 `protobuf:"varint,2,opt,name=seq,proto3"`
	xxx_hidden_Time    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3"`
	xxx_hidden_Level   string                 `protobuf:"bytes,4,opt,name=level,proto3"`
	xxx_hidden_Text    string                 `protobuf:"bytes,5,opt,name=text,proto3"`
	xxx_hidden_Dropped uint64                 `protobuf:"varint,6,opt,name=dropped,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogRecord) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *LogRecord) GetSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *LogRecord) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return ""
}

func (x *LogRecord) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *LogRecord) GetDropped() uint64 {
	if x != nil {
		return x.xxx_hidden_Dropped
	}
	return 0
}

func (x *LogRecord) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *LogRecord) SetSeq(v uint64) {
	x.xxx_hidden_Seq = v
}

func (x *LogRecord) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *LogRecord) SetLevel(v string) {
	x.xxx_hidden_Level = v
}

func (x *LogRecord) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *LogRecord) SetDropped(v uint64) {
	x.xxx_hidden_Dropped = v
}

func (x *LogRecord) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *LogRecord) ClearTime() {
	x.xxx_hidden_Time = nil
}

type LogRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source  string
	Seq     uint64
	Time    *timestamppb.Timestamp
	Level   string
	Text    string
	Dropped uint64
}

func (b0 LogRecord_builder) Build() *LogRecord {
	m0 := &LogRecord{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Seq = b.Seq
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_Level = b.Level
	x.xxx_hidden_Text = b.Text
	x.xxx_hidden_Dropped = b.Dropped
	return m0
}

type ListLogSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSourcesRequest) Reset() {
	*x = ListLogSourcesRequest{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesRequest) ProtoMessage() {}

func (x *ListLogSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListLogSourcesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListLogSourcesRequest_builder) Build() *ListLogSourcesRequest {
	m0 := &ListLogSourcesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListLogSourcesResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sources *[]*LogSource          `protobuf:"bytes,1,rep,name=sources,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListLogSourcesResponse) Reset() {
	*x = ListLogSourcesResponse{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSourcesResponse) ProtoMessage() {}

func (x *ListLogSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListLogSourcesResponse) GetSources() []*LogSource {
	if x != nil {
		if x.xxx_hidden_Sources != nil {
			return *x.xxx_hidden_Sources
		}
	}
	return nil
}

func (x *ListLogSourcesResponse) SetSources(v []*LogSource) {
	x.xxx_hidden_Sources = &v
}

type ListLogSourcesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sources []*LogSource
}

func (b0 ListLogSourcesResponse_builder) Build() *ListLogSourcesResponse {
	m0 := &ListLogSourcesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sources = &b.Sources
	return m0
}

type LogSource struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name      string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Running   bool                   `protobuf:"varint,2,opt,name=running,proto3"`
	xxx_hidden_SizeBytes int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogSource) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *LogSource) GetRunning() bool {
	if x != nil {
		return x.xxx_hidden_Running
	}
	return false
}

func (x *LogSource) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *LogSource) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *LogSource) SetRunning(v bool) {
	x.xxx_hidden_Running = v
}

func (x *LogSource) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
}

type LogSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      string
	Running   bool
	SizeBytes int64
}

func (b0 LogSource_builder) Build() *LogSource {
	m0 := &LogSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Running = b.Running
	x.xxx_hidden_SizeBytes = b.SizeBytes
	return m0
}

var File_steeleagle_protocol_v1_services_eagled_eagled_proto protoreflect.FileDescriptor

const file_steeleagle_protocol_v1_services_eagled_eagled_proto_rawDesc = "" +
	"\n" +
	"3steeleagle_protocol/v1/services/eagled/eagled.proto\x12&steeleagle_protocol.v1.services.eagled\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_toml\x18\x01 \x01(\tR\n" +
	"configToml\"\xd8\x01\n" +
	"\x11ConfigureResponse\x12Q\n" +
	"\bvehicles\x18\x01 \x03(\v25.steeleagle_protocol.v1.services.eagled.VehicleResultR\bvehicles\x126\n" +
	"\x17daemon_settings_applied\x18\x02 \x01(\bR\x15daemonSettingsApplied\x128\n" +
	"\x18daemon_settings_diverged\x18\x03 \x01(\bR\x16daemonSettingsDiverged\"+\n" +
	"\x13StopVehiclesRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"i\n" +
	"\x14StopVehiclesResponse\x12Q\n" +
	"\bvehicles\x18\x01 \x03(\v25.steeleagle_protocol.v1.services.eagled.VehicleResultR\bvehicles\".\n" +
	"\x16RestartVehiclesRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"l\n" +
	"\x17RestartVehiclesResponse\x12Q\n" +
	"\bvehicles\x18\x01 \x03(\v25.steeleagle_protocol.v1.services.eagled.VehicleResultR\bvehicles\"-\n" +
	"\x15ForgetVehiclesRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"k\n" +
	"\x16ForgetVehiclesResponse\x12Q\n" +
	"\bvehicles\x18\x01 \x03(\v25.steeleagle_protocol.v1.services.eagled.VehicleResultR\bvehicles\"\x98\x01\n" +
	"\rVehicleResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\"\n" +
	"\freconfigured\x18\x04 \x01(\bR\freconfigured\x12)\n" +
	"\x10restart_required\x18\x05 \x01(\bR\x0frestartRequired\"\xbe\x01\n" +
	"\x14InstallPluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x18\n" +
	"\asubpath\x18\x04 \x01(\tR\asubpath\x12R\n" +
	"\bcategory\x18\x05 \x01(\x0e26.steeleagle_protocol.v1.services.eagled.PluginCategoryR\bcategory\"=\n" +
	"\x15InstallPluginResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1c\n" +
	"\x1aGetInstalledPluginsRequest\"p\n" +
	"\x1bGetInstalledPluginsResponse\x12Q\n" +
	"\aplugins\x18\x01 \x03(\v27.steeleagle_protocol.v1.services.eagled.InstalledPluginR\aplugins\"\x8b\x01\n" +
	"\x0fInstalledPlugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12R\n" +
	"\bcategory\x18\x03 \x01(\x0e26.steeleagle_protocol.v1.services.eagled.PluginCategoryR\bcategory\"\x14\n" +
	"\x12ResetConfigRequest\"\x15\n" +
	"\x13ResetConfigResponse\"\x16\n" +
	"\x14RestartDaemonRequest\"\x17\n" +
	"\x15RestartDaemonResponse\"\x12\n" +
	"\x10GetStatusRequest\"\xd4\x01\n" +
	"\x11GetStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12L\n" +
	"\x06config\x18\x02 \x01(\v24.steeleagle_protocol.v1.services.eagled.DaemonConfigR\x06config\x12Q\n" +
	"\bvehicles\x18\x03 \x03(\v25.steeleagle_protocol.v1.services.eagled.VehicleStatusR\bvehicles\"\xf3\x02\n" +
	"\fDaemonConfig\x12\x10\n" +
	"\x03vpn\x18\x01 \x01(\bR\x03vpn\x12\x1f\n" +
	"\vvehicle_vpn\x18\x02 \x01(\bR\n" +
	"vehicleVpn\x12\x1b\n" +
	"\tport_base\x18\x03 \x01(\x05R\bportBase\x12\x1d\n" +
	"\n" +
	"plugin_dir\x18\x04 \x01(\tR\tpluginDir\x12-\n" +
	"\x12tailscale_hostname\x18\x05 \x01(\tR\x11tailscaleHostname\x122\n" +
	"\x15tailscale_authkey_env\x18\x06 \x01(\tR\x13tailscaleAuthkeyEnv\x128\n" +
	"\x18swarm_controller_address\x18\a \x01(\tR\x16swarmControllerAddress\x12\x1f\n" +
	"\vdaemon_name\x18\b \x01(\tR\n" +
	"daemonName\x126\n" +
	"\x17gabriel_server_endpoint\x18\t \x01(\tR\x15gabrielServerEndpoint\"\x8c\x01\n" +
	"\rVehicleStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12!\n" +
	"\fconfig_stale\x18\x05 \x01(\bR\vconfigStale\"\xfc\x01\n" +
	"\x11StreamLogsRequest\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x05R\x04tail\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12d\n" +
	"\tafter_seq\x18\x04 \x03(\v2G.steeleagle_protocol.v1.services.eagled.StreamLogsRequest.AfterSeqEntryR\bafterSeq\x1a;\n" +
	"\rAfterSeqEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa9\x01\n" +
	"\tLogRecord\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\adropped\x18\x06 \x01(\x04R\adropped\"\x17\n" +
	"\x15ListLogSourcesRequest\"e\n" +
	"\x16ListLogSourcesResponse\x12K\n" +
	"\asources\x18\x01 \x03(\v21.steeleagle_protocol.v1.services.eagled.LogSourceR\asources\"X\n" +
	"\tLogSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes*\x85\x01\n" +
	"\x0ePluginCategory\x12\x1f\n" +
	"\x1bPLUGIN_CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PLUGIN_CATEGORY_DRIVER\x10\x01\x12\x1b\n" +
	"\x17PLUGIN_CATEGORY_MISSION\x10\x02\x12\x19\n" +
	"\x15PLUGIN_CATEGORY_EXTRA\x10\x032\xb6\f\n" +
	"\rDaemonService\x12\x82\x01\n" +
	"\tConfigure\x128.steeleagle_protocol.v1.services.eagled.ConfigureRequest\x1a9.steeleagle_protocol.v1.services.eagled.ConfigureResponse\"\x00\x12\x8b\x01\n" +
	"\fStopVehicles\x12;.steeleagle_protocol.v1.services.eagled.StopVehiclesRequest\x1a<.steeleagle_protocol.v1.services.eagled.StopVehiclesResponse\"\x00\x12\x94\x01\n" +
	"\x0fRestartVehicles\x12>.steeleagle_protocol.v1.services.eagled.RestartVehiclesRequest\x1a?.steeleagle_protocol.v1.services.eagled.RestartVehiclesResponse\"\x00\x12\x91\x01\n" +
	"\x0eForgetVehicles\x12=.steeleagle_protocol.v1.services.eagled.ForgetVehiclesRequest\x1a>.steeleagle_protocol.v1.services.eagled.ForgetVehiclesResponse\"\x00\x12\x8e\x01\n" +
	"\rInstallPlugin\x12<.steeleagle_protocol.v1.services.eagled.InstallPluginRequest\x1a=.steeleagle_protocol.v1.services.eagled.InstallPluginResponse\"\x00\x12\xa0\x01\n" +
	"\x13GetInstalledPlugins\x12B.steeleagle_protocol.v1.services.eagled.GetInstalledPluginsRequest\x1aC.steeleagle_protocol.v1.services.eagled.GetInstalledPluginsResponse\"\x00\x12\x88\x01\n" +
	"\vResetConfig\x12:.steeleagle_protocol.v1.services.eagled.ResetConfigRequest\x1a;.steeleagle_protocol.v1.services.eagled.ResetConfigResponse\"\x00\x12\x8e\x01\n" +
	"\rRestartDaemon\x12<.steeleagle_protocol.v1.services.eagled.RestartDaemonRequest\x1a=.steeleagle_protocol.v1.services.eagled.RestartDaemonResponse\"\x00\x12\x82\x01\n" +
	"\tGetStatus\x128.steeleagle_protocol.v1.services.eagled.GetStatusRequest\x1a9.steeleagle_protocol.v1.services.eagled.GetStatusResponse\"\x00\x12~\n" +
	"\n" +
	"StreamLogs\x129.steeleagle_protocol.v1.services.eagled.StreamLogsRequest\x1a1.steeleagle_protocol.v1.services.eagled.LogRecord\"\x000\x01\x12\x91\x01\n" +
	"\x0eListLogSources\x12=.steeleagle_protocol.v1.services.eagled.ListLogSourcesRequest\x1a>.steeleagle_protocol.v1.services.eagled.ListLogSourcesResponse\"\x00B\xc2\x02\n" +
	"*com.steeleagle_protocol.v1.services.eagledB\vEagledProtoP\x01ZOgithub.com/cmusatyalab/steeleagle/api/go/steeleagle_protocol/v1/services/eagled\xa2\x02\x04SVSE\xaa\x02%SteeleagleProtocol.V1.Services.Eagled\xca\x02%SteeleagleProtocol\\V1\\Services\\Eagled\xe2\x021SteeleagleProtocol\\V1\\Services\\Eagled\\GPBMetadata\xea\x02(SteeleagleProtocol::V1::Services::Eagledb\x06proto3"

var file_steeleagle_protocol_v1_services_eagled_eagled_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_steeleagle_protocol_v1_services_eagled_eagled_proto_goTypes = []any{
	(PluginCategory)(0),                 // 0: steeleagle_protocol.v1.services.eagled.PluginCategory
	(*ConfigureRequest)(nil),            // 1: steeleagle_protocol.v1.services.eagled.ConfigureRequest
	(*ConfigureResponse)(nil),           // 2: steeleagle_protocol.v1.services.eagled.ConfigureResponse
	(*StopVehiclesRequest)(nil),         // 3: steeleagle_protocol.v1.services.eagled.StopVehiclesRequest
	(*StopVehiclesResponse)(nil),        // 4: steeleagle_protocol.v1.services.eagled.StopVehiclesResponse
	(*RestartVehiclesRequest)(nil),      // 5: steeleagle_protocol.v1.services.eagled.RestartVehiclesRequest
	(*RestartVehiclesResponse)(nil),     // 6: steeleagle_protocol.v1.services.eagled.RestartVehiclesResponse
	(*ForgetVehiclesRequest)(nil),       // 7: steeleagle_protocol.v1.services.eagled.ForgetVehiclesRequest
	(*ForgetVehiclesResponse)(nil),      // 8: steeleagle_protocol.v1.services.eagled.ForgetVehiclesResponse
	(*VehicleResult)(nil),               // 9: steeleagle_protocol.v1.services.eagled.VehicleResult
	(*InstallPluginRequest)(nil),        // 10: steeleagle_protocol.v1.services.eagled.InstallPluginRequest
	(*InstallPluginResponse)(nil),       // 11: steeleagle_protocol.v1.services.eagled.InstallPluginResponse
	(*GetInstalledPluginsRequest)(nil),  // 12: steeleagle_protocol.v1.services.eagled.GetInstalledPluginsRequest
	(*GetInstalledPluginsResponse)(nil), // 13: steeleagle_protocol.v1.services.eagled.GetInstalledPluginsResponse
	(*InstalledPlugin)(nil),             // 14: steeleagle_protocol.v1.services.eagled.InstalledPlugin
	(*ResetConfigRequest)(nil),          // 15: steeleagle_protocol.v1.services.eagled.ResetConfigRequest
	(*ResetConfigResponse)(nil),         // 16: steeleagle_protocol.v1.services.eagled.ResetConfigResponse
	(*RestartDaemonRequest)(nil),        // 17: steeleagle_protocol.v1.services.eagled.RestartDaemonRequest
	(*RestartDaemonResponse)(nil),       // 18: steeleagle_protocol.v1.services.eagled.RestartDaemonResponse
	(*GetStatusRequest)(nil),            // 19: steeleagle_protocol.v1.services.eagled.GetStatusRequest
	(*GetStatusResponse)(nil),           // 20: steeleagle_protocol.v1.services.eagled.GetStatusResponse
	(*DaemonConfig)(nil),                // 21: steeleagle_protocol.v1.services.eagled.DaemonConfig
	(*VehicleStatus)(nil),               // 22: steeleagle_protocol.v1.services.eagled.VehicleStatus
	(*StreamLogsRequest)(nil),           // 23: steeleagle_protocol.v1.services.eagled.StreamLogsRequest
	(*LogRecord)(nil),                   // 24: steeleagle_protocol.v1.services.eagled.LogRecord
	(*ListLogSourcesRequest)(nil),       // 25: steeleagle_protocol.v1.services.eagled.ListLogSourcesRequest
	(*ListLogSourcesResponse)(nil),      // 26: steeleagle_protocol.v1.services.eagled.ListLogSourcesResponse
	(*LogSource)(nil),                   // 27: steeleagle_protocol.v1.services.eagled.LogSource
	nil,                                 // 28: steeleagle_protocol.v1.services.eagled.StreamLogsRequest.AfterSeqEntry
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
}
var file_steeleagle_protocol_v1_services_eagled_eagled_proto_depIdxs = []int32{
	9,  // 0: steeleagle_protocol.v1.services.eagled.ConfigureResponse.vehicles:type_name -> steeleagle_protocol.v1.services.eagled.VehicleResult
	9,  // 1: steeleagle_protocol.v1.services.eagled.StopVehiclesResponse.vehicles:type_name -> steeleagle_protocol.v1.services.eagled.VehicleResult
	9,  // 2: steeleagle_protocol.v1.services.eagled.RestartVehiclesResponse.vehicles:type_name -> steeleagle_protocol.v1.services.eagled.VehicleResult
	9,  // 3: steeleagle_protocol.v1.services.eagled.ForgetVehiclesResponse.vehicles:type_name -> steeleagle_protocol.v1.services.eagled.VehicleResult
	0,  // 4: steeleagle_protocol.v1.services.eagled.InstallPluginRequest.category:type_name -> steeleagle_protocol.v1.services.eagled.PluginCategory
	14, // 5: steeleagle_protocol.v1.services.eagled.GetInstalledPluginsResponse.plugins:type_name -> steeleagle_protocol.v1.services.eagled.InstalledPlugin
	0,  // 6: steeleagle_protocol.v1.services.eagled.InstalledPlugin.category:type_name -> steeleagle_protocol.v1.services.eagled.PluginCategory
	21, // 7: steeleagle_protocol.v1.services.eagled.GetStatusResponse.config:type_name -> steeleagle_protocol.v1.services.eagled.DaemonConfig
	22, // 8: steeleagle_protocol.v1.services.eagled.GetStatusResponse.vehicles:type_name -> steeleagle_protocol.v1.services.eagled.VehicleStatus
	28, // 9: steeleagle_protocol.v1.services.eagled.StreamLogsRequest.after_seq:type_name -> steeleagle_protocol.v1.services.eagled.StreamLogsRequest.AfterSeqEntry
	29, // 10: steeleagle_protocol.v1.services.eagled.LogRecord.time:type_name -> google.protobuf.Timestamp
	27, // 11: steeleagle_protocol.v1.services.eagled.ListLogSourcesResponse.sources:type_name -> steeleagle_protocol.v1.services.eagled.LogSource
	1,  // 12: steeleagle_protocol.v1.services.eagled.DaemonService.Configure:input_type -> steeleagle_protocol.v1.services.eagled.ConfigureRequest
	3,  // 13: steeleagle_protocol.v1.services.eagled.DaemonService.StopVehicles:input_type -> steeleagle_protocol.v1.services.eagled.StopVehiclesRequest
	5,  // 14: steeleagle_protocol.v1.services.eagled.DaemonService.RestartVehicles:input_type -> steeleagle_protocol.v1.services.eagled.RestartVehiclesRequest
	7,  // 15: steeleagle_protocol.v1.services.eagled.DaemonService.ForgetVehicles:input_type -> steeleagle_protocol.v1.services.eagled.ForgetVehiclesRequest
	10, // 16: steeleagle_protocol.v1.services.eagled.DaemonService.InstallPlugin:input_type -> steeleagle_protocol.v1.services.eagled.InstallPluginRequest
	12, // 17: steeleagle_protocol.v1.services.eagled.DaemonService.GetInstalledPlugins:input_type -> steeleagle_protocol.v1.services.eagled.GetInstalledPluginsRequest
	15, // 18: steeleagle_protocol.v1.services.eagled.DaemonService.ResetConfig:input_type -> steeleagle_protocol.v1.services.eagled.ResetConfigRequest
	17, // 19: steeleagle_protocol.v1.services.eagled.DaemonService.RestartDaemon:input_type -> steeleagle_protocol.v1.services.eagled.RestartDaemonRequest
	19, // 20: steeleagle_protocol.v1.services.eagled.DaemonService.GetStatus:input_type -> steeleagle_protocol.v1.services.eagled.GetStatusRequest
	23, // 21: steeleagle_protocol.v1.services.eagled.DaemonService.StreamLogs:input_type -> steeleagle_protocol.v1.services.eagled.StreamLogsRequest
	25, // 22: steeleagle_protocol.v1.services.eagled.DaemonService.ListLogSources:input_type -> steeleagle_protocol.v1.services.eagled.ListLogSourcesRequest
	2,  // 23: steeleagle_protocol.v1.services.eagled.DaemonService.Configure:output_type -> steeleagle_protocol.v1.services.eagled.ConfigureResponse
	4,  // 24: steeleagle_protocol.v1.services.eagled.DaemonService.StopVehicles:output_type -> steeleagle_protocol.v1.services.eagled.StopVehiclesResponse
	6,  // 25: steeleagle_protocol.v1.services.eagled.DaemonService.RestartVehicles:output_type -> steeleagle_protocol.v1.services.eagled.RestartVehiclesResponse
	8,  // 26: steeleagle_protocol.v1.services.eagled.DaemonService.ForgetVehicles:output_type -> steeleagle_protocol.v1.services.eagled.ForgetVehiclesResponse
	11, // 27: steeleagle_protocol.v1.services.eagled.DaemonService.InstallPlugin:output_type -> steeleagle_protocol.v1.services.eagled.InstallPluginResponse
	13, // 28: steeleagle_protocol.v1.services.eagled.DaemonService.GetInstalledPlugins:output_type -> steeleagle_protocol.v1.services.eagled.GetInstalledPluginsResponse
	16, // 29: steeleagle_protocol.v1.services.eagled.DaemonService.ResetConfig:output_type -> steeleagle_protocol.v1.services.eagled.ResetConfigResponse
	18, // 30: steeleagle_protocol.v1.services.eagled.DaemonService.RestartDaemon:output_type -> steeleagle_protocol.v1.services.eagled.RestartDaemonResponse
	20, // 31: steeleagle_protocol.v1.services.eagled.DaemonService.GetStatus:output_type -> steeleagle_protocol.v1.services.eagled.GetStatusResponse
	24, // 32: steeleagle_protocol.v1.services.eagled.DaemonService.StreamLogs:output_type -> steeleagle_protocol.v1.services.eagled.LogRecord
	26, // 33: steeleagle_protocol.v1.services.eagled.DaemonService.ListLogSources:output_type -> steeleagle_protocol.v1.services.eagled.ListLogSourcesResponse
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_steeleagle_protocol_v1_services_eagled_eagled_proto_init() }
func file_steeleagle_protocol_v1_services_eagled_eagled_proto_init() {
	if File_steeleagle_protocol_v1_services_eagled_eagled_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steeleagle_protocol_v1_services_eagled_eagled_proto_rawDesc), len(file_steeleagle_protocol_v1_services_eagled_eagled_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steeleagle_protocol_v1_services_eagled_eagled_proto_goTypes,
		DependencyIndexes: file_steeleagle_protocol_v1_services_eagled_eagled_proto_depIdxs,
		EnumInfos:         file_steeleagle_protocol_v1_services_eagled_eagled_proto_enumTypes,
		MessageInfos:      file_steeleagle_protocol_v1_services_eagled_eagled_proto_msgTypes,
	}.Build()
	File_steeleagle_protocol_v1_services_eagled_eagled_proto = out.File
	file_steeleagle_protocol_v1_services_eagled_eagled_proto_goTypes = nil
	file_steeleagle_protocol_v1_services_eagled_eagled_proto_depIdxs = nil
}
