export STEELEAGLE_DRIVER_COMMAND_ADDR='127.0.0.1:5001'
export STEELEAGLE_KERNEL_COMMAND_ADDR='127.0.0.1:5002'
export PYTHONPATH=~/Documents/steeleagle/os/
export STEELEAGLE_DRIVER_ARGS='{}'
export STEELEAGLE_DRONE_ARGS='{"sim":true}'
