name: Build and push swiftmap engine

on:
  push:
    branches: [ "v4.0-beta" ]
    paths:
      - '.github/workflows/build-swiftmap-engine.yml'
      - 'backend/server/engines/swiftmap/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-swiftmap-engine
      dockerfile: backend/server/engines/swiftmap/Dockerfile
      free_disk_space: true
      ctx: backend/server/engines/swiftmap/
    secrets: inherit
