name: Build and push SLAM engine

on:
  push:
    branches: [ "v4.0-beta" ]
    paths:
      - '.github/workflows/build-slam-engine.yml'
      - 'backend/server/engines/slam/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/deploy-docker-img.yml
    with:
      name: steeleagle-slam-engine
      dockerfile: backend/server/engines/slam/Dockerfile.slam
      free_disk_space: true
      ctx: backend/server/engines/slam/
    secrets: inherit
