name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download protobuf compiler
        run: wget https://github.com/protocolbuffers/protobuf/releases/download/v29.4/protoc-29.4-linux-x86_64.zip

      - name: Unzip protobuf compiler
        run: unzip -d protobuf protoc-29.4-linux-x86_64.zip

      - name: Build protobufs
        run: cd protocol && PROTOC_PATH=../protobuf/bin/protoc ./build.sh
      - uses: astral-sh/ruff-action@v3
